/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.company.delegate;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.*;
import java.util.concurrent.*;

import org.axonframework.messaging.responsetypes.ResponseTypes;
import org.axonframework.commandhandling.gateway.CommandGateway;
import org.axonframework.queryhandling.QueryGateway;
import org.axonframework.queryhandling.QueryUpdateEmitter;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;

import com.company.api.*;
import com.company.entity.*;
import com.company.exception.*;
import com.company.validator.*;

/**
 *
 * <h2>Bank business delegate</h2>
 *
 * <p>
 * This class implements the Business Delegate design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of Bank related services in the case of a Bank business related service failing.</li>
 * <li>Exposes a simpler, uniform Bank interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill Bank business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */

public class BankBusinessDelegate 
extends BaseBusinessDelegate {
//************************************************************************
// Public Methods
//************************************************************************
    /** 
     * Default Constructor 
     */
    public BankBusinessDelegate()  {
    	queryGateway 		= applicationContext.getBean(QueryGateway.class);
    	commandGateway 		= applicationContext.getBean(CommandGateway.class);
    	queryUpdateEmitter  = applicationContext.getBean(QueryUpdateEmitter.class);
	}


   /**
	* Bank Business Delegate Factory Method
	*
	* All methods are expected to be self-sufficient.
	*
	* @return 	BankBusinessDelegate
	*/
	public static BankBusinessDelegate getBankInstance() {
		return( new BankBusinessDelegate() );
	}
 
   /**
    * Creates the provided command.
    * 
    * @param		command ${class.getCreateCommandAlias()}
    * @exception    ProcessingException
    * @exception	IllegalArgumentException
    * @return		CompletableFuture<UUID>
    */
	public CompletableFuture<UUID> createBank( CreateBankCommand command )
    throws ProcessingException, IllegalArgumentException {

		CompletableFuture<UUID> completableFuture = null;
				
		try {
			// --------------------------------------
        	// assign identity now if none
        	// -------------------------------------- 
			if ( command.getBankId() == null )
				command.setBankId( UUID.randomUUID() );
				
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	BankValidator.getInstance().validate( command );    

    		// ---------------------------------------
    		// issue the CreateBankCommand - by convention the future return value for a create command
        	// that is handled by the constructor of an aggregate will return the UUID 
    		// ---------------------------------------
        	completableFuture = commandGateway.send( command );
        	
			LOGGER.log( Level.INFO, "return from Command Gateway for CreateBankCommand of Bank is " + command );
			
        }
        catch (Exception exc) {
            final String errMsg = "Unable to create Bank - " + exc;
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return completableFuture;
    }

   /**
    * Update the provided command.
    * @param		command UpdateBankCommand
    * @return		CompletableFuture<Void>
    * @exception    ProcessingException
    * @exception  	IllegalArgumentException
    */
    public CompletableFuture<Void> updateBank( UpdateBankCommand command ) 
    throws ProcessingException, IllegalArgumentException {
    	CompletableFuture<Void> completableFuture = null;
    	
    	try {       

			// --------------------------------------
        	// validate 
        	// --------------------------------------    	
        	BankValidator.getInstance().validate( command );    

        	// --------------------------------------
        	// issue the UpdateBankCommand and return right away
        	// --------------------------------------    	
        	completableFuture = commandGateway.send( command );
    	}
        catch (Exception exc) {
            final String errMsg = "Unable to save Bank - " + exc;
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        
    	return completableFuture;
    }
   
   /**
    * Deletes the associatied value object
    * @param		command DeleteBankCommand
    * @return		CompletableFuture<Void>
    * @exception 	ProcessingException
    */
    public CompletableFuture<Void> delete( DeleteBankCommand command ) 
    throws ProcessingException, IllegalArgumentException {	
    	
    	CompletableFuture<Void> completableFuture = null;
    	
        try {  
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	BankValidator.getInstance().validate( command );    
        	
        	// --------------------------------------
        	// issue the DeleteBankCommand and return right away
        	// --------------------------------------    	
        	completableFuture = commandGateway.send( command );
        }
        catch (Exception exc) {
            final String errMsg = "Unable to delete Bank using Id = "  + command.getBankId();
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }
        
        return completableFuture;
    }

    /**
     * Method to retrieve the Bank via BankFetchOneSummary
     * @param 	summary BankFetchOneSummary 
     * @return 	BankFetchOneResponse
     * @exception ProcessingException - Thrown if processing any related problems
     * @exception IllegalArgumentException 
     */
    public Bank getBank( BankFetchOneSummary summary ) 
    throws ProcessingException, IllegalArgumentException {
    	
    	if( summary == null )
    		throw new IllegalArgumentException( "BankFetchOneSummary arg cannot be null" );
    	
    	Bank entity = null;
    	
        try {
        	// --------------------------------------
        	// validate the fetch one summary
        	// --------------------------------------    	
        	BankValidator.getInstance().validate( summary );    
        	
        	// --------------------------------------
        	// use queryGateway to send request to Find a Bank
        	// --------------------------------------
        	CompletableFuture<Bank> futureEntity = queryGateway.query(new FindBankQuery( new LoadBankFilter( summary.getBankId() ) ), ResponseTypes.instanceOf(Bank.class));
        	
        	entity = futureEntity.get();
        }
        catch( Exception exc ) {
            final String errMsg = "Unable to locate Bank with id " + summary.getBankId();
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return entity;
    }


    /**
     * Method to retrieve a collection of all Banks
     *
     * @return 	List<Bank> 
     * @exception ProcessingException Thrown if any problems
     */
    public List<Bank> getAllBank() 
    throws ProcessingException {
        List<Bank> list = null;

        try {
        	CompletableFuture<List<Bank>> futureList = queryGateway.query(new FindAllBankQuery(), ResponseTypes.multipleInstancesOf(Bank.class));
        	
        	list = futureList.get();
        }
        catch( Exception exc ) {
            String errMsg = "Failed to get all Bank";
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return list;
    }


    /**
     * add Branch to Branches 
     * @param		command AssignBranchesToBankCommand
     * @exception	ProcessingException
     */     
	public void addToBranches( AssignBranchesToBankCommand command ) throws ProcessingException {
		
		
		// -------------------------------------------
		// load the parent
		// -------------------------------------------
		load( command.getBankId() );

		BranchBusinessDelegate childDelegate 	= BranchBusinessDelegate.getBranchInstance();
		BankBusinessDelegate parentDelegate = BankBusinessDelegate.getBankInstance();		
		UUID childId = command.getAddTo().getBranchId();
		
		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	BankValidator.getInstance().validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );			
		}
		catch( Exception exc ) {
			final String msg = "Failed to add a Branch as Branches to Bank" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove Branch from Branches
     * @param		command RemoveBranchesFromBankCommand
     * @exception	ProcessingException
     */     	
	public void removeFromBranches( RemoveBranchesFromBankCommand command ) throws ProcessingException {		
		
		BranchBusinessDelegate childDelegate 	= BranchBusinessDelegate.getBranchInstance();
		UUID childId = command.getRemoveFrom().getBranchId();

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	BankValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + childId; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add BankingProduct to Products 
     * @param		command AssignProductsToBankCommand
     * @exception	ProcessingException
     */     
	public void addToProducts( AssignProductsToBankCommand command ) throws ProcessingException {
		
		
		// -------------------------------------------
		// load the parent
		// -------------------------------------------
		load( command.getBankId() );

		BankingProductBusinessDelegate childDelegate 	= BankingProductBusinessDelegate.getBankingProductInstance();
		BankBusinessDelegate parentDelegate = BankBusinessDelegate.getBankInstance();		
		UUID childId = command.getAddTo().getBankingProductId();
		
		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	BankValidator.getInstance().validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );			
		}
		catch( Exception exc ) {
			final String msg = "Failed to add a BankingProduct as Products to Bank" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove BankingProduct from Products
     * @param		command RemoveProductsFromBankCommand
     * @exception	ProcessingException
     */     	
	public void removeFromProducts( RemoveProductsFromBankCommand command ) throws ProcessingException {		
		
		BankingProductBusinessDelegate childDelegate 	= BankingProductBusinessDelegate.getBankingProductInstance();
		UUID childId = command.getRemoveFrom().getBankingProductId();

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	BankValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + childId; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add Customer to Customers 
     * @param		command AssignCustomersToBankCommand
     * @exception	ProcessingException
     */     
	public void addToCustomers( AssignCustomersToBankCommand command ) throws ProcessingException {
		
		
		// -------------------------------------------
		// load the parent
		// -------------------------------------------
		load( command.getBankId() );

		CustomerBusinessDelegate childDelegate 	= CustomerBusinessDelegate.getCustomerInstance();
		BankBusinessDelegate parentDelegate = BankBusinessDelegate.getBankInstance();		
		UUID childId = command.getAddTo().getCustomerId();
		
		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	BankValidator.getInstance().validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );			
		}
		catch( Exception exc ) {
			final String msg = "Failed to add a Customer as Customers to Bank" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove Customer from Customers
     * @param		command RemoveCustomersFromBankCommand
     * @exception	ProcessingException
     */     	
	public void removeFromCustomers( RemoveCustomersFromBankCommand command ) throws ProcessingException {		
		
		CustomerBusinessDelegate childDelegate 	= CustomerBusinessDelegate.getCustomerInstance();
		UUID childId = command.getRemoveFrom().getCustomerId();

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	BankValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + childId; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add Account to Accounts 
     * @param		command AssignAccountsToBankCommand
     * @exception	ProcessingException
     */     
	public void addToAccounts( AssignAccountsToBankCommand command ) throws ProcessingException {
		
		
		// -------------------------------------------
		// load the parent
		// -------------------------------------------
		load( command.getBankId() );

		AccountBusinessDelegate childDelegate 	= AccountBusinessDelegate.getAccountInstance();
		BankBusinessDelegate parentDelegate = BankBusinessDelegate.getBankInstance();		
		UUID childId = command.getAddTo().getAccountId();
		
		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	BankValidator.getInstance().validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );			
		}
		catch( Exception exc ) {
			final String msg = "Failed to add a Account as Accounts to Bank" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove Account from Accounts
     * @param		command RemoveAccountsFromBankCommand
     * @exception	ProcessingException
     */     	
	public void removeFromAccounts( RemoveAccountsFromBankCommand command ) throws ProcessingException {		
		
		AccountBusinessDelegate childDelegate 	= AccountBusinessDelegate.getAccountInstance();
		UUID childId = command.getRemoveFrom().getAccountId();

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	BankValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + childId; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add PaymentCard to PaymentCards 
     * @param		command AssignPaymentCardsToBankCommand
     * @exception	ProcessingException
     */     
	public void addToPaymentCards( AssignPaymentCardsToBankCommand command ) throws ProcessingException {
		
		
		// -------------------------------------------
		// load the parent
		// -------------------------------------------
		load( command.getBankId() );

		PaymentCardBusinessDelegate childDelegate 	= PaymentCardBusinessDelegate.getPaymentCardInstance();
		BankBusinessDelegate parentDelegate = BankBusinessDelegate.getBankInstance();		
		UUID childId = command.getAddTo().getPaymentCardId();
		
		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	BankValidator.getInstance().validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );			
		}
		catch( Exception exc ) {
			final String msg = "Failed to add a PaymentCard as PaymentCards to Bank" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove PaymentCard from PaymentCards
     * @param		command RemovePaymentCardsFromBankCommand
     * @exception	ProcessingException
     */     	
	public void removeFromPaymentCards( RemovePaymentCardsFromBankCommand command ) throws ProcessingException {		
		
		PaymentCardBusinessDelegate childDelegate 	= PaymentCardBusinessDelegate.getPaymentCardInstance();
		UUID childId = command.getRemoveFrom().getPaymentCardId();

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	BankValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + childId; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add LoanAccount to LoanAccounts 
     * @param		command AssignLoanAccountsToBankCommand
     * @exception	ProcessingException
     */     
	public void addToLoanAccounts( AssignLoanAccountsToBankCommand command ) throws ProcessingException {
		
		
		// -------------------------------------------
		// load the parent
		// -------------------------------------------
		load( command.getBankId() );

		LoanAccountBusinessDelegate childDelegate 	= LoanAccountBusinessDelegate.getLoanAccountInstance();
		BankBusinessDelegate parentDelegate = BankBusinessDelegate.getBankInstance();		
		UUID childId = command.getAddTo().getLoanAccountId();
		
		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	BankValidator.getInstance().validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );			
		}
		catch( Exception exc ) {
			final String msg = "Failed to add a LoanAccount as LoanAccounts to Bank" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove LoanAccount from LoanAccounts
     * @param		command RemoveLoanAccountsFromBankCommand
     * @exception	ProcessingException
     */     	
	public void removeFromLoanAccounts( RemoveLoanAccountsFromBankCommand command ) throws ProcessingException {		
		
		LoanAccountBusinessDelegate childDelegate 	= LoanAccountBusinessDelegate.getLoanAccountInstance();
		UUID childId = command.getRemoveFrom().getLoanAccountId();

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	BankValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + childId; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add ExchangeRate to ExchangeRates 
     * @param		command AssignExchangeRatesToBankCommand
     * @exception	ProcessingException
     */     
	public void addToExchangeRates( AssignExchangeRatesToBankCommand command ) throws ProcessingException {
		
		
		// -------------------------------------------
		// load the parent
		// -------------------------------------------
		load( command.getBankId() );

		ExchangeRateBusinessDelegate childDelegate 	= ExchangeRateBusinessDelegate.getExchangeRateInstance();
		BankBusinessDelegate parentDelegate = BankBusinessDelegate.getBankInstance();		
		UUID childId = command.getAddTo().getExchangeRateId();
		
		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	BankValidator.getInstance().validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );			
		}
		catch( Exception exc ) {
			final String msg = "Failed to add a ExchangeRate as ExchangeRates to Bank" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove ExchangeRate from ExchangeRates
     * @param		command RemoveExchangeRatesFromBankCommand
     * @exception	ProcessingException
     */     	
	public void removeFromExchangeRates( RemoveExchangeRatesFromBankCommand command ) throws ProcessingException {		
		
		ExchangeRateBusinessDelegate childDelegate 	= ExchangeRateBusinessDelegate.getExchangeRateInstance();
		UUID childId = command.getRemoveFrom().getExchangeRateId();

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	BankValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + childId; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add Consent to Consents 
     * @param		command AssignConsentsToBankCommand
     * @exception	ProcessingException
     */     
	public void addToConsents( AssignConsentsToBankCommand command ) throws ProcessingException {
		
		
		// -------------------------------------------
		// load the parent
		// -------------------------------------------
		load( command.getBankId() );

		ConsentBusinessDelegate childDelegate 	= ConsentBusinessDelegate.getConsentInstance();
		BankBusinessDelegate parentDelegate = BankBusinessDelegate.getBankInstance();		
		UUID childId = command.getAddTo().getConsentId();
		
		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	BankValidator.getInstance().validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );			
		}
		catch( Exception exc ) {
			final String msg = "Failed to add a Consent as Consents to Bank" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove Consent from Consents
     * @param		command RemoveConsentsFromBankCommand
     * @exception	ProcessingException
     */     	
	public void removeFromConsents( RemoveConsentsFromBankCommand command ) throws ProcessingException {		
		
		ConsentBusinessDelegate childDelegate 	= ConsentBusinessDelegate.getConsentInstance();
		UUID childId = command.getRemoveFrom().getConsentId();

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	BankValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + childId; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add ThirdPartyProvider to ThirdPartyProviders 
     * @param		command AssignThirdPartyProvidersToBankCommand
     * @exception	ProcessingException
     */     
	public void addToThirdPartyProviders( AssignThirdPartyProvidersToBankCommand command ) throws ProcessingException {
		
		
		// -------------------------------------------
		// load the parent
		// -------------------------------------------
		load( command.getBankId() );

		ThirdPartyProviderBusinessDelegate childDelegate 	= ThirdPartyProviderBusinessDelegate.getThirdPartyProviderInstance();
		BankBusinessDelegate parentDelegate = BankBusinessDelegate.getBankInstance();		
		UUID childId = command.getAddTo().getThirdPartyProviderId();
		
		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	BankValidator.getInstance().validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );			
		}
		catch( Exception exc ) {
			final String msg = "Failed to add a ThirdPartyProvider as ThirdPartyProviders to Bank" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove ThirdPartyProvider from ThirdPartyProviders
     * @param		command RemoveThirdPartyProvidersFromBankCommand
     * @exception	ProcessingException
     */     	
	public void removeFromThirdPartyProviders( RemoveThirdPartyProvidersFromBankCommand command ) throws ProcessingException {		
		
		ThirdPartyProviderBusinessDelegate childDelegate 	= ThirdPartyProviderBusinessDelegate.getThirdPartyProviderInstance();
		UUID childId = command.getRemoveFrom().getThirdPartyProviderId();

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	BankValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + childId; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}



	/**
	 * Internal helper method to load the root 
	 * 
	 * @param		id	UUID
	 * @return		Bank
	 */
	protected Bank load( UUID id ) throws ProcessingException {
		bank = BankBusinessDelegate.getBankInstance().getBank( new BankFetchOneSummary(id) );	
		return bank;
	}


//************************************************************************
// Attributes
//************************************************************************
	private final QueryGateway queryGateway;
	private final CommandGateway commandGateway;
	private final QueryUpdateEmitter queryUpdateEmitter;
	private Bank bank 	= null;
    private static final Logger LOGGER 			= Logger.getLogger(BankBusinessDelegate.class.getName());
    
}
