/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.company.delegate;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.*;
import java.util.concurrent.*;

import org.axonframework.messaging.responsetypes.ResponseTypes;
import org.axonframework.commandhandling.gateway.CommandGateway;
import org.axonframework.queryhandling.QueryGateway;
import org.axonframework.queryhandling.QueryUpdateEmitter;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;

import com.company.api.*;
import com.company.entity.*;
import com.company.exception.*;
import com.company.validator.*;

/**
 *
 * <h2>LoanAccount business delegate</h2>
 *
 * <p>
 * This class implements the Business Delegate design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of LoanAccount related services in the case of a LoanAccount business related service failing.</li>
 * <li>Exposes a simpler, uniform LoanAccount interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill LoanAccount business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */

public class LoanAccountBusinessDelegate 
extends BaseBusinessDelegate {
//************************************************************************
// Public Methods
//************************************************************************
    /** 
     * Default Constructor 
     */
    public LoanAccountBusinessDelegate()  {
    	queryGateway 		= applicationContext.getBean(QueryGateway.class);
    	commandGateway 		= applicationContext.getBean(CommandGateway.class);
    	queryUpdateEmitter  = applicationContext.getBean(QueryUpdateEmitter.class);
	}


   /**
	* LoanAccount Business Delegate Factory Method
	*
	* All methods are expected to be self-sufficient.
	*
	* @return 	LoanAccountBusinessDelegate
	*/
	public static LoanAccountBusinessDelegate getLoanAccountInstance() {
		return( new LoanAccountBusinessDelegate() );
	}
 
   /**
    * Creates the provided command.
    * 
    * @param		command ${class.getCreateCommandAlias()}
    * @exception    ProcessingException
    * @exception	IllegalArgumentException
    * @return		CompletableFuture<UUID>
    */
	public CompletableFuture<UUID> createLoanAccount( CreateLoanAccountCommand command )
    throws ProcessingException, IllegalArgumentException {

		CompletableFuture<UUID> completableFuture = null;
				
		try {
			// --------------------------------------
        	// assign identity now if none
        	// -------------------------------------- 
			if ( command.getLoanAccountId() == null )
				command.setLoanAccountId( UUID.randomUUID() );
				
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	LoanAccountValidator.getInstance().validate( command );    

    		// ---------------------------------------
    		// issue the CreateLoanAccountCommand - by convention the future return value for a create command
        	// that is handled by the constructor of an aggregate will return the UUID 
    		// ---------------------------------------
        	completableFuture = commandGateway.send( command );
        	
			LOGGER.log( Level.INFO, "return from Command Gateway for CreateLoanAccountCommand of LoanAccount is " + command );
			
        }
        catch (Exception exc) {
            final String errMsg = "Unable to create LoanAccount - " + exc;
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return completableFuture;
    }

   /**
    * Update the provided command.
    * @param		command UpdateLoanAccountCommand
    * @return		CompletableFuture<Void>
    * @exception    ProcessingException
    * @exception  	IllegalArgumentException
    */
    public CompletableFuture<Void> updateLoanAccount( UpdateLoanAccountCommand command ) 
    throws ProcessingException, IllegalArgumentException {
    	CompletableFuture<Void> completableFuture = null;
    	
    	try {       

			// --------------------------------------
        	// validate 
        	// --------------------------------------    	
        	LoanAccountValidator.getInstance().validate( command );    

        	// --------------------------------------
        	// issue the UpdateLoanAccountCommand and return right away
        	// --------------------------------------    	
        	completableFuture = commandGateway.send( command );
    	}
        catch (Exception exc) {
            final String errMsg = "Unable to save LoanAccount - " + exc;
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        
    	return completableFuture;
    }
   
   /**
    * Deletes the associatied value object
    * @param		command DeleteLoanAccountCommand
    * @return		CompletableFuture<Void>
    * @exception 	ProcessingException
    */
    public CompletableFuture<Void> delete( DeleteLoanAccountCommand command ) 
    throws ProcessingException, IllegalArgumentException {	
    	
    	CompletableFuture<Void> completableFuture = null;
    	
        try {  
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	LoanAccountValidator.getInstance().validate( command );    
        	
        	// --------------------------------------
        	// issue the DeleteLoanAccountCommand and return right away
        	// --------------------------------------    	
        	completableFuture = commandGateway.send( command );
        }
        catch (Exception exc) {
            final String errMsg = "Unable to delete LoanAccount using Id = "  + command.getLoanAccountId();
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }
        
        return completableFuture;
    }

    /**
     * Method to retrieve the LoanAccount via LoanAccountFetchOneSummary
     * @param 	summary LoanAccountFetchOneSummary 
     * @return 	LoanAccountFetchOneResponse
     * @exception ProcessingException - Thrown if processing any related problems
     * @exception IllegalArgumentException 
     */
    public LoanAccount getLoanAccount( LoanAccountFetchOneSummary summary ) 
    throws ProcessingException, IllegalArgumentException {
    	
    	if( summary == null )
    		throw new IllegalArgumentException( "LoanAccountFetchOneSummary arg cannot be null" );
    	
    	LoanAccount entity = null;
    	
        try {
        	// --------------------------------------
        	// validate the fetch one summary
        	// --------------------------------------    	
        	LoanAccountValidator.getInstance().validate( summary );    
        	
        	// --------------------------------------
        	// use queryGateway to send request to Find a LoanAccount
        	// --------------------------------------
        	CompletableFuture<LoanAccount> futureEntity = queryGateway.query(new FindLoanAccountQuery( new LoadLoanAccountFilter( summary.getLoanAccountId() ) ), ResponseTypes.instanceOf(LoanAccount.class));
        	
        	entity = futureEntity.get();
        }
        catch( Exception exc ) {
            final String errMsg = "Unable to locate LoanAccount with id " + summary.getLoanAccountId();
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return entity;
    }


    /**
     * Method to retrieve a collection of all LoanAccounts
     *
     * @return 	List<LoanAccount> 
     * @exception ProcessingException Thrown if any problems
     */
    public List<LoanAccount> getAllLoanAccount() 
    throws ProcessingException {
        List<LoanAccount> list = null;

        try {
        	CompletableFuture<List<LoanAccount>> futureList = queryGateway.query(new FindAllLoanAccountQuery(), ResponseTypes.multipleInstancesOf(LoanAccount.class));
        	
        	list = futureList.get();
        }
        catch( Exception exc ) {
            String errMsg = "Failed to get all LoanAccount";
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return list;
    }

    /**
     * assign Bank on LoanAccount
     * @param		command AssignBankToLoanAccountCommand	
     * @exception	ProcessingException
     */     
	public void assignBank( AssignBankToLoanAccountCommand command ) throws ProcessingException {

		// --------------------------------------------
		// load the parent
		// --------------------------------------------
		load( command.getLoanAccountId() );
		
		BankBusinessDelegate childDelegate 	= BankBusinessDelegate.getBankInstance();
		LoanAccountBusinessDelegate parentDelegate = LoanAccountBusinessDelegate.getLoanAccountInstance();			
		UUID childId = command.getAssignment().getBankId();
		Bank child = null;
		
		try {
			// --------------------------------------
	    	// best to validate the command now
	    	// --------------------------------------    
	    	LoanAccountValidator.getInstance().validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );

		}
        catch( Throwable exc ) {
			final String msg = "Failed to get Bank using id " + childId;
			LOGGER.log( Level.WARNING,  msg );
			throw new ProcessingException( msg, exc );
        }
	}

    /**
     * unAssign Bank on LoanAccount
     * @param		command UnAssignBankFromLoanAccountCommand
     * @exception	ProcessingException
     */     
	public void unAssignBank( UnAssignBankFromLoanAccountCommand command ) throws ProcessingException {

		try {
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	LoanAccountValidator.getInstance().validate( command );    
	
	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );
		}
		catch( Exception exc ) {
			final String msg = "Failed to unassign Bank on LoanAccount";
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}
	
    /**
     * assign Branch on LoanAccount
     * @param		command AssignBranchToLoanAccountCommand	
     * @exception	ProcessingException
     */     
	public void assignBranch( AssignBranchToLoanAccountCommand command ) throws ProcessingException {

		// --------------------------------------------
		// load the parent
		// --------------------------------------------
		load( command.getLoanAccountId() );
		
		BranchBusinessDelegate childDelegate 	= BranchBusinessDelegate.getBranchInstance();
		LoanAccountBusinessDelegate parentDelegate = LoanAccountBusinessDelegate.getLoanAccountInstance();			
		UUID childId = command.getAssignment().getBranchId();
		Branch child = null;
		
		try {
			// --------------------------------------
	    	// best to validate the command now
	    	// --------------------------------------    
	    	LoanAccountValidator.getInstance().validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );

		}
        catch( Throwable exc ) {
			final String msg = "Failed to get Branch using id " + childId;
			LOGGER.log( Level.WARNING,  msg );
			throw new ProcessingException( msg, exc );
        }
	}

    /**
     * unAssign Branch on LoanAccount
     * @param		command UnAssignBranchFromLoanAccountCommand
     * @exception	ProcessingException
     */     
	public void unAssignBranch( UnAssignBranchFromLoanAccountCommand command ) throws ProcessingException {

		try {
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	LoanAccountValidator.getInstance().validate( command );    
	
	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );
		}
		catch( Exception exc ) {
			final String msg = "Failed to unassign Branch on LoanAccount";
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}
	
    /**
     * assign Product on LoanAccount
     * @param		command AssignProductToLoanAccountCommand	
     * @exception	ProcessingException
     */     
	public void assignProduct( AssignProductToLoanAccountCommand command ) throws ProcessingException {

		// --------------------------------------------
		// load the parent
		// --------------------------------------------
		load( command.getLoanAccountId() );
		
		BankingProductBusinessDelegate childDelegate 	= BankingProductBusinessDelegate.getBankingProductInstance();
		LoanAccountBusinessDelegate parentDelegate = LoanAccountBusinessDelegate.getLoanAccountInstance();			
		UUID childId = command.getAssignment().getBankingProductId();
		BankingProduct child = null;
		
		try {
			// --------------------------------------
	    	// best to validate the command now
	    	// --------------------------------------    
	    	LoanAccountValidator.getInstance().validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );

		}
        catch( Throwable exc ) {
			final String msg = "Failed to get BankingProduct using id " + childId;
			LOGGER.log( Level.WARNING,  msg );
			throw new ProcessingException( msg, exc );
        }
	}

    /**
     * unAssign Product on LoanAccount
     * @param		command UnAssignProductFromLoanAccountCommand
     * @exception	ProcessingException
     */     
	public void unAssignProduct( UnAssignProductFromLoanAccountCommand command ) throws ProcessingException {

		try {
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	LoanAccountValidator.getInstance().validate( command );    
	
	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );
		}
		catch( Exception exc ) {
			final String msg = "Failed to unassign Product on LoanAccount";
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}
	

    /**
     * add Customer to Borrowers 
     * @param		command AssignBorrowersToLoanAccountCommand
     * @exception	ProcessingException
     */     
	public void addToBorrowers( AssignBorrowersToLoanAccountCommand command ) throws ProcessingException {
		
		
		// -------------------------------------------
		// load the parent
		// -------------------------------------------
		load( command.getLoanAccountId() );

		CustomerBusinessDelegate childDelegate 	= CustomerBusinessDelegate.getCustomerInstance();
		LoanAccountBusinessDelegate parentDelegate = LoanAccountBusinessDelegate.getLoanAccountInstance();		
		UUID childId = command.getAddTo().getCustomerId();
		
		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	LoanAccountValidator.getInstance().validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );			
		}
		catch( Exception exc ) {
			final String msg = "Failed to add a Customer as Borrowers to LoanAccount" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove Customer from Borrowers
     * @param		command RemoveBorrowersFromLoanAccountCommand
     * @exception	ProcessingException
     */     	
	public void removeFromBorrowers( RemoveBorrowersFromLoanAccountCommand command ) throws ProcessingException {		
		
		CustomerBusinessDelegate childDelegate 	= CustomerBusinessDelegate.getCustomerInstance();
		UUID childId = command.getRemoveFrom().getCustomerId();

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	LoanAccountValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + childId; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add RepaymentSchedule to RepaymentSchedule 
     * @param		command AssignRepaymentScheduleToLoanAccountCommand
     * @exception	ProcessingException
     */     
	public void addToRepaymentSchedule( AssignRepaymentScheduleToLoanAccountCommand command ) throws ProcessingException {
		
		
		// -------------------------------------------
		// load the parent
		// -------------------------------------------
		load( command.getLoanAccountId() );

		RepaymentScheduleBusinessDelegate childDelegate 	= RepaymentScheduleBusinessDelegate.getRepaymentScheduleInstance();
		LoanAccountBusinessDelegate parentDelegate = LoanAccountBusinessDelegate.getLoanAccountInstance();		
		UUID childId = command.getAddTo().getRepaymentScheduleId();
		
		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	LoanAccountValidator.getInstance().validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );			
		}
		catch( Exception exc ) {
			final String msg = "Failed to add a RepaymentSchedule as RepaymentSchedule to LoanAccount" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove RepaymentSchedule from RepaymentSchedule
     * @param		command RemoveRepaymentScheduleFromLoanAccountCommand
     * @exception	ProcessingException
     */     	
	public void removeFromRepaymentSchedule( RemoveRepaymentScheduleFromLoanAccountCommand command ) throws ProcessingException {		
		
		RepaymentScheduleBusinessDelegate childDelegate 	= RepaymentScheduleBusinessDelegate.getRepaymentScheduleInstance();
		UUID childId = command.getRemoveFrom().getRepaymentScheduleId();

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	LoanAccountValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + childId; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add LoanPayment to Payments 
     * @param		command AssignPaymentsToLoanAccountCommand
     * @exception	ProcessingException
     */     
	public void addToPayments( AssignPaymentsToLoanAccountCommand command ) throws ProcessingException {
		
		
		// -------------------------------------------
		// load the parent
		// -------------------------------------------
		load( command.getLoanAccountId() );

		LoanPaymentBusinessDelegate childDelegate 	= LoanPaymentBusinessDelegate.getLoanPaymentInstance();
		LoanAccountBusinessDelegate parentDelegate = LoanAccountBusinessDelegate.getLoanAccountInstance();		
		UUID childId = command.getAddTo().getLoanPaymentId();
		
		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	LoanAccountValidator.getInstance().validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );			
		}
		catch( Exception exc ) {
			final String msg = "Failed to add a LoanPayment as Payments to LoanAccount" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove LoanPayment from Payments
     * @param		command RemovePaymentsFromLoanAccountCommand
     * @exception	ProcessingException
     */     	
	public void removeFromPayments( RemovePaymentsFromLoanAccountCommand command ) throws ProcessingException {		
		
		LoanPaymentBusinessDelegate childDelegate 	= LoanPaymentBusinessDelegate.getLoanPaymentInstance();
		UUID childId = command.getRemoveFrom().getLoanPaymentId();

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	LoanAccountValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + childId; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add Collateral to Collateral 
     * @param		command AssignCollateralToLoanAccountCommand
     * @exception	ProcessingException
     */     
	public void addToCollateral( AssignCollateralToLoanAccountCommand command ) throws ProcessingException {
		
		
		// -------------------------------------------
		// load the parent
		// -------------------------------------------
		load( command.getLoanAccountId() );

		CollateralBusinessDelegate childDelegate 	= CollateralBusinessDelegate.getCollateralInstance();
		LoanAccountBusinessDelegate parentDelegate = LoanAccountBusinessDelegate.getLoanAccountInstance();		
		UUID childId = command.getAddTo().getCollateralId();
		
		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	LoanAccountValidator.getInstance().validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );			
		}
		catch( Exception exc ) {
			final String msg = "Failed to add a Collateral as Collateral to LoanAccount" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove Collateral from Collateral
     * @param		command RemoveCollateralFromLoanAccountCommand
     * @exception	ProcessingException
     */     	
	public void removeFromCollateral( RemoveCollateralFromLoanAccountCommand command ) throws ProcessingException {		
		
		CollateralBusinessDelegate childDelegate 	= CollateralBusinessDelegate.getCollateralInstance();
		UUID childId = command.getRemoveFrom().getCollateralId();

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	LoanAccountValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + childId; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add FeeCharge to FeeCharges 
     * @param		command AssignFeeChargesToLoanAccountCommand
     * @exception	ProcessingException
     */     
	public void addToFeeCharges( AssignFeeChargesToLoanAccountCommand command ) throws ProcessingException {
		
		
		// -------------------------------------------
		// load the parent
		// -------------------------------------------
		load( command.getLoanAccountId() );

		FeeChargeBusinessDelegate childDelegate 	= FeeChargeBusinessDelegate.getFeeChargeInstance();
		LoanAccountBusinessDelegate parentDelegate = LoanAccountBusinessDelegate.getLoanAccountInstance();		
		UUID childId = command.getAddTo().getFeeChargeId();
		
		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	LoanAccountValidator.getInstance().validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );			
		}
		catch( Exception exc ) {
			final String msg = "Failed to add a FeeCharge as FeeCharges to LoanAccount" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove FeeCharge from FeeCharges
     * @param		command RemoveFeeChargesFromLoanAccountCommand
     * @exception	ProcessingException
     */     	
	public void removeFromFeeCharges( RemoveFeeChargesFromLoanAccountCommand command ) throws ProcessingException {		
		
		FeeChargeBusinessDelegate childDelegate 	= FeeChargeBusinessDelegate.getFeeChargeInstance();
		UUID childId = command.getRemoveFrom().getFeeChargeId();

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	LoanAccountValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + childId; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}



	/**
	 * Internal helper method to load the root 
	 * 
	 * @param		id	UUID
	 * @return		LoanAccount
	 */
	protected LoanAccount load( UUID id ) throws ProcessingException {
		loanAccount = LoanAccountBusinessDelegate.getLoanAccountInstance().getLoanAccount( new LoanAccountFetchOneSummary(id) );	
		return loanAccount;
	}


//************************************************************************
// Attributes
//************************************************************************
	private final QueryGateway queryGateway;
	private final CommandGateway commandGateway;
	private final QueryUpdateEmitter queryUpdateEmitter;
	private LoanAccount loanAccount 	= null;
    private static final Logger LOGGER 			= Logger.getLogger(LoanAccountBusinessDelegate.class.getName());
    
}
