/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.company.controller.command;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.concurrent.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.company.api.*;
import com.company.delegate.*;
import com.company.entity.*;
import com.company.exception.*;
import com.company.projector.*;

import com.company.controller.*;

/**
 * <h2>ATMCommandRestController as REST API</h2>
 * <p>
 * Implements Spring Controller command CQRS processing for entity ATM.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	ATMBusinessDelegate
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateATMCommand</li>
 *      <li>UpdateATMCommand</li>
 *      <liDeleteATMCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 */

@CrossOrigin
@RestController
@RequestMapping("/ATMCommand")
public class ATMCommandRestController extends BaseSpringRestController {

    /**
     * Handles create a ATM.  if not key provided, calls create, otherwise calls save
     * @param		ATM	aTM
     * @return		CompletableFuture<UUID> 
     */
	@PostMapping("/create")
    public CompletableFuture<UUID> create( @RequestBody(required=true) CreateATMCommand command ) {
		CompletableFuture<UUID> completableFuture = null;
		try {       
        	
			completableFuture = ATMBusinessDelegate.getATMInstance().createATM( command );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage(), exc );        	
        }
		
		return completableFuture;
    }

    /**
     * Handles updating a ATM.  if no key provided, calls create, otherwise calls save
     * @param		ATM aTM
     * @return		CompletableFuture<Void>
     */
	@PutMapping("/update")
    public CompletableFuture<Void> update( @RequestBody(required=true) UpdateATMCommand command ) {
		CompletableFuture<Void> completableFuture = null;
		try {                        	        
			// -----------------------------------------------
			// delegate the UpdateATMCommand
			// -----------------------------------------------
			completableFuture = ATMBusinessDelegate.getATMInstance().updateATM(command);;
	    }
	    catch( Throwable exc ) {
	    	LOGGER.log( Level.WARNING, "ATMController:update() - successfully update ATM - " + exc.getMessage());        	
	    }		
		
		return completableFuture;
	}
 
    /**
     * Handles deleting a ATM entity
     * @param		command ${class.getDeleteCommandAlias()}
     * @return		CompletableFuture<Void>
     */
    @DeleteMapping("/delete")    
    public CompletableFuture<Void> delete( @RequestParam(required=true) UUID aTMId  ) {
    	CompletableFuture<Void> completableFuture = null;
		DeleteATMCommand command = new DeleteATMCommand( aTMId );

    	try {
        	ATMBusinessDelegate delegate = ATMBusinessDelegate.getATMInstance();

        	completableFuture = delegate.delete( command );
    		LOGGER.log( Level.WARNING, "Successfully deleted ATM with key " + command.getATMId() );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage() );
        }
        
        return completableFuture;
	}        
	

    /**
     * save Branch on ATM
     * @param		command AssignBranchToATMCommand
     */     
	@PutMapping("/assignBranch")
	public void assignBranch( @RequestBody AssignBranchToATMCommand command ) {
		try {
			ATMBusinessDelegate.getATMInstance().assignBranch( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Branch", exc );
        }
	}

    /**
     * unassign Branch on ATM
     * @param		 command UnAssignBranchFromATMCommand
     */     
	@PutMapping("/unAssignBranch")
	public void unAssignBranch( @RequestBody(required=true)  UnAssignBranchFromATMCommand command ) {
		try {
			ATMBusinessDelegate.getATMInstance().unAssignBranch( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Branch", exc );
		}
	}
	


//************************************************************************    
// Attributes
//************************************************************************
    protected ATM aTM = null;
    private static final Logger LOGGER = Logger.getLogger(ATMCommandRestController.class.getName());
    
}
