/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.company.controller.command;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.concurrent.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.company.api.*;
import com.company.delegate.*;
import com.company.entity.*;
import com.company.exception.*;
import com.company.projector.*;

import com.company.controller.*;

/**
 * <h2>CollateralCommandRestController as REST API</h2>
 * <p>
 * Implements Spring Controller command CQRS processing for entity Collateral.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>07/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	CollateralBusinessDelegate
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateCollateralCommand</li>
 *      <li>UpdateCollateralCommand</li>
 *      <liDeleteCollateralCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 */

@CrossOrigin
@RestController
@RequestMapping("/CollateralCommand")
public class CollateralCommandRestController extends BaseSpringRestController {

    /**
     * Handles create a Collateral.  if not key provided, calls create, otherwise calls save
     * @param		Collateral	collateral
     * @return		CompletableFuture<UUID> 
     */
	@PostMapping("/create")
    public CompletableFuture<UUID> create( @RequestBody(required=true) CreateCollateralCommand command ) {
		CompletableFuture<UUID> completableFuture = null;
		try {       
        	
			completableFuture = CollateralBusinessDelegate.getCollateralInstance().createCollateral( command );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage(), exc );        	
        }
		
		return completableFuture;
    }

    /**
     * Handles updating a Collateral.  if no key provided, calls create, otherwise calls save
     * @param		Collateral collateral
     * @return		CompletableFuture<Void>
     */
	@PutMapping("/update")
    public CompletableFuture<Void> update( @RequestBody(required=true) UpdateCollateralCommand command ) {
		CompletableFuture<Void> completableFuture = null;
		try {                        	        
			// -----------------------------------------------
			// delegate the UpdateCollateralCommand
			// -----------------------------------------------
			completableFuture = CollateralBusinessDelegate.getCollateralInstance().updateCollateral(command);;
	    }
	    catch( Throwable exc ) {
	    	LOGGER.log( Level.WARNING, "CollateralController:update() - successfully update Collateral - " + exc.getMessage());        	
	    }		
		
		return completableFuture;
	}
 
    /**
     * Handles deleting a Collateral entity
     * @param		command ${class.getDeleteCommandAlias()}
     * @return		CompletableFuture<Void>
     */
    @DeleteMapping("/delete")    
    public CompletableFuture<Void> delete( @RequestParam(required=true) UUID collateralId  ) {
    	CompletableFuture<Void> completableFuture = null;
		DeleteCollateralCommand command = new DeleteCollateralCommand( collateralId );

    	try {
        	CollateralBusinessDelegate delegate = CollateralBusinessDelegate.getCollateralInstance();

        	completableFuture = delegate.delete( command );
    		LOGGER.log( Level.WARNING, "Successfully deleted Collateral with key " + command.getCollateralId() );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage() );
        }
        
        return completableFuture;
	}        
	

    /**
     * save LoanAccount on Collateral
     * @param		command AssignLoanAccountToCollateralCommand
     */     
	@PutMapping("/assignLoanAccount")
	public void assignLoanAccount( @RequestBody AssignLoanAccountToCollateralCommand command ) {
		try {
			CollateralBusinessDelegate.getCollateralInstance().assignLoanAccount( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign LoanAccount", exc );
        }
	}

    /**
     * unassign LoanAccount on Collateral
     * @param		 command UnAssignLoanAccountFromCollateralCommand
     */     
	@PutMapping("/unAssignLoanAccount")
	public void unAssignLoanAccount( @RequestBody(required=true)  UnAssignLoanAccountFromCollateralCommand command ) {
		try {
			CollateralBusinessDelegate.getCollateralInstance().unAssignLoanAccount( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign LoanAccount", exc );
		}
	}
	


//************************************************************************    
// Attributes
//************************************************************************
    protected Collateral collateral = null;
    private static final Logger LOGGER = Logger.getLogger(CollateralCommandRestController.class.getName());
    
}
