/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.company.controller.command;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.concurrent.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.company.api.*;
import com.company.delegate.*;
import com.company.entity.*;
import com.company.exception.*;
import com.company.projector.*;

import com.company.controller.*;

/**
 * <h2>DisputeCommandRestController as REST API</h2>
 * <p>
 * Implements Spring Controller command CQRS processing for entity Dispute.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>07/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	DisputeBusinessDelegate
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateDisputeCommand</li>
 *      <li>UpdateDisputeCommand</li>
 *      <liDeleteDisputeCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 */

@CrossOrigin
@RestController
@RequestMapping("/DisputeCommand")
public class DisputeCommandRestController extends BaseSpringRestController {

    /**
     * Handles create a Dispute.  if not key provided, calls create, otherwise calls save
     * @param		Dispute	dispute
     * @return		CompletableFuture<UUID> 
     */
	@PostMapping("/create")
    public CompletableFuture<UUID> create( @RequestBody(required=true) CreateDisputeCommand command ) {
		CompletableFuture<UUID> completableFuture = null;
		try {       
        	
			completableFuture = DisputeBusinessDelegate.getDisputeInstance().createDispute( command );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage(), exc );        	
        }
		
		return completableFuture;
    }

    /**
     * Handles updating a Dispute.  if no key provided, calls create, otherwise calls save
     * @param		Dispute dispute
     * @return		CompletableFuture<Void>
     */
	@PutMapping("/update")
    public CompletableFuture<Void> update( @RequestBody(required=true) UpdateDisputeCommand command ) {
		CompletableFuture<Void> completableFuture = null;
		try {                        	        
			// -----------------------------------------------
			// delegate the UpdateDisputeCommand
			// -----------------------------------------------
			completableFuture = DisputeBusinessDelegate.getDisputeInstance().updateDispute(command);;
	    }
	    catch( Throwable exc ) {
	    	LOGGER.log( Level.WARNING, "DisputeController:update() - successfully update Dispute - " + exc.getMessage());        	
	    }		
		
		return completableFuture;
	}
 
    /**
     * Handles deleting a Dispute entity
     * @param		command ${class.getDeleteCommandAlias()}
     * @return		CompletableFuture<Void>
     */
    @DeleteMapping("/delete")    
    public CompletableFuture<Void> delete( @RequestParam(required=true) UUID disputeId  ) {
    	CompletableFuture<Void> completableFuture = null;
		DeleteDisputeCommand command = new DeleteDisputeCommand( disputeId );

    	try {
        	DisputeBusinessDelegate delegate = DisputeBusinessDelegate.getDisputeInstance();

        	completableFuture = delegate.delete( command );
    		LOGGER.log( Level.WARNING, "Successfully deleted Dispute with key " + command.getDisputeId() );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage() );
        }
        
        return completableFuture;
	}        
	

    /**
     * save Transaction on Dispute
     * @param		command AssignTransactionToDisputeCommand
     */     
	@PutMapping("/assignTransaction")
	public void assignTransaction( @RequestBody AssignTransactionToDisputeCommand command ) {
		try {
			DisputeBusinessDelegate.getDisputeInstance().assignTransaction( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Transaction", exc );
        }
	}

    /**
     * unassign Transaction on Dispute
     * @param		 command UnAssignTransactionFromDisputeCommand
     */     
	@PutMapping("/unAssignTransaction")
	public void unAssignTransaction( @RequestBody(required=true)  UnAssignTransactionFromDisputeCommand command ) {
		try {
			DisputeBusinessDelegate.getDisputeInstance().unAssignTransaction( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Transaction", exc );
		}
	}
	
    /**
     * save Customer on Dispute
     * @param		command AssignCustomerToDisputeCommand
     */     
	@PutMapping("/assignCustomer")
	public void assignCustomer( @RequestBody AssignCustomerToDisputeCommand command ) {
		try {
			DisputeBusinessDelegate.getDisputeInstance().assignCustomer( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Customer", exc );
        }
	}

    /**
     * unassign Customer on Dispute
     * @param		 command UnAssignCustomerFromDisputeCommand
     */     
	@PutMapping("/unAssignCustomer")
	public void unAssignCustomer( @RequestBody(required=true)  UnAssignCustomerFromDisputeCommand command ) {
		try {
			DisputeBusinessDelegate.getDisputeInstance().unAssignCustomer( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Customer", exc );
		}
	}
	
    /**
     * save Account on Dispute
     * @param		command AssignAccountToDisputeCommand
     */     
	@PutMapping("/assignAccount")
	public void assignAccount( @RequestBody AssignAccountToDisputeCommand command ) {
		try {
			DisputeBusinessDelegate.getDisputeInstance().assignAccount( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Account", exc );
        }
	}

    /**
     * unassign Account on Dispute
     * @param		 command UnAssignAccountFromDisputeCommand
     */     
	@PutMapping("/unAssignAccount")
	public void unAssignAccount( @RequestBody(required=true)  UnAssignAccountFromDisputeCommand command ) {
		try {
			DisputeBusinessDelegate.getDisputeInstance().unAssignAccount( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Account", exc );
		}
	}
	
    /**
     * save PaymentCard on Dispute
     * @param		command AssignPaymentCardToDisputeCommand
     */     
	@PutMapping("/assignPaymentCard")
	public void assignPaymentCard( @RequestBody AssignPaymentCardToDisputeCommand command ) {
		try {
			DisputeBusinessDelegate.getDisputeInstance().assignPaymentCard( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign PaymentCard", exc );
        }
	}

    /**
     * unassign PaymentCard on Dispute
     * @param		 command UnAssignPaymentCardFromDisputeCommand
     */     
	@PutMapping("/unAssignPaymentCard")
	public void unAssignPaymentCard( @RequestBody(required=true)  UnAssignPaymentCardFromDisputeCommand command ) {
		try {
			DisputeBusinessDelegate.getDisputeInstance().unAssignPaymentCard( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign PaymentCard", exc );
		}
	}
	


//************************************************************************    
// Attributes
//************************************************************************
    protected Dispute dispute = null;
    private static final Logger LOGGER = Logger.getLogger(DisputeCommandRestController.class.getName());
    
}
