/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.company.validator;

import org.springframework.util.Assert;

import com.company.api.*;

/**
 * <h2>AccountStatementValidation</h2>
 * <p>
 * The AccountStatement Validation  handles state validation of a AccountStatement include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateAccountStatementCommand</li>
 *      <li>UpdateAccountStatementCommand</li>
 *      <li>DeleteAccountStatementCommand</li>
 *set( false = false )
  *       <li>AssignAccountToAccountStatementCommand</li>
 *       <li>UnAssignAccountFromAccountStatementCommand</li>
   * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class AccountStatementValidator {
		
	/**
	 * default constructor
	 */
	protected AccountStatementValidator() {	
	}
	
	/**
	 * factory method
	 */
	static public AccountStatementValidator getInstance() {
		return new AccountStatementValidator();
	}
		
	/**
	 * handles creation validation for a AccountStatement
	 */
	public void validate( CreateAccountStatementCommand accountStatement )throws Exception {
		Assert.notNull( accountStatement, "CreateAccountStatementCommand should not be null" );
//		Assert.isNull( accountStatement.getAccountStatementId(), "CreateAccountStatementCommand identifier should be null" );
		Assert.notNull( accountStatement.getStatementNumber(), "Field CreateAccountStatementCommand.statementNumber should not be null" );
		Assert.notNull( accountStatement.getPeriodStart(), "Field CreateAccountStatementCommand.periodStart should not be null" );
		Assert.notNull( accountStatement.getPeriodEnd(), "Field CreateAccountStatementCommand.periodEnd should not be null" );
		Assert.notNull( accountStatement.getOpeningBalance(), "Field CreateAccountStatementCommand.openingBalance should not be null" );
		Assert.notNull( accountStatement.getClosingBalance(), "Field CreateAccountStatementCommand.closingBalance should not be null" );
	}

	/**
	 * handles update validation for a AccountStatement
	 */
	public void validate( UpdateAccountStatementCommand accountStatement ) throws Exception {
		Assert.notNull( accountStatement, "UpdateAccountStatementCommand should not be null" );
		Assert.notNull( accountStatement.getAccountStatementId(), "UpdateAccountStatementCommand identifier should not be null" );
		Assert.notNull( accountStatement.getStatementNumber(), "Field UpdateAccountStatementCommand.statementNumber should not be null" );
		Assert.notNull( accountStatement.getPeriodStart(), "Field UpdateAccountStatementCommand.periodStart should not be null" );
		Assert.notNull( accountStatement.getPeriodEnd(), "Field UpdateAccountStatementCommand.periodEnd should not be null" );
		Assert.notNull( accountStatement.getOpeningBalance(), "Field UpdateAccountStatementCommand.openingBalance should not be null" );
		Assert.notNull( accountStatement.getClosingBalance(), "Field UpdateAccountStatementCommand.closingBalance should not be null" );
    }

	/**
	 * handles delete validation for a AccountStatement
	 */
    public void validate( DeleteAccountStatementCommand accountStatement ) throws Exception {
		Assert.notNull( accountStatement, "{commandAlias} should not be null" );
		Assert.notNull( accountStatement.getAccountStatementId(), "DeleteAccountStatementCommand identifier should not be null" );
	}
	
	/**
	 * handles fetchOne validation for a AccountStatement
	 */
	public void validate( AccountStatementFetchOneSummary summary ) throws Exception {
		Assert.notNull( summary, "AccountStatementFetchOneSummary should not be null" );
		Assert.notNull( summary.getAccountStatementId(), "AccountStatementFetchOneSummary identifier should not be null" );
	}

	/**
	 * handles assign Account validation for a AccountStatement
	 * 
	 * @param	command AssignAccountToAccountStatementCommand
	 */	
	public void validate( AssignAccountToAccountStatementCommand command ) throws Exception {
		Assert.notNull( command, "AssignAccountToAccountStatementCommand should not be null" );
		Assert.notNull( command.getAccountStatementId(), "AssignAccountToAccountStatementCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignAccountToAccountStatementCommand assignment should not be null" );
	}

	/**
	 * handles unassign Account validation for a AccountStatement
	 * 
	 * @param	command UnAssignAccountFromAccountStatementCommand
	 */	
	public void validate( UnAssignAccountFromAccountStatementCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignAccountFromAccountStatementCommand should not be null" );
		Assert.notNull( command.getAccountStatementId(), "UnAssignAccountFromAccountStatementCommand identifier should not be null" );
	}


}
