/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.company.validator;

import org.springframework.util.Assert;

import com.company.api.*;

/**
 * <h2>AccountValidation</h2>
 * <p>
 * The Account Validation  handles state validation of a Account include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>07/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateAccountCommand</li>
 *      <li>UpdateAccountCommand</li>
 *      <li>DeleteAccountCommand</li>
 *set( false = false )
  *       <li>AssignBankToAccountCommand</li>
 *       <li>UnAssignBankFromAccountCommand</li>
  *       <li>AssignBranchToAccountCommand</li>
 *       <li>UnAssignBranchFromAccountCommand</li>
  *       <li>AssignProductToAccountCommand</li>
 *       <li>UnAssignProductFromAccountCommand</li>
   *       <li>AssignOwnersToAccountCommand</li>
 *       <li>RemoveOwnersFromAccountCommand</li>
 *   </ul>
 *
  *       <li>AssignTransactionsToAccountCommand</li>
 *       <li>RemoveTransactionsFromAccountCommand</li>
 *   </ul>
 *
  *       <li>AssignStatementsToAccountCommand</li>
 *       <li>RemoveStatementsFromAccountCommand</li>
 *   </ul>
 *
  *       <li>AssignStandingInstructionsToAccountCommand</li>
 *       <li>RemoveStandingInstructionsFromAccountCommand</li>
 *   </ul>
 *
  *       <li>AssignFeeChargesToAccountCommand</li>
 *       <li>RemoveFeeChargesFromAccountCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class AccountValidator {
		
	/**
	 * default constructor
	 */
	protected AccountValidator() {	
	}
	
	/**
	 * factory method
	 */
	static public AccountValidator getInstance() {
		return new AccountValidator();
	}
		
	/**
	 * handles creation validation for a Account
	 */
	public void validate( CreateAccountCommand account )throws Exception {
		Assert.notNull( account, "CreateAccountCommand should not be null" );
//		Assert.isNull( account.getAccountId(), "CreateAccountCommand identifier should be null" );
		Assert.notNull( account.getAccountNumber(), "Field CreateAccountCommand.accountNumber should not be null" );
		Assert.notNull( account.getIban(), "Field CreateAccountCommand.iban should not be null" );
		Assert.notNull( account.getAccountName(), "Field CreateAccountCommand.accountName should not be null" );
		Assert.notNull( account.getCurrency(), "Field CreateAccountCommand.currency should not be null" );
		Assert.notNull( account.getOpenedOn(), "Field CreateAccountCommand.openedOn should not be null" );
		Assert.notNull( account.getClosedOn(), "Field CreateAccountCommand.closedOn should not be null" );
	}

	/**
	 * handles update validation for a Account
	 */
	public void validate( UpdateAccountCommand account ) throws Exception {
		Assert.notNull( account, "UpdateAccountCommand should not be null" );
		Assert.notNull( account.getAccountId(), "UpdateAccountCommand identifier should not be null" );
		Assert.notNull( account.getAccountNumber(), "Field UpdateAccountCommand.accountNumber should not be null" );
		Assert.notNull( account.getIban(), "Field UpdateAccountCommand.iban should not be null" );
		Assert.notNull( account.getAccountName(), "Field UpdateAccountCommand.accountName should not be null" );
		Assert.notNull( account.getCurrency(), "Field UpdateAccountCommand.currency should not be null" );
		Assert.notNull( account.getOpenedOn(), "Field UpdateAccountCommand.openedOn should not be null" );
		Assert.notNull( account.getClosedOn(), "Field UpdateAccountCommand.closedOn should not be null" );
    }

	/**
	 * handles delete validation for a Account
	 */
    public void validate( DeleteAccountCommand account ) throws Exception {
		Assert.notNull( account, "{commandAlias} should not be null" );
		Assert.notNull( account.getAccountId(), "DeleteAccountCommand identifier should not be null" );
	}
	
	/**
	 * handles fetchOne validation for a Account
	 */
	public void validate( AccountFetchOneSummary summary ) throws Exception {
		Assert.notNull( summary, "AccountFetchOneSummary should not be null" );
		Assert.notNull( summary.getAccountId(), "AccountFetchOneSummary identifier should not be null" );
	}

	/**
	 * handles assign Bank validation for a Account
	 * 
	 * @param	command AssignBankToAccountCommand
	 */	
	public void validate( AssignBankToAccountCommand command ) throws Exception {
		Assert.notNull( command, "AssignBankToAccountCommand should not be null" );
		Assert.notNull( command.getAccountId(), "AssignBankToAccountCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignBankToAccountCommand assignment should not be null" );
	}

	/**
	 * handles unassign Bank validation for a Account
	 * 
	 * @param	command UnAssignBankFromAccountCommand
	 */	
	public void validate( UnAssignBankFromAccountCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignBankFromAccountCommand should not be null" );
		Assert.notNull( command.getAccountId(), "UnAssignBankFromAccountCommand identifier should not be null" );
	}
	/**
	 * handles assign Branch validation for a Account
	 * 
	 * @param	command AssignBranchToAccountCommand
	 */	
	public void validate( AssignBranchToAccountCommand command ) throws Exception {
		Assert.notNull( command, "AssignBranchToAccountCommand should not be null" );
		Assert.notNull( command.getAccountId(), "AssignBranchToAccountCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignBranchToAccountCommand assignment should not be null" );
	}

	/**
	 * handles unassign Branch validation for a Account
	 * 
	 * @param	command UnAssignBranchFromAccountCommand
	 */	
	public void validate( UnAssignBranchFromAccountCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignBranchFromAccountCommand should not be null" );
		Assert.notNull( command.getAccountId(), "UnAssignBranchFromAccountCommand identifier should not be null" );
	}
	/**
	 * handles assign Product validation for a Account
	 * 
	 * @param	command AssignProductToAccountCommand
	 */	
	public void validate( AssignProductToAccountCommand command ) throws Exception {
		Assert.notNull( command, "AssignProductToAccountCommand should not be null" );
		Assert.notNull( command.getAccountId(), "AssignProductToAccountCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignProductToAccountCommand assignment should not be null" );
	}

	/**
	 * handles unassign Product validation for a Account
	 * 
	 * @param	command UnAssignProductFromAccountCommand
	 */	
	public void validate( UnAssignProductFromAccountCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignProductFromAccountCommand should not be null" );
		Assert.notNull( command.getAccountId(), "UnAssignProductFromAccountCommand identifier should not be null" );
	}

	/**
	 * handles add to Owners validation for a Account
	 * 
	 * @param	command AssignOwnersToAccountCommand
	 */	
	public void validate( AssignOwnersToAccountCommand command ) throws Exception {
		Assert.notNull( command, "AssignOwnersToAccountCommand should not be null" );
		Assert.notNull( command.getAccountId(), "AssignOwnersToAccountCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignOwnersToAccountCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from Owners validation for a Account
	 * 
	 * @param	command RemoveOwnersFromAccountCommand
	 */	
	public void validate( RemoveOwnersFromAccountCommand command ) throws Exception {
		Assert.notNull( command, "RemoveOwnersFromAccountCommand should not be null" );
		Assert.notNull( command.getAccountId(), "RemoveOwnersFromAccountCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveOwnersFromAccountCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getCustomerId(), "RemoveOwnersFromAccountCommand removeFrom attribubte identifier should not be null" );
	}
	
	/**
	 * handles add to Transactions validation for a Account
	 * 
	 * @param	command AssignTransactionsToAccountCommand
	 */	
	public void validate( AssignTransactionsToAccountCommand command ) throws Exception {
		Assert.notNull( command, "AssignTransactionsToAccountCommand should not be null" );
		Assert.notNull( command.getAccountId(), "AssignTransactionsToAccountCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignTransactionsToAccountCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from Transactions validation for a Account
	 * 
	 * @param	command RemoveTransactionsFromAccountCommand
	 */	
	public void validate( RemoveTransactionsFromAccountCommand command ) throws Exception {
		Assert.notNull( command, "RemoveTransactionsFromAccountCommand should not be null" );
		Assert.notNull( command.getAccountId(), "RemoveTransactionsFromAccountCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveTransactionsFromAccountCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getTransactionId(), "RemoveTransactionsFromAccountCommand removeFrom attribubte identifier should not be null" );
	}
	
	/**
	 * handles add to Statements validation for a Account
	 * 
	 * @param	command AssignStatementsToAccountCommand
	 */	
	public void validate( AssignStatementsToAccountCommand command ) throws Exception {
		Assert.notNull( command, "AssignStatementsToAccountCommand should not be null" );
		Assert.notNull( command.getAccountId(), "AssignStatementsToAccountCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignStatementsToAccountCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from Statements validation for a Account
	 * 
	 * @param	command RemoveStatementsFromAccountCommand
	 */	
	public void validate( RemoveStatementsFromAccountCommand command ) throws Exception {
		Assert.notNull( command, "RemoveStatementsFromAccountCommand should not be null" );
		Assert.notNull( command.getAccountId(), "RemoveStatementsFromAccountCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveStatementsFromAccountCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getAccountStatementId(), "RemoveStatementsFromAccountCommand removeFrom attribubte identifier should not be null" );
	}
	
	/**
	 * handles add to StandingInstructions validation for a Account
	 * 
	 * @param	command AssignStandingInstructionsToAccountCommand
	 */	
	public void validate( AssignStandingInstructionsToAccountCommand command ) throws Exception {
		Assert.notNull( command, "AssignStandingInstructionsToAccountCommand should not be null" );
		Assert.notNull( command.getAccountId(), "AssignStandingInstructionsToAccountCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignStandingInstructionsToAccountCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from StandingInstructions validation for a Account
	 * 
	 * @param	command RemoveStandingInstructionsFromAccountCommand
	 */	
	public void validate( RemoveStandingInstructionsFromAccountCommand command ) throws Exception {
		Assert.notNull( command, "RemoveStandingInstructionsFromAccountCommand should not be null" );
		Assert.notNull( command.getAccountId(), "RemoveStandingInstructionsFromAccountCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveStandingInstructionsFromAccountCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getStandingInstructionId(), "RemoveStandingInstructionsFromAccountCommand removeFrom attribubte identifier should not be null" );
	}
	
	/**
	 * handles add to FeeCharges validation for a Account
	 * 
	 * @param	command AssignFeeChargesToAccountCommand
	 */	
	public void validate( AssignFeeChargesToAccountCommand command ) throws Exception {
		Assert.notNull( command, "AssignFeeChargesToAccountCommand should not be null" );
		Assert.notNull( command.getAccountId(), "AssignFeeChargesToAccountCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignFeeChargesToAccountCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from FeeCharges validation for a Account
	 * 
	 * @param	command RemoveFeeChargesFromAccountCommand
	 */	
	public void validate( RemoveFeeChargesFromAccountCommand command ) throws Exception {
		Assert.notNull( command, "RemoveFeeChargesFromAccountCommand should not be null" );
		Assert.notNull( command.getAccountId(), "RemoveFeeChargesFromAccountCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveFeeChargesFromAccountCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getFeeChargeId(), "RemoveFeeChargesFromAccountCommand removeFrom attribubte identifier should not be null" );
	}
	

}
