/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.company.validator;

import org.springframework.util.Assert;

import com.company.api.*;

/**
 * <h2>ATMValidation</h2>
 * <p>
 * The ATM Validation  handles state validation of a ATM include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateATMCommand</li>
 *      <li>UpdateATMCommand</li>
 *      <li>DeleteATMCommand</li>
 *set( false = false )
  *       <li>AssignBranchToATMCommand</li>
 *       <li>UnAssignBranchFromATMCommand</li>
   * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class ATMValidator {
		
	/**
	 * default constructor
	 */
	protected ATMValidator() {	
	}
	
	/**
	 * factory method
	 */
	static public ATMValidator getInstance() {
		return new ATMValidator();
	}
		
	/**
	 * handles creation validation for a ATM
	 */
	public void validate( CreateATMCommand aTM )throws Exception {
		Assert.notNull( aTM, "CreateATMCommand should not be null" );
//		Assert.isNull( aTM.getATMId(), "CreateATMCommand identifier should be null" );
		Assert.notNull( aTM.getTerminalId(), "Field CreateATMCommand.terminalId should not be null" );
		Assert.notNull( aTM.getLocation(), "Field CreateATMCommand.location should not be null" );
	}

	/**
	 * handles update validation for a ATM
	 */
	public void validate( UpdateATMCommand aTM ) throws Exception {
		Assert.notNull( aTM, "UpdateATMCommand should not be null" );
		Assert.notNull( aTM.getATMId(), "UpdateATMCommand identifier should not be null" );
		Assert.notNull( aTM.getTerminalId(), "Field UpdateATMCommand.terminalId should not be null" );
		Assert.notNull( aTM.getLocation(), "Field UpdateATMCommand.location should not be null" );
    }

	/**
	 * handles delete validation for a ATM
	 */
    public void validate( DeleteATMCommand aTM ) throws Exception {
		Assert.notNull( aTM, "{commandAlias} should not be null" );
		Assert.notNull( aTM.getATMId(), "DeleteATMCommand identifier should not be null" );
	}
	
	/**
	 * handles fetchOne validation for a ATM
	 */
	public void validate( ATMFetchOneSummary summary ) throws Exception {
		Assert.notNull( summary, "ATMFetchOneSummary should not be null" );
		Assert.notNull( summary.getATMId(), "ATMFetchOneSummary identifier should not be null" );
	}

	/**
	 * handles assign Branch validation for a ATM
	 * 
	 * @param	command AssignBranchToATMCommand
	 */	
	public void validate( AssignBranchToATMCommand command ) throws Exception {
		Assert.notNull( command, "AssignBranchToATMCommand should not be null" );
		Assert.notNull( command.getATMId(), "AssignBranchToATMCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignBranchToATMCommand assignment should not be null" );
	}

	/**
	 * handles unassign Branch validation for a ATM
	 * 
	 * @param	command UnAssignBranchFromATMCommand
	 */	
	public void validate( UnAssignBranchFromATMCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignBranchFromATMCommand should not be null" );
		Assert.notNull( command.getATMId(), "UnAssignBranchFromATMCommand identifier should not be null" );
	}


}
