/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.company.validator;

import org.springframework.util.Assert;

import com.company.api.*;

/**
 * <h2>BankingProductValidation</h2>
 * <p>
 * The BankingProduct Validation  handles state validation of a BankingProduct include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>07/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateBankingProductCommand</li>
 *      <li>UpdateBankingProductCommand</li>
 *      <li>DeleteBankingProductCommand</li>
 *set( false = false )
  *       <li>AssignBankToBankingProductCommand</li>
 *       <li>UnAssignBankFromBankingProductCommand</li>
   *       <li>AssignAccountsToBankingProductCommand</li>
 *       <li>RemoveAccountsFromBankingProductCommand</li>
 *   </ul>
 *
  *       <li>AssignLoanAccountsToBankingProductCommand</li>
 *       <li>RemoveLoanAccountsFromBankingProductCommand</li>
 *   </ul>
 *
  *       <li>AssignPaymentCardsToBankingProductCommand</li>
 *       <li>RemovePaymentCardsFromBankingProductCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class BankingProductValidator {
		
	/**
	 * default constructor
	 */
	protected BankingProductValidator() {	
	}
	
	/**
	 * factory method
	 */
	static public BankingProductValidator getInstance() {
		return new BankingProductValidator();
	}
		
	/**
	 * handles creation validation for a BankingProduct
	 */
	public void validate( CreateBankingProductCommand bankingProduct )throws Exception {
		Assert.notNull( bankingProduct, "CreateBankingProductCommand should not be null" );
//		Assert.isNull( bankingProduct.getBankingProductId(), "CreateBankingProductCommand identifier should be null" );
		Assert.notNull( bankingProduct.getProductCode(), "Field CreateBankingProductCommand.productCode should not be null" );
		Assert.notNull( bankingProduct.getName(), "Field CreateBankingProductCommand.name should not be null" );
		Assert.notNull( bankingProduct.getDescription(), "Field CreateBankingProductCommand.description should not be null" );
	}

	/**
	 * handles update validation for a BankingProduct
	 */
	public void validate( UpdateBankingProductCommand bankingProduct ) throws Exception {
		Assert.notNull( bankingProduct, "UpdateBankingProductCommand should not be null" );
		Assert.notNull( bankingProduct.getBankingProductId(), "UpdateBankingProductCommand identifier should not be null" );
		Assert.notNull( bankingProduct.getProductCode(), "Field UpdateBankingProductCommand.productCode should not be null" );
		Assert.notNull( bankingProduct.getName(), "Field UpdateBankingProductCommand.name should not be null" );
		Assert.notNull( bankingProduct.getDescription(), "Field UpdateBankingProductCommand.description should not be null" );
    }

	/**
	 * handles delete validation for a BankingProduct
	 */
    public void validate( DeleteBankingProductCommand bankingProduct ) throws Exception {
		Assert.notNull( bankingProduct, "{commandAlias} should not be null" );
		Assert.notNull( bankingProduct.getBankingProductId(), "DeleteBankingProductCommand identifier should not be null" );
	}
	
	/**
	 * handles fetchOne validation for a BankingProduct
	 */
	public void validate( BankingProductFetchOneSummary summary ) throws Exception {
		Assert.notNull( summary, "BankingProductFetchOneSummary should not be null" );
		Assert.notNull( summary.getBankingProductId(), "BankingProductFetchOneSummary identifier should not be null" );
	}

	/**
	 * handles assign Bank validation for a BankingProduct
	 * 
	 * @param	command AssignBankToBankingProductCommand
	 */	
	public void validate( AssignBankToBankingProductCommand command ) throws Exception {
		Assert.notNull( command, "AssignBankToBankingProductCommand should not be null" );
		Assert.notNull( command.getBankingProductId(), "AssignBankToBankingProductCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignBankToBankingProductCommand assignment should not be null" );
	}

	/**
	 * handles unassign Bank validation for a BankingProduct
	 * 
	 * @param	command UnAssignBankFromBankingProductCommand
	 */	
	public void validate( UnAssignBankFromBankingProductCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignBankFromBankingProductCommand should not be null" );
		Assert.notNull( command.getBankingProductId(), "UnAssignBankFromBankingProductCommand identifier should not be null" );
	}

	/**
	 * handles add to Accounts validation for a BankingProduct
	 * 
	 * @param	command AssignAccountsToBankingProductCommand
	 */	
	public void validate( AssignAccountsToBankingProductCommand command ) throws Exception {
		Assert.notNull( command, "AssignAccountsToBankingProductCommand should not be null" );
		Assert.notNull( command.getBankingProductId(), "AssignAccountsToBankingProductCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignAccountsToBankingProductCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from Accounts validation for a BankingProduct
	 * 
	 * @param	command RemoveAccountsFromBankingProductCommand
	 */	
	public void validate( RemoveAccountsFromBankingProductCommand command ) throws Exception {
		Assert.notNull( command, "RemoveAccountsFromBankingProductCommand should not be null" );
		Assert.notNull( command.getBankingProductId(), "RemoveAccountsFromBankingProductCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveAccountsFromBankingProductCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getAccountId(), "RemoveAccountsFromBankingProductCommand removeFrom attribubte identifier should not be null" );
	}
	
	/**
	 * handles add to LoanAccounts validation for a BankingProduct
	 * 
	 * @param	command AssignLoanAccountsToBankingProductCommand
	 */	
	public void validate( AssignLoanAccountsToBankingProductCommand command ) throws Exception {
		Assert.notNull( command, "AssignLoanAccountsToBankingProductCommand should not be null" );
		Assert.notNull( command.getBankingProductId(), "AssignLoanAccountsToBankingProductCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignLoanAccountsToBankingProductCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from LoanAccounts validation for a BankingProduct
	 * 
	 * @param	command RemoveLoanAccountsFromBankingProductCommand
	 */	
	public void validate( RemoveLoanAccountsFromBankingProductCommand command ) throws Exception {
		Assert.notNull( command, "RemoveLoanAccountsFromBankingProductCommand should not be null" );
		Assert.notNull( command.getBankingProductId(), "RemoveLoanAccountsFromBankingProductCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveLoanAccountsFromBankingProductCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getLoanAccountId(), "RemoveLoanAccountsFromBankingProductCommand removeFrom attribubte identifier should not be null" );
	}
	
	/**
	 * handles add to PaymentCards validation for a BankingProduct
	 * 
	 * @param	command AssignPaymentCardsToBankingProductCommand
	 */	
	public void validate( AssignPaymentCardsToBankingProductCommand command ) throws Exception {
		Assert.notNull( command, "AssignPaymentCardsToBankingProductCommand should not be null" );
		Assert.notNull( command.getBankingProductId(), "AssignPaymentCardsToBankingProductCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignPaymentCardsToBankingProductCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from PaymentCards validation for a BankingProduct
	 * 
	 * @param	command RemovePaymentCardsFromBankingProductCommand
	 */	
	public void validate( RemovePaymentCardsFromBankingProductCommand command ) throws Exception {
		Assert.notNull( command, "RemovePaymentCardsFromBankingProductCommand should not be null" );
		Assert.notNull( command.getBankingProductId(), "RemovePaymentCardsFromBankingProductCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemovePaymentCardsFromBankingProductCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getPaymentCardId(), "RemovePaymentCardsFromBankingProductCommand removeFrom attribubte identifier should not be null" );
	}
	

}
