/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.company.validator;

import org.springframework.util.Assert;

import com.company.api.*;

/**
 * <h2>BankValidation</h2>
 * <p>
 * The Bank Validation  handles state validation of a Bank include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>07/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateBankCommand</li>
 *      <li>UpdateBankCommand</li>
 *      <li>DeleteBankCommand</li>
 *set( false = false )
   *       <li>AssignBranchesToBankCommand</li>
 *       <li>RemoveBranchesFromBankCommand</li>
 *   </ul>
 *
  *       <li>AssignProductsToBankCommand</li>
 *       <li>RemoveProductsFromBankCommand</li>
 *   </ul>
 *
  *       <li>AssignCustomersToBankCommand</li>
 *       <li>RemoveCustomersFromBankCommand</li>
 *   </ul>
 *
  *       <li>AssignAccountsToBankCommand</li>
 *       <li>RemoveAccountsFromBankCommand</li>
 *   </ul>
 *
  *       <li>AssignPaymentCardsToBankCommand</li>
 *       <li>RemovePaymentCardsFromBankCommand</li>
 *   </ul>
 *
  *       <li>AssignLoanAccountsToBankCommand</li>
 *       <li>RemoveLoanAccountsFromBankCommand</li>
 *   </ul>
 *
  *       <li>AssignExchangeRatesToBankCommand</li>
 *       <li>RemoveExchangeRatesFromBankCommand</li>
 *   </ul>
 *
  *       <li>AssignConsentsToBankCommand</li>
 *       <li>RemoveConsentsFromBankCommand</li>
 *   </ul>
 *
  *       <li>AssignThirdPartyProvidersToBankCommand</li>
 *       <li>RemoveThirdPartyProvidersFromBankCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class BankValidator {
		
	/**
	 * default constructor
	 */
	protected BankValidator() {	
	}
	
	/**
	 * factory method
	 */
	static public BankValidator getInstance() {
		return new BankValidator();
	}
		
	/**
	 * handles creation validation for a Bank
	 */
	public void validate( CreateBankCommand bank )throws Exception {
		Assert.notNull( bank, "CreateBankCommand should not be null" );
//		Assert.isNull( bank.getBankId(), "CreateBankCommand identifier should be null" );
		Assert.notNull( bank.getName(), "Field CreateBankCommand.name should not be null" );
		Assert.notNull( bank.getLegalName(), "Field CreateBankCommand.legalName should not be null" );
		Assert.notNull( bank.getSwiftBic(), "Field CreateBankCommand.swiftBic should not be null" );
		Assert.notNull( bank.getHeadquartersCountry(), "Field CreateBankCommand.headquartersCountry should not be null" );
		Assert.notNull( bank.getWebsite(), "Field CreateBankCommand.website should not be null" );
	}

	/**
	 * handles update validation for a Bank
	 */
	public void validate( UpdateBankCommand bank ) throws Exception {
		Assert.notNull( bank, "UpdateBankCommand should not be null" );
		Assert.notNull( bank.getBankId(), "UpdateBankCommand identifier should not be null" );
		Assert.notNull( bank.getName(), "Field UpdateBankCommand.name should not be null" );
		Assert.notNull( bank.getLegalName(), "Field UpdateBankCommand.legalName should not be null" );
		Assert.notNull( bank.getSwiftBic(), "Field UpdateBankCommand.swiftBic should not be null" );
		Assert.notNull( bank.getHeadquartersCountry(), "Field UpdateBankCommand.headquartersCountry should not be null" );
		Assert.notNull( bank.getWebsite(), "Field UpdateBankCommand.website should not be null" );
    }

	/**
	 * handles delete validation for a Bank
	 */
    public void validate( DeleteBankCommand bank ) throws Exception {
		Assert.notNull( bank, "{commandAlias} should not be null" );
		Assert.notNull( bank.getBankId(), "DeleteBankCommand identifier should not be null" );
	}
	
	/**
	 * handles fetchOne validation for a Bank
	 */
	public void validate( BankFetchOneSummary summary ) throws Exception {
		Assert.notNull( summary, "BankFetchOneSummary should not be null" );
		Assert.notNull( summary.getBankId(), "BankFetchOneSummary identifier should not be null" );
	}


	/**
	 * handles add to Branches validation for a Bank
	 * 
	 * @param	command AssignBranchesToBankCommand
	 */	
	public void validate( AssignBranchesToBankCommand command ) throws Exception {
		Assert.notNull( command, "AssignBranchesToBankCommand should not be null" );
		Assert.notNull( command.getBankId(), "AssignBranchesToBankCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignBranchesToBankCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from Branches validation for a Bank
	 * 
	 * @param	command RemoveBranchesFromBankCommand
	 */	
	public void validate( RemoveBranchesFromBankCommand command ) throws Exception {
		Assert.notNull( command, "RemoveBranchesFromBankCommand should not be null" );
		Assert.notNull( command.getBankId(), "RemoveBranchesFromBankCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveBranchesFromBankCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getBranchId(), "RemoveBranchesFromBankCommand removeFrom attribubte identifier should not be null" );
	}
	
	/**
	 * handles add to Products validation for a Bank
	 * 
	 * @param	command AssignProductsToBankCommand
	 */	
	public void validate( AssignProductsToBankCommand command ) throws Exception {
		Assert.notNull( command, "AssignProductsToBankCommand should not be null" );
		Assert.notNull( command.getBankId(), "AssignProductsToBankCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignProductsToBankCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from Products validation for a Bank
	 * 
	 * @param	command RemoveProductsFromBankCommand
	 */	
	public void validate( RemoveProductsFromBankCommand command ) throws Exception {
		Assert.notNull( command, "RemoveProductsFromBankCommand should not be null" );
		Assert.notNull( command.getBankId(), "RemoveProductsFromBankCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveProductsFromBankCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getBankingProductId(), "RemoveProductsFromBankCommand removeFrom attribubte identifier should not be null" );
	}
	
	/**
	 * handles add to Customers validation for a Bank
	 * 
	 * @param	command AssignCustomersToBankCommand
	 */	
	public void validate( AssignCustomersToBankCommand command ) throws Exception {
		Assert.notNull( command, "AssignCustomersToBankCommand should not be null" );
		Assert.notNull( command.getBankId(), "AssignCustomersToBankCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignCustomersToBankCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from Customers validation for a Bank
	 * 
	 * @param	command RemoveCustomersFromBankCommand
	 */	
	public void validate( RemoveCustomersFromBankCommand command ) throws Exception {
		Assert.notNull( command, "RemoveCustomersFromBankCommand should not be null" );
		Assert.notNull( command.getBankId(), "RemoveCustomersFromBankCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveCustomersFromBankCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getCustomerId(), "RemoveCustomersFromBankCommand removeFrom attribubte identifier should not be null" );
	}
	
	/**
	 * handles add to Accounts validation for a Bank
	 * 
	 * @param	command AssignAccountsToBankCommand
	 */	
	public void validate( AssignAccountsToBankCommand command ) throws Exception {
		Assert.notNull( command, "AssignAccountsToBankCommand should not be null" );
		Assert.notNull( command.getBankId(), "AssignAccountsToBankCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignAccountsToBankCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from Accounts validation for a Bank
	 * 
	 * @param	command RemoveAccountsFromBankCommand
	 */	
	public void validate( RemoveAccountsFromBankCommand command ) throws Exception {
		Assert.notNull( command, "RemoveAccountsFromBankCommand should not be null" );
		Assert.notNull( command.getBankId(), "RemoveAccountsFromBankCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveAccountsFromBankCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getAccountId(), "RemoveAccountsFromBankCommand removeFrom attribubte identifier should not be null" );
	}
	
	/**
	 * handles add to PaymentCards validation for a Bank
	 * 
	 * @param	command AssignPaymentCardsToBankCommand
	 */	
	public void validate( AssignPaymentCardsToBankCommand command ) throws Exception {
		Assert.notNull( command, "AssignPaymentCardsToBankCommand should not be null" );
		Assert.notNull( command.getBankId(), "AssignPaymentCardsToBankCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignPaymentCardsToBankCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from PaymentCards validation for a Bank
	 * 
	 * @param	command RemovePaymentCardsFromBankCommand
	 */	
	public void validate( RemovePaymentCardsFromBankCommand command ) throws Exception {
		Assert.notNull( command, "RemovePaymentCardsFromBankCommand should not be null" );
		Assert.notNull( command.getBankId(), "RemovePaymentCardsFromBankCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemovePaymentCardsFromBankCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getPaymentCardId(), "RemovePaymentCardsFromBankCommand removeFrom attribubte identifier should not be null" );
	}
	
	/**
	 * handles add to LoanAccounts validation for a Bank
	 * 
	 * @param	command AssignLoanAccountsToBankCommand
	 */	
	public void validate( AssignLoanAccountsToBankCommand command ) throws Exception {
		Assert.notNull( command, "AssignLoanAccountsToBankCommand should not be null" );
		Assert.notNull( command.getBankId(), "AssignLoanAccountsToBankCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignLoanAccountsToBankCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from LoanAccounts validation for a Bank
	 * 
	 * @param	command RemoveLoanAccountsFromBankCommand
	 */	
	public void validate( RemoveLoanAccountsFromBankCommand command ) throws Exception {
		Assert.notNull( command, "RemoveLoanAccountsFromBankCommand should not be null" );
		Assert.notNull( command.getBankId(), "RemoveLoanAccountsFromBankCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveLoanAccountsFromBankCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getLoanAccountId(), "RemoveLoanAccountsFromBankCommand removeFrom attribubte identifier should not be null" );
	}
	
	/**
	 * handles add to ExchangeRates validation for a Bank
	 * 
	 * @param	command AssignExchangeRatesToBankCommand
	 */	
	public void validate( AssignExchangeRatesToBankCommand command ) throws Exception {
		Assert.notNull( command, "AssignExchangeRatesToBankCommand should not be null" );
		Assert.notNull( command.getBankId(), "AssignExchangeRatesToBankCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignExchangeRatesToBankCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from ExchangeRates validation for a Bank
	 * 
	 * @param	command RemoveExchangeRatesFromBankCommand
	 */	
	public void validate( RemoveExchangeRatesFromBankCommand command ) throws Exception {
		Assert.notNull( command, "RemoveExchangeRatesFromBankCommand should not be null" );
		Assert.notNull( command.getBankId(), "RemoveExchangeRatesFromBankCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveExchangeRatesFromBankCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getExchangeRateId(), "RemoveExchangeRatesFromBankCommand removeFrom attribubte identifier should not be null" );
	}
	
	/**
	 * handles add to Consents validation for a Bank
	 * 
	 * @param	command AssignConsentsToBankCommand
	 */	
	public void validate( AssignConsentsToBankCommand command ) throws Exception {
		Assert.notNull( command, "AssignConsentsToBankCommand should not be null" );
		Assert.notNull( command.getBankId(), "AssignConsentsToBankCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignConsentsToBankCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from Consents validation for a Bank
	 * 
	 * @param	command RemoveConsentsFromBankCommand
	 */	
	public void validate( RemoveConsentsFromBankCommand command ) throws Exception {
		Assert.notNull( command, "RemoveConsentsFromBankCommand should not be null" );
		Assert.notNull( command.getBankId(), "RemoveConsentsFromBankCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveConsentsFromBankCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getConsentId(), "RemoveConsentsFromBankCommand removeFrom attribubte identifier should not be null" );
	}
	
	/**
	 * handles add to ThirdPartyProviders validation for a Bank
	 * 
	 * @param	command AssignThirdPartyProvidersToBankCommand
	 */	
	public void validate( AssignThirdPartyProvidersToBankCommand command ) throws Exception {
		Assert.notNull( command, "AssignThirdPartyProvidersToBankCommand should not be null" );
		Assert.notNull( command.getBankId(), "AssignThirdPartyProvidersToBankCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignThirdPartyProvidersToBankCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from ThirdPartyProviders validation for a Bank
	 * 
	 * @param	command RemoveThirdPartyProvidersFromBankCommand
	 */	
	public void validate( RemoveThirdPartyProvidersFromBankCommand command ) throws Exception {
		Assert.notNull( command, "RemoveThirdPartyProvidersFromBankCommand should not be null" );
		Assert.notNull( command.getBankId(), "RemoveThirdPartyProvidersFromBankCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveThirdPartyProvidersFromBankCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getThirdPartyProviderId(), "RemoveThirdPartyProvidersFromBankCommand removeFrom attribubte identifier should not be null" );
	}
	

}
