/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.company.validator;

import org.springframework.util.Assert;

import com.company.api.*;

/**
 * <h2>BranchValidation</h2>
 * <p>
 * The Branch Validation  handles state validation of a Branch include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateBranchCommand</li>
 *      <li>UpdateBranchCommand</li>
 *      <li>DeleteBranchCommand</li>
 *set( false = false )
  *       <li>AssignBankToBranchCommand</li>
 *       <li>UnAssignBankFromBranchCommand</li>
   *       <li>AssignAccountsToBranchCommand</li>
 *       <li>RemoveAccountsFromBranchCommand</li>
 *   </ul>
 *
  *       <li>AssignLoanAccountsToBranchCommand</li>
 *       <li>RemoveLoanAccountsFromBranchCommand</li>
 *   </ul>
 *
  *       <li>AssignAtmsToBranchCommand</li>
 *       <li>RemoveAtmsFromBranchCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class BranchValidator {
		
	/**
	 * default constructor
	 */
	protected BranchValidator() {	
	}
	
	/**
	 * factory method
	 */
	static public BranchValidator getInstance() {
		return new BranchValidator();
	}
		
	/**
	 * handles creation validation for a Branch
	 */
	public void validate( CreateBranchCommand branch )throws Exception {
		Assert.notNull( branch, "CreateBranchCommand should not be null" );
//		Assert.isNull( branch.getBranchId(), "CreateBranchCommand identifier should be null" );
		Assert.notNull( branch.getName(), "Field CreateBranchCommand.name should not be null" );
		Assert.notNull( branch.getBranchCode(), "Field CreateBranchCommand.branchCode should not be null" );
		Assert.notNull( branch.getAddress(), "Field CreateBranchCommand.address should not be null" );
		Assert.notNull( branch.getPhone(), "Field CreateBranchCommand.phone should not be null" );
		Assert.notNull( branch.getOpeningHours(), "Field CreateBranchCommand.openingHours should not be null" );
	}

	/**
	 * handles update validation for a Branch
	 */
	public void validate( UpdateBranchCommand branch ) throws Exception {
		Assert.notNull( branch, "UpdateBranchCommand should not be null" );
		Assert.notNull( branch.getBranchId(), "UpdateBranchCommand identifier should not be null" );
		Assert.notNull( branch.getName(), "Field UpdateBranchCommand.name should not be null" );
		Assert.notNull( branch.getBranchCode(), "Field UpdateBranchCommand.branchCode should not be null" );
		Assert.notNull( branch.getAddress(), "Field UpdateBranchCommand.address should not be null" );
		Assert.notNull( branch.getPhone(), "Field UpdateBranchCommand.phone should not be null" );
		Assert.notNull( branch.getOpeningHours(), "Field UpdateBranchCommand.openingHours should not be null" );
    }

	/**
	 * handles delete validation for a Branch
	 */
    public void validate( DeleteBranchCommand branch ) throws Exception {
		Assert.notNull( branch, "{commandAlias} should not be null" );
		Assert.notNull( branch.getBranchId(), "DeleteBranchCommand identifier should not be null" );
	}
	
	/**
	 * handles fetchOne validation for a Branch
	 */
	public void validate( BranchFetchOneSummary summary ) throws Exception {
		Assert.notNull( summary, "BranchFetchOneSummary should not be null" );
		Assert.notNull( summary.getBranchId(), "BranchFetchOneSummary identifier should not be null" );
	}

	/**
	 * handles assign Bank validation for a Branch
	 * 
	 * @param	command AssignBankToBranchCommand
	 */	
	public void validate( AssignBankToBranchCommand command ) throws Exception {
		Assert.notNull( command, "AssignBankToBranchCommand should not be null" );
		Assert.notNull( command.getBranchId(), "AssignBankToBranchCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignBankToBranchCommand assignment should not be null" );
	}

	/**
	 * handles unassign Bank validation for a Branch
	 * 
	 * @param	command UnAssignBankFromBranchCommand
	 */	
	public void validate( UnAssignBankFromBranchCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignBankFromBranchCommand should not be null" );
		Assert.notNull( command.getBranchId(), "UnAssignBankFromBranchCommand identifier should not be null" );
	}

	/**
	 * handles add to Accounts validation for a Branch
	 * 
	 * @param	command AssignAccountsToBranchCommand
	 */	
	public void validate( AssignAccountsToBranchCommand command ) throws Exception {
		Assert.notNull( command, "AssignAccountsToBranchCommand should not be null" );
		Assert.notNull( command.getBranchId(), "AssignAccountsToBranchCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignAccountsToBranchCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from Accounts validation for a Branch
	 * 
	 * @param	command RemoveAccountsFromBranchCommand
	 */	
	public void validate( RemoveAccountsFromBranchCommand command ) throws Exception {
		Assert.notNull( command, "RemoveAccountsFromBranchCommand should not be null" );
		Assert.notNull( command.getBranchId(), "RemoveAccountsFromBranchCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveAccountsFromBranchCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getAccountId(), "RemoveAccountsFromBranchCommand removeFrom attribubte identifier should not be null" );
	}
	
	/**
	 * handles add to LoanAccounts validation for a Branch
	 * 
	 * @param	command AssignLoanAccountsToBranchCommand
	 */	
	public void validate( AssignLoanAccountsToBranchCommand command ) throws Exception {
		Assert.notNull( command, "AssignLoanAccountsToBranchCommand should not be null" );
		Assert.notNull( command.getBranchId(), "AssignLoanAccountsToBranchCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignLoanAccountsToBranchCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from LoanAccounts validation for a Branch
	 * 
	 * @param	command RemoveLoanAccountsFromBranchCommand
	 */	
	public void validate( RemoveLoanAccountsFromBranchCommand command ) throws Exception {
		Assert.notNull( command, "RemoveLoanAccountsFromBranchCommand should not be null" );
		Assert.notNull( command.getBranchId(), "RemoveLoanAccountsFromBranchCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveLoanAccountsFromBranchCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getLoanAccountId(), "RemoveLoanAccountsFromBranchCommand removeFrom attribubte identifier should not be null" );
	}
	
	/**
	 * handles add to Atms validation for a Branch
	 * 
	 * @param	command AssignAtmsToBranchCommand
	 */	
	public void validate( AssignAtmsToBranchCommand command ) throws Exception {
		Assert.notNull( command, "AssignAtmsToBranchCommand should not be null" );
		Assert.notNull( command.getBranchId(), "AssignAtmsToBranchCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignAtmsToBranchCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from Atms validation for a Branch
	 * 
	 * @param	command RemoveAtmsFromBranchCommand
	 */	
	public void validate( RemoveAtmsFromBranchCommand command ) throws Exception {
		Assert.notNull( command, "RemoveAtmsFromBranchCommand should not be null" );
		Assert.notNull( command.getBranchId(), "RemoveAtmsFromBranchCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveAtmsFromBranchCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getATMId(), "RemoveAtmsFromBranchCommand removeFrom attribubte identifier should not be null" );
	}
	

}
