/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.company.validator;

import org.springframework.util.Assert;

import com.company.api.*;

/**
 * <h2>CollateralValidation</h2>
 * <p>
 * The Collateral Validation  handles state validation of a Collateral include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateCollateralCommand</li>
 *      <li>UpdateCollateralCommand</li>
 *      <li>DeleteCollateralCommand</li>
 *set( false = false )
  *       <li>AssignLoanAccountToCollateralCommand</li>
 *       <li>UnAssignLoanAccountFromCollateralCommand</li>
   * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class CollateralValidator {
		
	/**
	 * default constructor
	 */
	protected CollateralValidator() {	
	}
	
	/**
	 * factory method
	 */
	static public CollateralValidator getInstance() {
		return new CollateralValidator();
	}
		
	/**
	 * handles creation validation for a Collateral
	 */
	public void validate( CreateCollateralCommand collateral )throws Exception {
		Assert.notNull( collateral, "CreateCollateralCommand should not be null" );
//		Assert.isNull( collateral.getCollateralId(), "CreateCollateralCommand identifier should be null" );
		Assert.notNull( collateral.getAppraisedValue(), "Field CreateCollateralCommand.appraisedValue should not be null" );
		Assert.notNull( collateral.getDescription(), "Field CreateCollateralCommand.description should not be null" );
		Assert.notNull( collateral.getLocation(), "Field CreateCollateralCommand.location should not be null" );
	}

	/**
	 * handles update validation for a Collateral
	 */
	public void validate( UpdateCollateralCommand collateral ) throws Exception {
		Assert.notNull( collateral, "UpdateCollateralCommand should not be null" );
		Assert.notNull( collateral.getCollateralId(), "UpdateCollateralCommand identifier should not be null" );
		Assert.notNull( collateral.getAppraisedValue(), "Field UpdateCollateralCommand.appraisedValue should not be null" );
		Assert.notNull( collateral.getDescription(), "Field UpdateCollateralCommand.description should not be null" );
		Assert.notNull( collateral.getLocation(), "Field UpdateCollateralCommand.location should not be null" );
    }

	/**
	 * handles delete validation for a Collateral
	 */
    public void validate( DeleteCollateralCommand collateral ) throws Exception {
		Assert.notNull( collateral, "{commandAlias} should not be null" );
		Assert.notNull( collateral.getCollateralId(), "DeleteCollateralCommand identifier should not be null" );
	}
	
	/**
	 * handles fetchOne validation for a Collateral
	 */
	public void validate( CollateralFetchOneSummary summary ) throws Exception {
		Assert.notNull( summary, "CollateralFetchOneSummary should not be null" );
		Assert.notNull( summary.getCollateralId(), "CollateralFetchOneSummary identifier should not be null" );
	}

	/**
	 * handles assign LoanAccount validation for a Collateral
	 * 
	 * @param	command AssignLoanAccountToCollateralCommand
	 */	
	public void validate( AssignLoanAccountToCollateralCommand command ) throws Exception {
		Assert.notNull( command, "AssignLoanAccountToCollateralCommand should not be null" );
		Assert.notNull( command.getCollateralId(), "AssignLoanAccountToCollateralCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignLoanAccountToCollateralCommand assignment should not be null" );
	}

	/**
	 * handles unassign LoanAccount validation for a Collateral
	 * 
	 * @param	command UnAssignLoanAccountFromCollateralCommand
	 */	
	public void validate( UnAssignLoanAccountFromCollateralCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignLoanAccountFromCollateralCommand should not be null" );
		Assert.notNull( command.getCollateralId(), "UnAssignLoanAccountFromCollateralCommand identifier should not be null" );
	}


}
