/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.company.validator;

import org.springframework.util.Assert;

import com.company.api.*;

/**
 * <h2>ConsentValidation</h2>
 * <p>
 * The Consent Validation  handles state validation of a Consent include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>07/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateConsentCommand</li>
 *      <li>UpdateConsentCommand</li>
 *      <li>DeleteConsentCommand</li>
 *set( false = false )
  *       <li>AssignCustomerToConsentCommand</li>
 *       <li>UnAssignCustomerFromConsentCommand</li>
  *       <li>AssignBankToConsentCommand</li>
 *       <li>UnAssignBankFromConsentCommand</li>
  *       <li>AssignThirdPartyProviderToConsentCommand</li>
 *       <li>UnAssignThirdPartyProviderFromConsentCommand</li>
   *       <li>AssignAuthorizedAccountsToConsentCommand</li>
 *       <li>RemoveAuthorizedAccountsFromConsentCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class ConsentValidator {
		
	/**
	 * default constructor
	 */
	protected ConsentValidator() {	
	}
	
	/**
	 * factory method
	 */
	static public ConsentValidator getInstance() {
		return new ConsentValidator();
	}
		
	/**
	 * handles creation validation for a Consent
	 */
	public void validate( CreateConsentCommand consent )throws Exception {
		Assert.notNull( consent, "CreateConsentCommand should not be null" );
//		Assert.isNull( consent.getConsentId(), "CreateConsentCommand identifier should be null" );
		Assert.notNull( consent.getGrantedOn(), "Field CreateConsentCommand.grantedOn should not be null" );
		Assert.notNull( consent.getExpiresOn(), "Field CreateConsentCommand.expiresOn should not be null" );
	}

	/**
	 * handles update validation for a Consent
	 */
	public void validate( UpdateConsentCommand consent ) throws Exception {
		Assert.notNull( consent, "UpdateConsentCommand should not be null" );
		Assert.notNull( consent.getConsentId(), "UpdateConsentCommand identifier should not be null" );
		Assert.notNull( consent.getGrantedOn(), "Field UpdateConsentCommand.grantedOn should not be null" );
		Assert.notNull( consent.getExpiresOn(), "Field UpdateConsentCommand.expiresOn should not be null" );
    }

	/**
	 * handles delete validation for a Consent
	 */
    public void validate( DeleteConsentCommand consent ) throws Exception {
		Assert.notNull( consent, "{commandAlias} should not be null" );
		Assert.notNull( consent.getConsentId(), "DeleteConsentCommand identifier should not be null" );
	}
	
	/**
	 * handles fetchOne validation for a Consent
	 */
	public void validate( ConsentFetchOneSummary summary ) throws Exception {
		Assert.notNull( summary, "ConsentFetchOneSummary should not be null" );
		Assert.notNull( summary.getConsentId(), "ConsentFetchOneSummary identifier should not be null" );
	}

	/**
	 * handles assign Customer validation for a Consent
	 * 
	 * @param	command AssignCustomerToConsentCommand
	 */	
	public void validate( AssignCustomerToConsentCommand command ) throws Exception {
		Assert.notNull( command, "AssignCustomerToConsentCommand should not be null" );
		Assert.notNull( command.getConsentId(), "AssignCustomerToConsentCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignCustomerToConsentCommand assignment should not be null" );
	}

	/**
	 * handles unassign Customer validation for a Consent
	 * 
	 * @param	command UnAssignCustomerFromConsentCommand
	 */	
	public void validate( UnAssignCustomerFromConsentCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignCustomerFromConsentCommand should not be null" );
		Assert.notNull( command.getConsentId(), "UnAssignCustomerFromConsentCommand identifier should not be null" );
	}
	/**
	 * handles assign Bank validation for a Consent
	 * 
	 * @param	command AssignBankToConsentCommand
	 */	
	public void validate( AssignBankToConsentCommand command ) throws Exception {
		Assert.notNull( command, "AssignBankToConsentCommand should not be null" );
		Assert.notNull( command.getConsentId(), "AssignBankToConsentCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignBankToConsentCommand assignment should not be null" );
	}

	/**
	 * handles unassign Bank validation for a Consent
	 * 
	 * @param	command UnAssignBankFromConsentCommand
	 */	
	public void validate( UnAssignBankFromConsentCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignBankFromConsentCommand should not be null" );
		Assert.notNull( command.getConsentId(), "UnAssignBankFromConsentCommand identifier should not be null" );
	}
	/**
	 * handles assign ThirdPartyProvider validation for a Consent
	 * 
	 * @param	command AssignThirdPartyProviderToConsentCommand
	 */	
	public void validate( AssignThirdPartyProviderToConsentCommand command ) throws Exception {
		Assert.notNull( command, "AssignThirdPartyProviderToConsentCommand should not be null" );
		Assert.notNull( command.getConsentId(), "AssignThirdPartyProviderToConsentCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignThirdPartyProviderToConsentCommand assignment should not be null" );
	}

	/**
	 * handles unassign ThirdPartyProvider validation for a Consent
	 * 
	 * @param	command UnAssignThirdPartyProviderFromConsentCommand
	 */	
	public void validate( UnAssignThirdPartyProviderFromConsentCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignThirdPartyProviderFromConsentCommand should not be null" );
		Assert.notNull( command.getConsentId(), "UnAssignThirdPartyProviderFromConsentCommand identifier should not be null" );
	}

	/**
	 * handles add to AuthorizedAccounts validation for a Consent
	 * 
	 * @param	command AssignAuthorizedAccountsToConsentCommand
	 */	
	public void validate( AssignAuthorizedAccountsToConsentCommand command ) throws Exception {
		Assert.notNull( command, "AssignAuthorizedAccountsToConsentCommand should not be null" );
		Assert.notNull( command.getConsentId(), "AssignAuthorizedAccountsToConsentCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignAuthorizedAccountsToConsentCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from AuthorizedAccounts validation for a Consent
	 * 
	 * @param	command RemoveAuthorizedAccountsFromConsentCommand
	 */	
	public void validate( RemoveAuthorizedAccountsFromConsentCommand command ) throws Exception {
		Assert.notNull( command, "RemoveAuthorizedAccountsFromConsentCommand should not be null" );
		Assert.notNull( command.getConsentId(), "RemoveAuthorizedAccountsFromConsentCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveAuthorizedAccountsFromConsentCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getAccountId(), "RemoveAuthorizedAccountsFromConsentCommand removeFrom attribubte identifier should not be null" );
	}
	

}
