/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.company.validator;

import org.springframework.util.Assert;

import com.company.api.*;

/**
 * <h2>CustomerValidation</h2>
 * <p>
 * The Customer Validation  handles state validation of a Customer include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>07/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateCustomerCommand</li>
 *      <li>UpdateCustomerCommand</li>
 *      <li>DeleteCustomerCommand</li>
 *set( false = false )
  *       <li>AssignBankToCustomerCommand</li>
 *       <li>UnAssignBankFromCustomerCommand</li>
   *       <li>AssignAccountsToCustomerCommand</li>
 *       <li>RemoveAccountsFromCustomerCommand</li>
 *   </ul>
 *
  *       <li>AssignLoanAccountsToCustomerCommand</li>
 *       <li>RemoveLoanAccountsFromCustomerCommand</li>
 *   </ul>
 *
  *       <li>AssignPaymentCardsToCustomerCommand</li>
 *       <li>RemovePaymentCardsFromCustomerCommand</li>
 *   </ul>
 *
  *       <li>AssignExternalAccountsToCustomerCommand</li>
 *       <li>RemoveExternalAccountsFromCustomerCommand</li>
 *   </ul>
 *
  *       <li>AssignFundsTransfersToCustomerCommand</li>
 *       <li>RemoveFundsTransfersFromCustomerCommand</li>
 *   </ul>
 *
  *       <li>AssignDisputesToCustomerCommand</li>
 *       <li>RemoveDisputesFromCustomerCommand</li>
 *   </ul>
 *
  *       <li>AssignKycProfilesToCustomerCommand</li>
 *       <li>RemoveKycProfilesFromCustomerCommand</li>
 *   </ul>
 *
  *       <li>AssignConsentsToCustomerCommand</li>
 *       <li>RemoveConsentsFromCustomerCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class CustomerValidator {
		
	/**
	 * default constructor
	 */
	protected CustomerValidator() {	
	}
	
	/**
	 * factory method
	 */
	static public CustomerValidator getInstance() {
		return new CustomerValidator();
	}
		
	/**
	 * handles creation validation for a Customer
	 */
	public void validate( CreateCustomerCommand customer )throws Exception {
		Assert.notNull( customer, "CreateCustomerCommand should not be null" );
//		Assert.isNull( customer.getCustomerId(), "CreateCustomerCommand identifier should be null" );
		Assert.notNull( customer.getFirstName(), "Field CreateCustomerCommand.firstName should not be null" );
		Assert.notNull( customer.getLastName(), "Field CreateCustomerCommand.lastName should not be null" );
		Assert.notNull( customer.getLegalName(), "Field CreateCustomerCommand.legalName should not be null" );
		Assert.notNull( customer.getDateOfBirth(), "Field CreateCustomerCommand.dateOfBirth should not be null" );
		Assert.notNull( customer.getTaxId(), "Field CreateCustomerCommand.taxId should not be null" );
		Assert.notNull( customer.getEmail(), "Field CreateCustomerCommand.email should not be null" );
		Assert.notNull( customer.getPhone(), "Field CreateCustomerCommand.phone should not be null" );
		Assert.notNull( customer.getAddress(), "Field CreateCustomerCommand.address should not be null" );
	}

	/**
	 * handles update validation for a Customer
	 */
	public void validate( UpdateCustomerCommand customer ) throws Exception {
		Assert.notNull( customer, "UpdateCustomerCommand should not be null" );
		Assert.notNull( customer.getCustomerId(), "UpdateCustomerCommand identifier should not be null" );
		Assert.notNull( customer.getFirstName(), "Field UpdateCustomerCommand.firstName should not be null" );
		Assert.notNull( customer.getLastName(), "Field UpdateCustomerCommand.lastName should not be null" );
		Assert.notNull( customer.getLegalName(), "Field UpdateCustomerCommand.legalName should not be null" );
		Assert.notNull( customer.getDateOfBirth(), "Field UpdateCustomerCommand.dateOfBirth should not be null" );
		Assert.notNull( customer.getTaxId(), "Field UpdateCustomerCommand.taxId should not be null" );
		Assert.notNull( customer.getEmail(), "Field UpdateCustomerCommand.email should not be null" );
		Assert.notNull( customer.getPhone(), "Field UpdateCustomerCommand.phone should not be null" );
		Assert.notNull( customer.getAddress(), "Field UpdateCustomerCommand.address should not be null" );
    }

	/**
	 * handles delete validation for a Customer
	 */
    public void validate( DeleteCustomerCommand customer ) throws Exception {
		Assert.notNull( customer, "{commandAlias} should not be null" );
		Assert.notNull( customer.getCustomerId(), "DeleteCustomerCommand identifier should not be null" );
	}
	
	/**
	 * handles fetchOne validation for a Customer
	 */
	public void validate( CustomerFetchOneSummary summary ) throws Exception {
		Assert.notNull( summary, "CustomerFetchOneSummary should not be null" );
		Assert.notNull( summary.getCustomerId(), "CustomerFetchOneSummary identifier should not be null" );
	}

	/**
	 * handles assign Bank validation for a Customer
	 * 
	 * @param	command AssignBankToCustomerCommand
	 */	
	public void validate( AssignBankToCustomerCommand command ) throws Exception {
		Assert.notNull( command, "AssignBankToCustomerCommand should not be null" );
		Assert.notNull( command.getCustomerId(), "AssignBankToCustomerCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignBankToCustomerCommand assignment should not be null" );
	}

	/**
	 * handles unassign Bank validation for a Customer
	 * 
	 * @param	command UnAssignBankFromCustomerCommand
	 */	
	public void validate( UnAssignBankFromCustomerCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignBankFromCustomerCommand should not be null" );
		Assert.notNull( command.getCustomerId(), "UnAssignBankFromCustomerCommand identifier should not be null" );
	}

	/**
	 * handles add to Accounts validation for a Customer
	 * 
	 * @param	command AssignAccountsToCustomerCommand
	 */	
	public void validate( AssignAccountsToCustomerCommand command ) throws Exception {
		Assert.notNull( command, "AssignAccountsToCustomerCommand should not be null" );
		Assert.notNull( command.getCustomerId(), "AssignAccountsToCustomerCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignAccountsToCustomerCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from Accounts validation for a Customer
	 * 
	 * @param	command RemoveAccountsFromCustomerCommand
	 */	
	public void validate( RemoveAccountsFromCustomerCommand command ) throws Exception {
		Assert.notNull( command, "RemoveAccountsFromCustomerCommand should not be null" );
		Assert.notNull( command.getCustomerId(), "RemoveAccountsFromCustomerCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveAccountsFromCustomerCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getAccountId(), "RemoveAccountsFromCustomerCommand removeFrom attribubte identifier should not be null" );
	}
	
	/**
	 * handles add to LoanAccounts validation for a Customer
	 * 
	 * @param	command AssignLoanAccountsToCustomerCommand
	 */	
	public void validate( AssignLoanAccountsToCustomerCommand command ) throws Exception {
		Assert.notNull( command, "AssignLoanAccountsToCustomerCommand should not be null" );
		Assert.notNull( command.getCustomerId(), "AssignLoanAccountsToCustomerCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignLoanAccountsToCustomerCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from LoanAccounts validation for a Customer
	 * 
	 * @param	command RemoveLoanAccountsFromCustomerCommand
	 */	
	public void validate( RemoveLoanAccountsFromCustomerCommand command ) throws Exception {
		Assert.notNull( command, "RemoveLoanAccountsFromCustomerCommand should not be null" );
		Assert.notNull( command.getCustomerId(), "RemoveLoanAccountsFromCustomerCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveLoanAccountsFromCustomerCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getLoanAccountId(), "RemoveLoanAccountsFromCustomerCommand removeFrom attribubte identifier should not be null" );
	}
	
	/**
	 * handles add to PaymentCards validation for a Customer
	 * 
	 * @param	command AssignPaymentCardsToCustomerCommand
	 */	
	public void validate( AssignPaymentCardsToCustomerCommand command ) throws Exception {
		Assert.notNull( command, "AssignPaymentCardsToCustomerCommand should not be null" );
		Assert.notNull( command.getCustomerId(), "AssignPaymentCardsToCustomerCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignPaymentCardsToCustomerCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from PaymentCards validation for a Customer
	 * 
	 * @param	command RemovePaymentCardsFromCustomerCommand
	 */	
	public void validate( RemovePaymentCardsFromCustomerCommand command ) throws Exception {
		Assert.notNull( command, "RemovePaymentCardsFromCustomerCommand should not be null" );
		Assert.notNull( command.getCustomerId(), "RemovePaymentCardsFromCustomerCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemovePaymentCardsFromCustomerCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getPaymentCardId(), "RemovePaymentCardsFromCustomerCommand removeFrom attribubte identifier should not be null" );
	}
	
	/**
	 * handles add to ExternalAccounts validation for a Customer
	 * 
	 * @param	command AssignExternalAccountsToCustomerCommand
	 */	
	public void validate( AssignExternalAccountsToCustomerCommand command ) throws Exception {
		Assert.notNull( command, "AssignExternalAccountsToCustomerCommand should not be null" );
		Assert.notNull( command.getCustomerId(), "AssignExternalAccountsToCustomerCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignExternalAccountsToCustomerCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from ExternalAccounts validation for a Customer
	 * 
	 * @param	command RemoveExternalAccountsFromCustomerCommand
	 */	
	public void validate( RemoveExternalAccountsFromCustomerCommand command ) throws Exception {
		Assert.notNull( command, "RemoveExternalAccountsFromCustomerCommand should not be null" );
		Assert.notNull( command.getCustomerId(), "RemoveExternalAccountsFromCustomerCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveExternalAccountsFromCustomerCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getExternalAccountId(), "RemoveExternalAccountsFromCustomerCommand removeFrom attribubte identifier should not be null" );
	}
	
	/**
	 * handles add to FundsTransfers validation for a Customer
	 * 
	 * @param	command AssignFundsTransfersToCustomerCommand
	 */	
	public void validate( AssignFundsTransfersToCustomerCommand command ) throws Exception {
		Assert.notNull( command, "AssignFundsTransfersToCustomerCommand should not be null" );
		Assert.notNull( command.getCustomerId(), "AssignFundsTransfersToCustomerCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignFundsTransfersToCustomerCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from FundsTransfers validation for a Customer
	 * 
	 * @param	command RemoveFundsTransfersFromCustomerCommand
	 */	
	public void validate( RemoveFundsTransfersFromCustomerCommand command ) throws Exception {
		Assert.notNull( command, "RemoveFundsTransfersFromCustomerCommand should not be null" );
		Assert.notNull( command.getCustomerId(), "RemoveFundsTransfersFromCustomerCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveFundsTransfersFromCustomerCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getFundsTransferId(), "RemoveFundsTransfersFromCustomerCommand removeFrom attribubte identifier should not be null" );
	}
	
	/**
	 * handles add to Disputes validation for a Customer
	 * 
	 * @param	command AssignDisputesToCustomerCommand
	 */	
	public void validate( AssignDisputesToCustomerCommand command ) throws Exception {
		Assert.notNull( command, "AssignDisputesToCustomerCommand should not be null" );
		Assert.notNull( command.getCustomerId(), "AssignDisputesToCustomerCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignDisputesToCustomerCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from Disputes validation for a Customer
	 * 
	 * @param	command RemoveDisputesFromCustomerCommand
	 */	
	public void validate( RemoveDisputesFromCustomerCommand command ) throws Exception {
		Assert.notNull( command, "RemoveDisputesFromCustomerCommand should not be null" );
		Assert.notNull( command.getCustomerId(), "RemoveDisputesFromCustomerCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveDisputesFromCustomerCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getDisputeId(), "RemoveDisputesFromCustomerCommand removeFrom attribubte identifier should not be null" );
	}
	
	/**
	 * handles add to KycProfiles validation for a Customer
	 * 
	 * @param	command AssignKycProfilesToCustomerCommand
	 */	
	public void validate( AssignKycProfilesToCustomerCommand command ) throws Exception {
		Assert.notNull( command, "AssignKycProfilesToCustomerCommand should not be null" );
		Assert.notNull( command.getCustomerId(), "AssignKycProfilesToCustomerCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignKycProfilesToCustomerCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from KycProfiles validation for a Customer
	 * 
	 * @param	command RemoveKycProfilesFromCustomerCommand
	 */	
	public void validate( RemoveKycProfilesFromCustomerCommand command ) throws Exception {
		Assert.notNull( command, "RemoveKycProfilesFromCustomerCommand should not be null" );
		Assert.notNull( command.getCustomerId(), "RemoveKycProfilesFromCustomerCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveKycProfilesFromCustomerCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getKycProfileId(), "RemoveKycProfilesFromCustomerCommand removeFrom attribubte identifier should not be null" );
	}
	
	/**
	 * handles add to Consents validation for a Customer
	 * 
	 * @param	command AssignConsentsToCustomerCommand
	 */	
	public void validate( AssignConsentsToCustomerCommand command ) throws Exception {
		Assert.notNull( command, "AssignConsentsToCustomerCommand should not be null" );
		Assert.notNull( command.getCustomerId(), "AssignConsentsToCustomerCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignConsentsToCustomerCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from Consents validation for a Customer
	 * 
	 * @param	command RemoveConsentsFromCustomerCommand
	 */	
	public void validate( RemoveConsentsFromCustomerCommand command ) throws Exception {
		Assert.notNull( command, "RemoveConsentsFromCustomerCommand should not be null" );
		Assert.notNull( command.getCustomerId(), "RemoveConsentsFromCustomerCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveConsentsFromCustomerCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getConsentId(), "RemoveConsentsFromCustomerCommand removeFrom attribubte identifier should not be null" );
	}
	

}
