/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.company.validator;

import org.springframework.util.Assert;

import com.company.api.*;

/**
 * <h2>DisputeValidation</h2>
 * <p>
 * The Dispute Validation  handles state validation of a Dispute include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateDisputeCommand</li>
 *      <li>UpdateDisputeCommand</li>
 *      <li>DeleteDisputeCommand</li>
 *set( false = false )
  *       <li>AssignTransactionToDisputeCommand</li>
 *       <li>UnAssignTransactionFromDisputeCommand</li>
  *       <li>AssignCustomerToDisputeCommand</li>
 *       <li>UnAssignCustomerFromDisputeCommand</li>
  *       <li>AssignAccountToDisputeCommand</li>
 *       <li>UnAssignAccountFromDisputeCommand</li>
  *       <li>AssignPaymentCardToDisputeCommand</li>
 *       <li>UnAssignPaymentCardFromDisputeCommand</li>
   * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class DisputeValidator {
		
	/**
	 * default constructor
	 */
	protected DisputeValidator() {	
	}
	
	/**
	 * factory method
	 */
	static public DisputeValidator getInstance() {
		return new DisputeValidator();
	}
		
	/**
	 * handles creation validation for a Dispute
	 */
	public void validate( CreateDisputeCommand dispute )throws Exception {
		Assert.notNull( dispute, "CreateDisputeCommand should not be null" );
//		Assert.isNull( dispute.getDisputeId(), "CreateDisputeCommand identifier should be null" );
		Assert.notNull( dispute.getDisputeReference(), "Field CreateDisputeCommand.disputeReference should not be null" );
		Assert.notNull( dispute.getRaisedOn(), "Field CreateDisputeCommand.raisedOn should not be null" );
		Assert.notNull( dispute.getReason(), "Field CreateDisputeCommand.reason should not be null" );
	}

	/**
	 * handles update validation for a Dispute
	 */
	public void validate( UpdateDisputeCommand dispute ) throws Exception {
		Assert.notNull( dispute, "UpdateDisputeCommand should not be null" );
		Assert.notNull( dispute.getDisputeId(), "UpdateDisputeCommand identifier should not be null" );
		Assert.notNull( dispute.getDisputeReference(), "Field UpdateDisputeCommand.disputeReference should not be null" );
		Assert.notNull( dispute.getRaisedOn(), "Field UpdateDisputeCommand.raisedOn should not be null" );
		Assert.notNull( dispute.getReason(), "Field UpdateDisputeCommand.reason should not be null" );
    }

	/**
	 * handles delete validation for a Dispute
	 */
    public void validate( DeleteDisputeCommand dispute ) throws Exception {
		Assert.notNull( dispute, "{commandAlias} should not be null" );
		Assert.notNull( dispute.getDisputeId(), "DeleteDisputeCommand identifier should not be null" );
	}
	
	/**
	 * handles fetchOne validation for a Dispute
	 */
	public void validate( DisputeFetchOneSummary summary ) throws Exception {
		Assert.notNull( summary, "DisputeFetchOneSummary should not be null" );
		Assert.notNull( summary.getDisputeId(), "DisputeFetchOneSummary identifier should not be null" );
	}

	/**
	 * handles assign Transaction validation for a Dispute
	 * 
	 * @param	command AssignTransactionToDisputeCommand
	 */	
	public void validate( AssignTransactionToDisputeCommand command ) throws Exception {
		Assert.notNull( command, "AssignTransactionToDisputeCommand should not be null" );
		Assert.notNull( command.getDisputeId(), "AssignTransactionToDisputeCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignTransactionToDisputeCommand assignment should not be null" );
	}

	/**
	 * handles unassign Transaction validation for a Dispute
	 * 
	 * @param	command UnAssignTransactionFromDisputeCommand
	 */	
	public void validate( UnAssignTransactionFromDisputeCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignTransactionFromDisputeCommand should not be null" );
		Assert.notNull( command.getDisputeId(), "UnAssignTransactionFromDisputeCommand identifier should not be null" );
	}
	/**
	 * handles assign Customer validation for a Dispute
	 * 
	 * @param	command AssignCustomerToDisputeCommand
	 */	
	public void validate( AssignCustomerToDisputeCommand command ) throws Exception {
		Assert.notNull( command, "AssignCustomerToDisputeCommand should not be null" );
		Assert.notNull( command.getDisputeId(), "AssignCustomerToDisputeCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignCustomerToDisputeCommand assignment should not be null" );
	}

	/**
	 * handles unassign Customer validation for a Dispute
	 * 
	 * @param	command UnAssignCustomerFromDisputeCommand
	 */	
	public void validate( UnAssignCustomerFromDisputeCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignCustomerFromDisputeCommand should not be null" );
		Assert.notNull( command.getDisputeId(), "UnAssignCustomerFromDisputeCommand identifier should not be null" );
	}
	/**
	 * handles assign Account validation for a Dispute
	 * 
	 * @param	command AssignAccountToDisputeCommand
	 */	
	public void validate( AssignAccountToDisputeCommand command ) throws Exception {
		Assert.notNull( command, "AssignAccountToDisputeCommand should not be null" );
		Assert.notNull( command.getDisputeId(), "AssignAccountToDisputeCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignAccountToDisputeCommand assignment should not be null" );
	}

	/**
	 * handles unassign Account validation for a Dispute
	 * 
	 * @param	command UnAssignAccountFromDisputeCommand
	 */	
	public void validate( UnAssignAccountFromDisputeCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignAccountFromDisputeCommand should not be null" );
		Assert.notNull( command.getDisputeId(), "UnAssignAccountFromDisputeCommand identifier should not be null" );
	}
	/**
	 * handles assign PaymentCard validation for a Dispute
	 * 
	 * @param	command AssignPaymentCardToDisputeCommand
	 */	
	public void validate( AssignPaymentCardToDisputeCommand command ) throws Exception {
		Assert.notNull( command, "AssignPaymentCardToDisputeCommand should not be null" );
		Assert.notNull( command.getDisputeId(), "AssignPaymentCardToDisputeCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignPaymentCardToDisputeCommand assignment should not be null" );
	}

	/**
	 * handles unassign PaymentCard validation for a Dispute
	 * 
	 * @param	command UnAssignPaymentCardFromDisputeCommand
	 */	
	public void validate( UnAssignPaymentCardFromDisputeCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignPaymentCardFromDisputeCommand should not be null" );
		Assert.notNull( command.getDisputeId(), "UnAssignPaymentCardFromDisputeCommand identifier should not be null" );
	}


}
