/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.company.validator;

import org.springframework.util.Assert;

import com.company.api.*;

/**
 * <h2>ExchangeRateValidation</h2>
 * <p>
 * The ExchangeRate Validation  handles state validation of a ExchangeRate include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateExchangeRateCommand</li>
 *      <li>UpdateExchangeRateCommand</li>
 *      <li>DeleteExchangeRateCommand</li>
 *set( false = false )
  *       <li>AssignBankToExchangeRateCommand</li>
 *       <li>UnAssignBankFromExchangeRateCommand</li>
   *       <li>AssignFxTradesToExchangeRateCommand</li>
 *       <li>RemoveFxTradesFromExchangeRateCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class ExchangeRateValidator {
		
	/**
	 * default constructor
	 */
	protected ExchangeRateValidator() {	
	}
	
	/**
	 * factory method
	 */
	static public ExchangeRateValidator getInstance() {
		return new ExchangeRateValidator();
	}
		
	/**
	 * handles creation validation for a ExchangeRate
	 */
	public void validate( CreateExchangeRateCommand exchangeRate )throws Exception {
		Assert.notNull( exchangeRate, "CreateExchangeRateCommand should not be null" );
//		Assert.isNull( exchangeRate.getExchangeRateId(), "CreateExchangeRateCommand identifier should be null" );
		Assert.notNull( exchangeRate.getBaseCurrency(), "Field CreateExchangeRateCommand.baseCurrency should not be null" );
		Assert.notNull( exchangeRate.getCounterCurrency(), "Field CreateExchangeRateCommand.counterCurrency should not be null" );
		Assert.notNull( exchangeRate.getRate(), "Field CreateExchangeRateCommand.rate should not be null" );
		Assert.notNull( exchangeRate.getAsOf(), "Field CreateExchangeRateCommand.asOf should not be null" );
		Assert.notNull( exchangeRate.getSource(), "Field CreateExchangeRateCommand.source should not be null" );
	}

	/**
	 * handles update validation for a ExchangeRate
	 */
	public void validate( UpdateExchangeRateCommand exchangeRate ) throws Exception {
		Assert.notNull( exchangeRate, "UpdateExchangeRateCommand should not be null" );
		Assert.notNull( exchangeRate.getExchangeRateId(), "UpdateExchangeRateCommand identifier should not be null" );
		Assert.notNull( exchangeRate.getBaseCurrency(), "Field UpdateExchangeRateCommand.baseCurrency should not be null" );
		Assert.notNull( exchangeRate.getCounterCurrency(), "Field UpdateExchangeRateCommand.counterCurrency should not be null" );
		Assert.notNull( exchangeRate.getRate(), "Field UpdateExchangeRateCommand.rate should not be null" );
		Assert.notNull( exchangeRate.getAsOf(), "Field UpdateExchangeRateCommand.asOf should not be null" );
		Assert.notNull( exchangeRate.getSource(), "Field UpdateExchangeRateCommand.source should not be null" );
    }

	/**
	 * handles delete validation for a ExchangeRate
	 */
    public void validate( DeleteExchangeRateCommand exchangeRate ) throws Exception {
		Assert.notNull( exchangeRate, "{commandAlias} should not be null" );
		Assert.notNull( exchangeRate.getExchangeRateId(), "DeleteExchangeRateCommand identifier should not be null" );
	}
	
	/**
	 * handles fetchOne validation for a ExchangeRate
	 */
	public void validate( ExchangeRateFetchOneSummary summary ) throws Exception {
		Assert.notNull( summary, "ExchangeRateFetchOneSummary should not be null" );
		Assert.notNull( summary.getExchangeRateId(), "ExchangeRateFetchOneSummary identifier should not be null" );
	}

	/**
	 * handles assign Bank validation for a ExchangeRate
	 * 
	 * @param	command AssignBankToExchangeRateCommand
	 */	
	public void validate( AssignBankToExchangeRateCommand command ) throws Exception {
		Assert.notNull( command, "AssignBankToExchangeRateCommand should not be null" );
		Assert.notNull( command.getExchangeRateId(), "AssignBankToExchangeRateCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignBankToExchangeRateCommand assignment should not be null" );
	}

	/**
	 * handles unassign Bank validation for a ExchangeRate
	 * 
	 * @param	command UnAssignBankFromExchangeRateCommand
	 */	
	public void validate( UnAssignBankFromExchangeRateCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignBankFromExchangeRateCommand should not be null" );
		Assert.notNull( command.getExchangeRateId(), "UnAssignBankFromExchangeRateCommand identifier should not be null" );
	}

	/**
	 * handles add to FxTrades validation for a ExchangeRate
	 * 
	 * @param	command AssignFxTradesToExchangeRateCommand
	 */	
	public void validate( AssignFxTradesToExchangeRateCommand command ) throws Exception {
		Assert.notNull( command, "AssignFxTradesToExchangeRateCommand should not be null" );
		Assert.notNull( command.getExchangeRateId(), "AssignFxTradesToExchangeRateCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignFxTradesToExchangeRateCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from FxTrades validation for a ExchangeRate
	 * 
	 * @param	command RemoveFxTradesFromExchangeRateCommand
	 */	
	public void validate( RemoveFxTradesFromExchangeRateCommand command ) throws Exception {
		Assert.notNull( command, "RemoveFxTradesFromExchangeRateCommand should not be null" );
		Assert.notNull( command.getExchangeRateId(), "RemoveFxTradesFromExchangeRateCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveFxTradesFromExchangeRateCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getFXTradeId(), "RemoveFxTradesFromExchangeRateCommand removeFrom attribubte identifier should not be null" );
	}
	

}
