/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.company.validator;

import org.springframework.util.Assert;

import com.company.api.*;

/**
 * <h2>ExternalAccountValidation</h2>
 * <p>
 * The ExternalAccount Validation  handles state validation of a ExternalAccount include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateExternalAccountCommand</li>
 *      <li>UpdateExternalAccountCommand</li>
 *      <li>DeleteExternalAccountCommand</li>
 *set( false = false )
  *       <li>AssignCustomerToExternalAccountCommand</li>
 *       <li>UnAssignCustomerFromExternalAccountCommand</li>
   *       <li>AssignTransactionsToExternalAccountCommand</li>
 *       <li>RemoveTransactionsFromExternalAccountCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class ExternalAccountValidator {
		
	/**
	 * default constructor
	 */
	protected ExternalAccountValidator() {	
	}
	
	/**
	 * factory method
	 */
	static public ExternalAccountValidator getInstance() {
		return new ExternalAccountValidator();
	}
		
	/**
	 * handles creation validation for a ExternalAccount
	 */
	public void validate( CreateExternalAccountCommand externalAccount )throws Exception {
		Assert.notNull( externalAccount, "CreateExternalAccountCommand should not be null" );
//		Assert.isNull( externalAccount.getExternalAccountId(), "CreateExternalAccountCommand identifier should be null" );
		Assert.notNull( externalAccount.getName(), "Field CreateExternalAccountCommand.name should not be null" );
		Assert.notNull( externalAccount.getIban(), "Field CreateExternalAccountCommand.iban should not be null" );
		Assert.notNull( externalAccount.getAccountNumber(), "Field CreateExternalAccountCommand.accountNumber should not be null" );
		Assert.notNull( externalAccount.getBic(), "Field CreateExternalAccountCommand.bic should not be null" );
		Assert.notNull( externalAccount.getBankName(), "Field CreateExternalAccountCommand.bankName should not be null" );
		Assert.notNull( externalAccount.getCountry(), "Field CreateExternalAccountCommand.country should not be null" );
	}

	/**
	 * handles update validation for a ExternalAccount
	 */
	public void validate( UpdateExternalAccountCommand externalAccount ) throws Exception {
		Assert.notNull( externalAccount, "UpdateExternalAccountCommand should not be null" );
		Assert.notNull( externalAccount.getExternalAccountId(), "UpdateExternalAccountCommand identifier should not be null" );
		Assert.notNull( externalAccount.getName(), "Field UpdateExternalAccountCommand.name should not be null" );
		Assert.notNull( externalAccount.getIban(), "Field UpdateExternalAccountCommand.iban should not be null" );
		Assert.notNull( externalAccount.getAccountNumber(), "Field UpdateExternalAccountCommand.accountNumber should not be null" );
		Assert.notNull( externalAccount.getBic(), "Field UpdateExternalAccountCommand.bic should not be null" );
		Assert.notNull( externalAccount.getBankName(), "Field UpdateExternalAccountCommand.bankName should not be null" );
		Assert.notNull( externalAccount.getCountry(), "Field UpdateExternalAccountCommand.country should not be null" );
    }

	/**
	 * handles delete validation for a ExternalAccount
	 */
    public void validate( DeleteExternalAccountCommand externalAccount ) throws Exception {
		Assert.notNull( externalAccount, "{commandAlias} should not be null" );
		Assert.notNull( externalAccount.getExternalAccountId(), "DeleteExternalAccountCommand identifier should not be null" );
	}
	
	/**
	 * handles fetchOne validation for a ExternalAccount
	 */
	public void validate( ExternalAccountFetchOneSummary summary ) throws Exception {
		Assert.notNull( summary, "ExternalAccountFetchOneSummary should not be null" );
		Assert.notNull( summary.getExternalAccountId(), "ExternalAccountFetchOneSummary identifier should not be null" );
	}

	/**
	 * handles assign Customer validation for a ExternalAccount
	 * 
	 * @param	command AssignCustomerToExternalAccountCommand
	 */	
	public void validate( AssignCustomerToExternalAccountCommand command ) throws Exception {
		Assert.notNull( command, "AssignCustomerToExternalAccountCommand should not be null" );
		Assert.notNull( command.getExternalAccountId(), "AssignCustomerToExternalAccountCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignCustomerToExternalAccountCommand assignment should not be null" );
	}

	/**
	 * handles unassign Customer validation for a ExternalAccount
	 * 
	 * @param	command UnAssignCustomerFromExternalAccountCommand
	 */	
	public void validate( UnAssignCustomerFromExternalAccountCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignCustomerFromExternalAccountCommand should not be null" );
		Assert.notNull( command.getExternalAccountId(), "UnAssignCustomerFromExternalAccountCommand identifier should not be null" );
	}

	/**
	 * handles add to Transactions validation for a ExternalAccount
	 * 
	 * @param	command AssignTransactionsToExternalAccountCommand
	 */	
	public void validate( AssignTransactionsToExternalAccountCommand command ) throws Exception {
		Assert.notNull( command, "AssignTransactionsToExternalAccountCommand should not be null" );
		Assert.notNull( command.getExternalAccountId(), "AssignTransactionsToExternalAccountCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignTransactionsToExternalAccountCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from Transactions validation for a ExternalAccount
	 * 
	 * @param	command RemoveTransactionsFromExternalAccountCommand
	 */	
	public void validate( RemoveTransactionsFromExternalAccountCommand command ) throws Exception {
		Assert.notNull( command, "RemoveTransactionsFromExternalAccountCommand should not be null" );
		Assert.notNull( command.getExternalAccountId(), "RemoveTransactionsFromExternalAccountCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveTransactionsFromExternalAccountCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getTransactionId(), "RemoveTransactionsFromExternalAccountCommand removeFrom attribubte identifier should not be null" );
	}
	

}
