/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.company.validator;

import org.springframework.util.Assert;

import com.company.api.*;

/**
 * <h2>FeeChargeValidation</h2>
 * <p>
 * The FeeCharge Validation  handles state validation of a FeeCharge include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>07/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateFeeChargeCommand</li>
 *      <li>UpdateFeeChargeCommand</li>
 *      <li>DeleteFeeChargeCommand</li>
 *set( false = false )
  *       <li>AssignAccountToFeeChargeCommand</li>
 *       <li>UnAssignAccountFromFeeChargeCommand</li>
  *       <li>AssignLoanAccountToFeeChargeCommand</li>
 *       <li>UnAssignLoanAccountFromFeeChargeCommand</li>
   * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class FeeChargeValidator {
		
	/**
	 * default constructor
	 */
	protected FeeChargeValidator() {	
	}
	
	/**
	 * factory method
	 */
	static public FeeChargeValidator getInstance() {
		return new FeeChargeValidator();
	}
		
	/**
	 * handles creation validation for a FeeCharge
	 */
	public void validate( CreateFeeChargeCommand feeCharge )throws Exception {
		Assert.notNull( feeCharge, "CreateFeeChargeCommand should not be null" );
//		Assert.isNull( feeCharge.getFeeChargeId(), "CreateFeeChargeCommand identifier should be null" );
		Assert.notNull( feeCharge.getFeeCode(), "Field CreateFeeChargeCommand.feeCode should not be null" );
		Assert.notNull( feeCharge.getAmount(), "Field CreateFeeChargeCommand.amount should not be null" );
		Assert.notNull( feeCharge.getAppliedOn(), "Field CreateFeeChargeCommand.appliedOn should not be null" );
	}

	/**
	 * handles update validation for a FeeCharge
	 */
	public void validate( UpdateFeeChargeCommand feeCharge ) throws Exception {
		Assert.notNull( feeCharge, "UpdateFeeChargeCommand should not be null" );
		Assert.notNull( feeCharge.getFeeChargeId(), "UpdateFeeChargeCommand identifier should not be null" );
		Assert.notNull( feeCharge.getFeeCode(), "Field UpdateFeeChargeCommand.feeCode should not be null" );
		Assert.notNull( feeCharge.getAmount(), "Field UpdateFeeChargeCommand.amount should not be null" );
		Assert.notNull( feeCharge.getAppliedOn(), "Field UpdateFeeChargeCommand.appliedOn should not be null" );
    }

	/**
	 * handles delete validation for a FeeCharge
	 */
    public void validate( DeleteFeeChargeCommand feeCharge ) throws Exception {
		Assert.notNull( feeCharge, "{commandAlias} should not be null" );
		Assert.notNull( feeCharge.getFeeChargeId(), "DeleteFeeChargeCommand identifier should not be null" );
	}
	
	/**
	 * handles fetchOne validation for a FeeCharge
	 */
	public void validate( FeeChargeFetchOneSummary summary ) throws Exception {
		Assert.notNull( summary, "FeeChargeFetchOneSummary should not be null" );
		Assert.notNull( summary.getFeeChargeId(), "FeeChargeFetchOneSummary identifier should not be null" );
	}

	/**
	 * handles assign Account validation for a FeeCharge
	 * 
	 * @param	command AssignAccountToFeeChargeCommand
	 */	
	public void validate( AssignAccountToFeeChargeCommand command ) throws Exception {
		Assert.notNull( command, "AssignAccountToFeeChargeCommand should not be null" );
		Assert.notNull( command.getFeeChargeId(), "AssignAccountToFeeChargeCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignAccountToFeeChargeCommand assignment should not be null" );
	}

	/**
	 * handles unassign Account validation for a FeeCharge
	 * 
	 * @param	command UnAssignAccountFromFeeChargeCommand
	 */	
	public void validate( UnAssignAccountFromFeeChargeCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignAccountFromFeeChargeCommand should not be null" );
		Assert.notNull( command.getFeeChargeId(), "UnAssignAccountFromFeeChargeCommand identifier should not be null" );
	}
	/**
	 * handles assign LoanAccount validation for a FeeCharge
	 * 
	 * @param	command AssignLoanAccountToFeeChargeCommand
	 */	
	public void validate( AssignLoanAccountToFeeChargeCommand command ) throws Exception {
		Assert.notNull( command, "AssignLoanAccountToFeeChargeCommand should not be null" );
		Assert.notNull( command.getFeeChargeId(), "AssignLoanAccountToFeeChargeCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignLoanAccountToFeeChargeCommand assignment should not be null" );
	}

	/**
	 * handles unassign LoanAccount validation for a FeeCharge
	 * 
	 * @param	command UnAssignLoanAccountFromFeeChargeCommand
	 */	
	public void validate( UnAssignLoanAccountFromFeeChargeCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignLoanAccountFromFeeChargeCommand should not be null" );
		Assert.notNull( command.getFeeChargeId(), "UnAssignLoanAccountFromFeeChargeCommand identifier should not be null" );
	}


}
