/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.company.validator;

import org.springframework.util.Assert;

import com.company.api.*;

/**
 * <h2>FundsTransferValidation</h2>
 * <p>
 * The FundsTransfer Validation  handles state validation of a FundsTransfer include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateFundsTransferCommand</li>
 *      <li>UpdateFundsTransferCommand</li>
 *      <li>DeleteFundsTransferCommand</li>
 *set( false = false )
  *       <li>AssignSourceAccountToFundsTransferCommand</li>
 *       <li>UnAssignSourceAccountFromFundsTransferCommand</li>
  *       <li>AssignDestinationAccountToFundsTransferCommand</li>
 *       <li>UnAssignDestinationAccountFromFundsTransferCommand</li>
  *       <li>AssignExternalBeneficiaryToFundsTransferCommand</li>
 *       <li>UnAssignExternalBeneficiaryFromFundsTransferCommand</li>
  *       <li>AssignInitiatedByToFundsTransferCommand</li>
 *       <li>UnAssignInitiatedByFromFundsTransferCommand</li>
   *       <li>AssignTransactionsToFundsTransferCommand</li>
 *       <li>RemoveTransactionsFromFundsTransferCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class FundsTransferValidator {
		
	/**
	 * default constructor
	 */
	protected FundsTransferValidator() {	
	}
	
	/**
	 * factory method
	 */
	static public FundsTransferValidator getInstance() {
		return new FundsTransferValidator();
	}
		
	/**
	 * handles creation validation for a FundsTransfer
	 */
	public void validate( CreateFundsTransferCommand fundsTransfer )throws Exception {
		Assert.notNull( fundsTransfer, "CreateFundsTransferCommand should not be null" );
//		Assert.isNull( fundsTransfer.getFundsTransferId(), "CreateFundsTransferCommand identifier should be null" );
		Assert.notNull( fundsTransfer.getTransferReference(), "Field CreateFundsTransferCommand.transferReference should not be null" );
		Assert.notNull( fundsTransfer.getAmount(), "Field CreateFundsTransferCommand.amount should not be null" );
		Assert.notNull( fundsTransfer.getRequestedDate(), "Field CreateFundsTransferCommand.requestedDate should not be null" );
		Assert.notNull( fundsTransfer.getExecutionDate(), "Field CreateFundsTransferCommand.executionDate should not be null" );
		Assert.notNull( fundsTransfer.getPurpose(), "Field CreateFundsTransferCommand.purpose should not be null" );
		Assert.notNull( fundsTransfer.getFeeAmount(), "Field CreateFundsTransferCommand.feeAmount should not be null" );
	}

	/**
	 * handles update validation for a FundsTransfer
	 */
	public void validate( UpdateFundsTransferCommand fundsTransfer ) throws Exception {
		Assert.notNull( fundsTransfer, "UpdateFundsTransferCommand should not be null" );
		Assert.notNull( fundsTransfer.getFundsTransferId(), "UpdateFundsTransferCommand identifier should not be null" );
		Assert.notNull( fundsTransfer.getTransferReference(), "Field UpdateFundsTransferCommand.transferReference should not be null" );
		Assert.notNull( fundsTransfer.getAmount(), "Field UpdateFundsTransferCommand.amount should not be null" );
		Assert.notNull( fundsTransfer.getRequestedDate(), "Field UpdateFundsTransferCommand.requestedDate should not be null" );
		Assert.notNull( fundsTransfer.getExecutionDate(), "Field UpdateFundsTransferCommand.executionDate should not be null" );
		Assert.notNull( fundsTransfer.getPurpose(), "Field UpdateFundsTransferCommand.purpose should not be null" );
		Assert.notNull( fundsTransfer.getFeeAmount(), "Field UpdateFundsTransferCommand.feeAmount should not be null" );
    }

	/**
	 * handles delete validation for a FundsTransfer
	 */
    public void validate( DeleteFundsTransferCommand fundsTransfer ) throws Exception {
		Assert.notNull( fundsTransfer, "{commandAlias} should not be null" );
		Assert.notNull( fundsTransfer.getFundsTransferId(), "DeleteFundsTransferCommand identifier should not be null" );
	}
	
	/**
	 * handles fetchOne validation for a FundsTransfer
	 */
	public void validate( FundsTransferFetchOneSummary summary ) throws Exception {
		Assert.notNull( summary, "FundsTransferFetchOneSummary should not be null" );
		Assert.notNull( summary.getFundsTransferId(), "FundsTransferFetchOneSummary identifier should not be null" );
	}

	/**
	 * handles assign SourceAccount validation for a FundsTransfer
	 * 
	 * @param	command AssignSourceAccountToFundsTransferCommand
	 */	
	public void validate( AssignSourceAccountToFundsTransferCommand command ) throws Exception {
		Assert.notNull( command, "AssignSourceAccountToFundsTransferCommand should not be null" );
		Assert.notNull( command.getFundsTransferId(), "AssignSourceAccountToFundsTransferCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignSourceAccountToFundsTransferCommand assignment should not be null" );
	}

	/**
	 * handles unassign SourceAccount validation for a FundsTransfer
	 * 
	 * @param	command UnAssignSourceAccountFromFundsTransferCommand
	 */	
	public void validate( UnAssignSourceAccountFromFundsTransferCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignSourceAccountFromFundsTransferCommand should not be null" );
		Assert.notNull( command.getFundsTransferId(), "UnAssignSourceAccountFromFundsTransferCommand identifier should not be null" );
	}
	/**
	 * handles assign DestinationAccount validation for a FundsTransfer
	 * 
	 * @param	command AssignDestinationAccountToFundsTransferCommand
	 */	
	public void validate( AssignDestinationAccountToFundsTransferCommand command ) throws Exception {
		Assert.notNull( command, "AssignDestinationAccountToFundsTransferCommand should not be null" );
		Assert.notNull( command.getFundsTransferId(), "AssignDestinationAccountToFundsTransferCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignDestinationAccountToFundsTransferCommand assignment should not be null" );
	}

	/**
	 * handles unassign DestinationAccount validation for a FundsTransfer
	 * 
	 * @param	command UnAssignDestinationAccountFromFundsTransferCommand
	 */	
	public void validate( UnAssignDestinationAccountFromFundsTransferCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignDestinationAccountFromFundsTransferCommand should not be null" );
		Assert.notNull( command.getFundsTransferId(), "UnAssignDestinationAccountFromFundsTransferCommand identifier should not be null" );
	}
	/**
	 * handles assign ExternalBeneficiary validation for a FundsTransfer
	 * 
	 * @param	command AssignExternalBeneficiaryToFundsTransferCommand
	 */	
	public void validate( AssignExternalBeneficiaryToFundsTransferCommand command ) throws Exception {
		Assert.notNull( command, "AssignExternalBeneficiaryToFundsTransferCommand should not be null" );
		Assert.notNull( command.getFundsTransferId(), "AssignExternalBeneficiaryToFundsTransferCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignExternalBeneficiaryToFundsTransferCommand assignment should not be null" );
	}

	/**
	 * handles unassign ExternalBeneficiary validation for a FundsTransfer
	 * 
	 * @param	command UnAssignExternalBeneficiaryFromFundsTransferCommand
	 */	
	public void validate( UnAssignExternalBeneficiaryFromFundsTransferCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignExternalBeneficiaryFromFundsTransferCommand should not be null" );
		Assert.notNull( command.getFundsTransferId(), "UnAssignExternalBeneficiaryFromFundsTransferCommand identifier should not be null" );
	}
	/**
	 * handles assign InitiatedBy validation for a FundsTransfer
	 * 
	 * @param	command AssignInitiatedByToFundsTransferCommand
	 */	
	public void validate( AssignInitiatedByToFundsTransferCommand command ) throws Exception {
		Assert.notNull( command, "AssignInitiatedByToFundsTransferCommand should not be null" );
		Assert.notNull( command.getFundsTransferId(), "AssignInitiatedByToFundsTransferCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignInitiatedByToFundsTransferCommand assignment should not be null" );
	}

	/**
	 * handles unassign InitiatedBy validation for a FundsTransfer
	 * 
	 * @param	command UnAssignInitiatedByFromFundsTransferCommand
	 */	
	public void validate( UnAssignInitiatedByFromFundsTransferCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignInitiatedByFromFundsTransferCommand should not be null" );
		Assert.notNull( command.getFundsTransferId(), "UnAssignInitiatedByFromFundsTransferCommand identifier should not be null" );
	}

	/**
	 * handles add to Transactions validation for a FundsTransfer
	 * 
	 * @param	command AssignTransactionsToFundsTransferCommand
	 */	
	public void validate( AssignTransactionsToFundsTransferCommand command ) throws Exception {
		Assert.notNull( command, "AssignTransactionsToFundsTransferCommand should not be null" );
		Assert.notNull( command.getFundsTransferId(), "AssignTransactionsToFundsTransferCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignTransactionsToFundsTransferCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from Transactions validation for a FundsTransfer
	 * 
	 * @param	command RemoveTransactionsFromFundsTransferCommand
	 */	
	public void validate( RemoveTransactionsFromFundsTransferCommand command ) throws Exception {
		Assert.notNull( command, "RemoveTransactionsFromFundsTransferCommand should not be null" );
		Assert.notNull( command.getFundsTransferId(), "RemoveTransactionsFromFundsTransferCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveTransactionsFromFundsTransferCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getTransactionId(), "RemoveTransactionsFromFundsTransferCommand removeFrom attribubte identifier should not be null" );
	}
	

}
