/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.company.validator;

import org.springframework.util.Assert;

import com.company.api.*;

/**
 * <h2>FXTradeValidation</h2>
 * <p>
 * The FXTrade Validation  handles state validation of a FXTrade include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>07/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateFXTradeCommand</li>
 *      <li>UpdateFXTradeCommand</li>
 *      <li>DeleteFXTradeCommand</li>
 *set( false = false )
  *       <li>AssignCustomerToFXTradeCommand</li>
 *       <li>UnAssignCustomerFromFXTradeCommand</li>
  *       <li>AssignBankToFXTradeCommand</li>
 *       <li>UnAssignBankFromFXTradeCommand</li>
  *       <li>AssignExchangeRateToFXTradeCommand</li>
 *       <li>UnAssignExchangeRateFromFXTradeCommand</li>
  *       <li>AssignSourceAccountToFXTradeCommand</li>
 *       <li>UnAssignSourceAccountFromFXTradeCommand</li>
  *       <li>AssignDestinationAccountToFXTradeCommand</li>
 *       <li>UnAssignDestinationAccountFromFXTradeCommand</li>
  *       <li>AssignTransactionToFXTradeCommand</li>
 *       <li>UnAssignTransactionFromFXTradeCommand</li>
   * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class FXTradeValidator {
		
	/**
	 * default constructor
	 */
	protected FXTradeValidator() {	
	}
	
	/**
	 * factory method
	 */
	static public FXTradeValidator getInstance() {
		return new FXTradeValidator();
	}
		
	/**
	 * handles creation validation for a FXTrade
	 */
	public void validate( CreateFXTradeCommand fXTrade )throws Exception {
		Assert.notNull( fXTrade, "CreateFXTradeCommand should not be null" );
//		Assert.isNull( fXTrade.getFXTradeId(), "CreateFXTradeCommand identifier should be null" );
		Assert.notNull( fXTrade.getTradeReference(), "Field CreateFXTradeCommand.tradeReference should not be null" );
		Assert.notNull( fXTrade.getTradeDate(), "Field CreateFXTradeCommand.tradeDate should not be null" );
		Assert.notNull( fXTrade.getSettlementDate(), "Field CreateFXTradeCommand.settlementDate should not be null" );
		Assert.notNull( fXTrade.getAmountSold(), "Field CreateFXTradeCommand.amountSold should not be null" );
		Assert.notNull( fXTrade.getAmountBought(), "Field CreateFXTradeCommand.amountBought should not be null" );
		Assert.notNull( fXTrade.getRate(), "Field CreateFXTradeCommand.rate should not be null" );
	}

	/**
	 * handles update validation for a FXTrade
	 */
	public void validate( UpdateFXTradeCommand fXTrade ) throws Exception {
		Assert.notNull( fXTrade, "UpdateFXTradeCommand should not be null" );
		Assert.notNull( fXTrade.getFXTradeId(), "UpdateFXTradeCommand identifier should not be null" );
		Assert.notNull( fXTrade.getTradeReference(), "Field UpdateFXTradeCommand.tradeReference should not be null" );
		Assert.notNull( fXTrade.getTradeDate(), "Field UpdateFXTradeCommand.tradeDate should not be null" );
		Assert.notNull( fXTrade.getSettlementDate(), "Field UpdateFXTradeCommand.settlementDate should not be null" );
		Assert.notNull( fXTrade.getAmountSold(), "Field UpdateFXTradeCommand.amountSold should not be null" );
		Assert.notNull( fXTrade.getAmountBought(), "Field UpdateFXTradeCommand.amountBought should not be null" );
		Assert.notNull( fXTrade.getRate(), "Field UpdateFXTradeCommand.rate should not be null" );
    }

	/**
	 * handles delete validation for a FXTrade
	 */
    public void validate( DeleteFXTradeCommand fXTrade ) throws Exception {
		Assert.notNull( fXTrade, "{commandAlias} should not be null" );
		Assert.notNull( fXTrade.getFXTradeId(), "DeleteFXTradeCommand identifier should not be null" );
	}
	
	/**
	 * handles fetchOne validation for a FXTrade
	 */
	public void validate( FXTradeFetchOneSummary summary ) throws Exception {
		Assert.notNull( summary, "FXTradeFetchOneSummary should not be null" );
		Assert.notNull( summary.getFXTradeId(), "FXTradeFetchOneSummary identifier should not be null" );
	}

	/**
	 * handles assign Customer validation for a FXTrade
	 * 
	 * @param	command AssignCustomerToFXTradeCommand
	 */	
	public void validate( AssignCustomerToFXTradeCommand command ) throws Exception {
		Assert.notNull( command, "AssignCustomerToFXTradeCommand should not be null" );
		Assert.notNull( command.getFXTradeId(), "AssignCustomerToFXTradeCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignCustomerToFXTradeCommand assignment should not be null" );
	}

	/**
	 * handles unassign Customer validation for a FXTrade
	 * 
	 * @param	command UnAssignCustomerFromFXTradeCommand
	 */	
	public void validate( UnAssignCustomerFromFXTradeCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignCustomerFromFXTradeCommand should not be null" );
		Assert.notNull( command.getFXTradeId(), "UnAssignCustomerFromFXTradeCommand identifier should not be null" );
	}
	/**
	 * handles assign Bank validation for a FXTrade
	 * 
	 * @param	command AssignBankToFXTradeCommand
	 */	
	public void validate( AssignBankToFXTradeCommand command ) throws Exception {
		Assert.notNull( command, "AssignBankToFXTradeCommand should not be null" );
		Assert.notNull( command.getFXTradeId(), "AssignBankToFXTradeCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignBankToFXTradeCommand assignment should not be null" );
	}

	/**
	 * handles unassign Bank validation for a FXTrade
	 * 
	 * @param	command UnAssignBankFromFXTradeCommand
	 */	
	public void validate( UnAssignBankFromFXTradeCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignBankFromFXTradeCommand should not be null" );
		Assert.notNull( command.getFXTradeId(), "UnAssignBankFromFXTradeCommand identifier should not be null" );
	}
	/**
	 * handles assign ExchangeRate validation for a FXTrade
	 * 
	 * @param	command AssignExchangeRateToFXTradeCommand
	 */	
	public void validate( AssignExchangeRateToFXTradeCommand command ) throws Exception {
		Assert.notNull( command, "AssignExchangeRateToFXTradeCommand should not be null" );
		Assert.notNull( command.getFXTradeId(), "AssignExchangeRateToFXTradeCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignExchangeRateToFXTradeCommand assignment should not be null" );
	}

	/**
	 * handles unassign ExchangeRate validation for a FXTrade
	 * 
	 * @param	command UnAssignExchangeRateFromFXTradeCommand
	 */	
	public void validate( UnAssignExchangeRateFromFXTradeCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignExchangeRateFromFXTradeCommand should not be null" );
		Assert.notNull( command.getFXTradeId(), "UnAssignExchangeRateFromFXTradeCommand identifier should not be null" );
	}
	/**
	 * handles assign SourceAccount validation for a FXTrade
	 * 
	 * @param	command AssignSourceAccountToFXTradeCommand
	 */	
	public void validate( AssignSourceAccountToFXTradeCommand command ) throws Exception {
		Assert.notNull( command, "AssignSourceAccountToFXTradeCommand should not be null" );
		Assert.notNull( command.getFXTradeId(), "AssignSourceAccountToFXTradeCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignSourceAccountToFXTradeCommand assignment should not be null" );
	}

	/**
	 * handles unassign SourceAccount validation for a FXTrade
	 * 
	 * @param	command UnAssignSourceAccountFromFXTradeCommand
	 */	
	public void validate( UnAssignSourceAccountFromFXTradeCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignSourceAccountFromFXTradeCommand should not be null" );
		Assert.notNull( command.getFXTradeId(), "UnAssignSourceAccountFromFXTradeCommand identifier should not be null" );
	}
	/**
	 * handles assign DestinationAccount validation for a FXTrade
	 * 
	 * @param	command AssignDestinationAccountToFXTradeCommand
	 */	
	public void validate( AssignDestinationAccountToFXTradeCommand command ) throws Exception {
		Assert.notNull( command, "AssignDestinationAccountToFXTradeCommand should not be null" );
		Assert.notNull( command.getFXTradeId(), "AssignDestinationAccountToFXTradeCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignDestinationAccountToFXTradeCommand assignment should not be null" );
	}

	/**
	 * handles unassign DestinationAccount validation for a FXTrade
	 * 
	 * @param	command UnAssignDestinationAccountFromFXTradeCommand
	 */	
	public void validate( UnAssignDestinationAccountFromFXTradeCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignDestinationAccountFromFXTradeCommand should not be null" );
		Assert.notNull( command.getFXTradeId(), "UnAssignDestinationAccountFromFXTradeCommand identifier should not be null" );
	}
	/**
	 * handles assign Transaction validation for a FXTrade
	 * 
	 * @param	command AssignTransactionToFXTradeCommand
	 */	
	public void validate( AssignTransactionToFXTradeCommand command ) throws Exception {
		Assert.notNull( command, "AssignTransactionToFXTradeCommand should not be null" );
		Assert.notNull( command.getFXTradeId(), "AssignTransactionToFXTradeCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignTransactionToFXTradeCommand assignment should not be null" );
	}

	/**
	 * handles unassign Transaction validation for a FXTrade
	 * 
	 * @param	command UnAssignTransactionFromFXTradeCommand
	 */	
	public void validate( UnAssignTransactionFromFXTradeCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignTransactionFromFXTradeCommand should not be null" );
		Assert.notNull( command.getFXTradeId(), "UnAssignTransactionFromFXTradeCommand identifier should not be null" );
	}


}
