/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.company.validator;

import org.springframework.util.Assert;

import com.company.api.*;

/**
 * <h2>IdentityDocumentValidation</h2>
 * <p>
 * The IdentityDocument Validation  handles state validation of a IdentityDocument include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateIdentityDocumentCommand</li>
 *      <li>UpdateIdentityDocumentCommand</li>
 *      <li>DeleteIdentityDocumentCommand</li>
 *set( false = false )
  *       <li>AssignKycProfileToIdentityDocumentCommand</li>
 *       <li>UnAssignKycProfileFromIdentityDocumentCommand</li>
   * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class IdentityDocumentValidator {
		
	/**
	 * default constructor
	 */
	protected IdentityDocumentValidator() {	
	}
	
	/**
	 * factory method
	 */
	static public IdentityDocumentValidator getInstance() {
		return new IdentityDocumentValidator();
	}
		
	/**
	 * handles creation validation for a IdentityDocument
	 */
	public void validate( CreateIdentityDocumentCommand identityDocument )throws Exception {
		Assert.notNull( identityDocument, "CreateIdentityDocumentCommand should not be null" );
//		Assert.isNull( identityDocument.getIdentityDocumentId(), "CreateIdentityDocumentCommand identifier should be null" );
		Assert.notNull( identityDocument.getDocumentNumber(), "Field CreateIdentityDocumentCommand.documentNumber should not be null" );
		Assert.notNull( identityDocument.getIssuingCountry(), "Field CreateIdentityDocumentCommand.issuingCountry should not be null" );
		Assert.notNull( identityDocument.getExpirationDate(), "Field CreateIdentityDocumentCommand.expirationDate should not be null" );
	}

	/**
	 * handles update validation for a IdentityDocument
	 */
	public void validate( UpdateIdentityDocumentCommand identityDocument ) throws Exception {
		Assert.notNull( identityDocument, "UpdateIdentityDocumentCommand should not be null" );
		Assert.notNull( identityDocument.getIdentityDocumentId(), "UpdateIdentityDocumentCommand identifier should not be null" );
		Assert.notNull( identityDocument.getDocumentNumber(), "Field UpdateIdentityDocumentCommand.documentNumber should not be null" );
		Assert.notNull( identityDocument.getIssuingCountry(), "Field UpdateIdentityDocumentCommand.issuingCountry should not be null" );
		Assert.notNull( identityDocument.getExpirationDate(), "Field UpdateIdentityDocumentCommand.expirationDate should not be null" );
    }

	/**
	 * handles delete validation for a IdentityDocument
	 */
    public void validate( DeleteIdentityDocumentCommand identityDocument ) throws Exception {
		Assert.notNull( identityDocument, "{commandAlias} should not be null" );
		Assert.notNull( identityDocument.getIdentityDocumentId(), "DeleteIdentityDocumentCommand identifier should not be null" );
	}
	
	/**
	 * handles fetchOne validation for a IdentityDocument
	 */
	public void validate( IdentityDocumentFetchOneSummary summary ) throws Exception {
		Assert.notNull( summary, "IdentityDocumentFetchOneSummary should not be null" );
		Assert.notNull( summary.getIdentityDocumentId(), "IdentityDocumentFetchOneSummary identifier should not be null" );
	}

	/**
	 * handles assign KycProfile validation for a IdentityDocument
	 * 
	 * @param	command AssignKycProfileToIdentityDocumentCommand
	 */	
	public void validate( AssignKycProfileToIdentityDocumentCommand command ) throws Exception {
		Assert.notNull( command, "AssignKycProfileToIdentityDocumentCommand should not be null" );
		Assert.notNull( command.getIdentityDocumentId(), "AssignKycProfileToIdentityDocumentCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignKycProfileToIdentityDocumentCommand assignment should not be null" );
	}

	/**
	 * handles unassign KycProfile validation for a IdentityDocument
	 * 
	 * @param	command UnAssignKycProfileFromIdentityDocumentCommand
	 */	
	public void validate( UnAssignKycProfileFromIdentityDocumentCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignKycProfileFromIdentityDocumentCommand should not be null" );
		Assert.notNull( command.getIdentityDocumentId(), "UnAssignKycProfileFromIdentityDocumentCommand identifier should not be null" );
	}


}
