/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.company.validator;

import org.springframework.util.Assert;

import com.company.api.*;

/**
 * <h2>KycProfileValidation</h2>
 * <p>
 * The KycProfile Validation  handles state validation of a KycProfile include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>07/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateKycProfileCommand</li>
 *      <li>UpdateKycProfileCommand</li>
 *      <li>DeleteKycProfileCommand</li>
 *set( false = false )
  *       <li>AssignCustomerToKycProfileCommand</li>
 *       <li>UnAssignCustomerFromKycProfileCommand</li>
   *       <li>AssignIdentityDocumentsToKycProfileCommand</li>
 *       <li>RemoveIdentityDocumentsFromKycProfileCommand</li>
 *   </ul>
 *
  *       <li>AssignRiskAssessmentsToKycProfileCommand</li>
 *       <li>RemoveRiskAssessmentsFromKycProfileCommand</li>
 *   </ul>
 *
  *       <li>AssignScreeningsToKycProfileCommand</li>
 *       <li>RemoveScreeningsFromKycProfileCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class KycProfileValidator {
		
	/**
	 * default constructor
	 */
	protected KycProfileValidator() {	
	}
	
	/**
	 * factory method
	 */
	static public KycProfileValidator getInstance() {
		return new KycProfileValidator();
	}
		
	/**
	 * handles creation validation for a KycProfile
	 */
	public void validate( CreateKycProfileCommand kycProfile )throws Exception {
		Assert.notNull( kycProfile, "CreateKycProfileCommand should not be null" );
//		Assert.isNull( kycProfile.getKycProfileId(), "CreateKycProfileCommand identifier should be null" );
		Assert.notNull( kycProfile.getProfileId(), "Field CreateKycProfileCommand.profileId should not be null" );
		Assert.notNull( kycProfile.getLastReviewedOn(), "Field CreateKycProfileCommand.lastReviewedOn should not be null" );
	}

	/**
	 * handles update validation for a KycProfile
	 */
	public void validate( UpdateKycProfileCommand kycProfile ) throws Exception {
		Assert.notNull( kycProfile, "UpdateKycProfileCommand should not be null" );
		Assert.notNull( kycProfile.getKycProfileId(), "UpdateKycProfileCommand identifier should not be null" );
		Assert.notNull( kycProfile.getProfileId(), "Field UpdateKycProfileCommand.profileId should not be null" );
		Assert.notNull( kycProfile.getLastReviewedOn(), "Field UpdateKycProfileCommand.lastReviewedOn should not be null" );
    }

	/**
	 * handles delete validation for a KycProfile
	 */
    public void validate( DeleteKycProfileCommand kycProfile ) throws Exception {
		Assert.notNull( kycProfile, "{commandAlias} should not be null" );
		Assert.notNull( kycProfile.getKycProfileId(), "DeleteKycProfileCommand identifier should not be null" );
	}
	
	/**
	 * handles fetchOne validation for a KycProfile
	 */
	public void validate( KycProfileFetchOneSummary summary ) throws Exception {
		Assert.notNull( summary, "KycProfileFetchOneSummary should not be null" );
		Assert.notNull( summary.getKycProfileId(), "KycProfileFetchOneSummary identifier should not be null" );
	}

	/**
	 * handles assign Customer validation for a KycProfile
	 * 
	 * @param	command AssignCustomerToKycProfileCommand
	 */	
	public void validate( AssignCustomerToKycProfileCommand command ) throws Exception {
		Assert.notNull( command, "AssignCustomerToKycProfileCommand should not be null" );
		Assert.notNull( command.getKycProfileId(), "AssignCustomerToKycProfileCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignCustomerToKycProfileCommand assignment should not be null" );
	}

	/**
	 * handles unassign Customer validation for a KycProfile
	 * 
	 * @param	command UnAssignCustomerFromKycProfileCommand
	 */	
	public void validate( UnAssignCustomerFromKycProfileCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignCustomerFromKycProfileCommand should not be null" );
		Assert.notNull( command.getKycProfileId(), "UnAssignCustomerFromKycProfileCommand identifier should not be null" );
	}

	/**
	 * handles add to IdentityDocuments validation for a KycProfile
	 * 
	 * @param	command AssignIdentityDocumentsToKycProfileCommand
	 */	
	public void validate( AssignIdentityDocumentsToKycProfileCommand command ) throws Exception {
		Assert.notNull( command, "AssignIdentityDocumentsToKycProfileCommand should not be null" );
		Assert.notNull( command.getKycProfileId(), "AssignIdentityDocumentsToKycProfileCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignIdentityDocumentsToKycProfileCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from IdentityDocuments validation for a KycProfile
	 * 
	 * @param	command RemoveIdentityDocumentsFromKycProfileCommand
	 */	
	public void validate( RemoveIdentityDocumentsFromKycProfileCommand command ) throws Exception {
		Assert.notNull( command, "RemoveIdentityDocumentsFromKycProfileCommand should not be null" );
		Assert.notNull( command.getKycProfileId(), "RemoveIdentityDocumentsFromKycProfileCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveIdentityDocumentsFromKycProfileCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getIdentityDocumentId(), "RemoveIdentityDocumentsFromKycProfileCommand removeFrom attribubte identifier should not be null" );
	}
	
	/**
	 * handles add to RiskAssessments validation for a KycProfile
	 * 
	 * @param	command AssignRiskAssessmentsToKycProfileCommand
	 */	
	public void validate( AssignRiskAssessmentsToKycProfileCommand command ) throws Exception {
		Assert.notNull( command, "AssignRiskAssessmentsToKycProfileCommand should not be null" );
		Assert.notNull( command.getKycProfileId(), "AssignRiskAssessmentsToKycProfileCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignRiskAssessmentsToKycProfileCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from RiskAssessments validation for a KycProfile
	 * 
	 * @param	command RemoveRiskAssessmentsFromKycProfileCommand
	 */	
	public void validate( RemoveRiskAssessmentsFromKycProfileCommand command ) throws Exception {
		Assert.notNull( command, "RemoveRiskAssessmentsFromKycProfileCommand should not be null" );
		Assert.notNull( command.getKycProfileId(), "RemoveRiskAssessmentsFromKycProfileCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveRiskAssessmentsFromKycProfileCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getRiskAssessmentId(), "RemoveRiskAssessmentsFromKycProfileCommand removeFrom attribubte identifier should not be null" );
	}
	
	/**
	 * handles add to Screenings validation for a KycProfile
	 * 
	 * @param	command AssignScreeningsToKycProfileCommand
	 */	
	public void validate( AssignScreeningsToKycProfileCommand command ) throws Exception {
		Assert.notNull( command, "AssignScreeningsToKycProfileCommand should not be null" );
		Assert.notNull( command.getKycProfileId(), "AssignScreeningsToKycProfileCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignScreeningsToKycProfileCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from Screenings validation for a KycProfile
	 * 
	 * @param	command RemoveScreeningsFromKycProfileCommand
	 */	
	public void validate( RemoveScreeningsFromKycProfileCommand command ) throws Exception {
		Assert.notNull( command, "RemoveScreeningsFromKycProfileCommand should not be null" );
		Assert.notNull( command.getKycProfileId(), "RemoveScreeningsFromKycProfileCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveScreeningsFromKycProfileCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getScreeningResultId(), "RemoveScreeningsFromKycProfileCommand removeFrom attribubte identifier should not be null" );
	}
	

}
