/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.company.validator;

import org.springframework.util.Assert;

import com.company.api.*;

/**
 * <h2>LoanPaymentValidation</h2>
 * <p>
 * The LoanPayment Validation  handles state validation of a LoanPayment include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>07/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateLoanPaymentCommand</li>
 *      <li>UpdateLoanPaymentCommand</li>
 *      <li>DeleteLoanPaymentCommand</li>
 *set( false = false )
  *       <li>AssignLoanAccountToLoanPaymentCommand</li>
 *       <li>UnAssignLoanAccountFromLoanPaymentCommand</li>
  *       <li>AssignTransactionToLoanPaymentCommand</li>
 *       <li>UnAssignTransactionFromLoanPaymentCommand</li>
   * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class LoanPaymentValidator {
		
	/**
	 * default constructor
	 */
	protected LoanPaymentValidator() {	
	}
	
	/**
	 * factory method
	 */
	static public LoanPaymentValidator getInstance() {
		return new LoanPaymentValidator();
	}
		
	/**
	 * handles creation validation for a LoanPayment
	 */
	public void validate( CreateLoanPaymentCommand loanPayment )throws Exception {
		Assert.notNull( loanPayment, "CreateLoanPaymentCommand should not be null" );
//		Assert.isNull( loanPayment.getLoanPaymentId(), "CreateLoanPaymentCommand identifier should be null" );
		Assert.notNull( loanPayment.getPaymentReference(), "Field CreateLoanPaymentCommand.paymentReference should not be null" );
		Assert.notNull( loanPayment.getAmount(), "Field CreateLoanPaymentCommand.amount should not be null" );
		Assert.notNull( loanPayment.getPaymentDate(), "Field CreateLoanPaymentCommand.paymentDate should not be null" );
	}

	/**
	 * handles update validation for a LoanPayment
	 */
	public void validate( UpdateLoanPaymentCommand loanPayment ) throws Exception {
		Assert.notNull( loanPayment, "UpdateLoanPaymentCommand should not be null" );
		Assert.notNull( loanPayment.getLoanPaymentId(), "UpdateLoanPaymentCommand identifier should not be null" );
		Assert.notNull( loanPayment.getPaymentReference(), "Field UpdateLoanPaymentCommand.paymentReference should not be null" );
		Assert.notNull( loanPayment.getAmount(), "Field UpdateLoanPaymentCommand.amount should not be null" );
		Assert.notNull( loanPayment.getPaymentDate(), "Field UpdateLoanPaymentCommand.paymentDate should not be null" );
    }

	/**
	 * handles delete validation for a LoanPayment
	 */
    public void validate( DeleteLoanPaymentCommand loanPayment ) throws Exception {
		Assert.notNull( loanPayment, "{commandAlias} should not be null" );
		Assert.notNull( loanPayment.getLoanPaymentId(), "DeleteLoanPaymentCommand identifier should not be null" );
	}
	
	/**
	 * handles fetchOne validation for a LoanPayment
	 */
	public void validate( LoanPaymentFetchOneSummary summary ) throws Exception {
		Assert.notNull( summary, "LoanPaymentFetchOneSummary should not be null" );
		Assert.notNull( summary.getLoanPaymentId(), "LoanPaymentFetchOneSummary identifier should not be null" );
	}

	/**
	 * handles assign LoanAccount validation for a LoanPayment
	 * 
	 * @param	command AssignLoanAccountToLoanPaymentCommand
	 */	
	public void validate( AssignLoanAccountToLoanPaymentCommand command ) throws Exception {
		Assert.notNull( command, "AssignLoanAccountToLoanPaymentCommand should not be null" );
		Assert.notNull( command.getLoanPaymentId(), "AssignLoanAccountToLoanPaymentCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignLoanAccountToLoanPaymentCommand assignment should not be null" );
	}

	/**
	 * handles unassign LoanAccount validation for a LoanPayment
	 * 
	 * @param	command UnAssignLoanAccountFromLoanPaymentCommand
	 */	
	public void validate( UnAssignLoanAccountFromLoanPaymentCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignLoanAccountFromLoanPaymentCommand should not be null" );
		Assert.notNull( command.getLoanPaymentId(), "UnAssignLoanAccountFromLoanPaymentCommand identifier should not be null" );
	}
	/**
	 * handles assign Transaction validation for a LoanPayment
	 * 
	 * @param	command AssignTransactionToLoanPaymentCommand
	 */	
	public void validate( AssignTransactionToLoanPaymentCommand command ) throws Exception {
		Assert.notNull( command, "AssignTransactionToLoanPaymentCommand should not be null" );
		Assert.notNull( command.getLoanPaymentId(), "AssignTransactionToLoanPaymentCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignTransactionToLoanPaymentCommand assignment should not be null" );
	}

	/**
	 * handles unassign Transaction validation for a LoanPayment
	 * 
	 * @param	command UnAssignTransactionFromLoanPaymentCommand
	 */	
	public void validate( UnAssignTransactionFromLoanPaymentCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignTransactionFromLoanPaymentCommand should not be null" );
		Assert.notNull( command.getLoanPaymentId(), "UnAssignTransactionFromLoanPaymentCommand identifier should not be null" );
	}


}
