/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.company.validator;

import org.springframework.util.Assert;

import com.company.api.*;

/**
 * <h2>LoanAccountValidation</h2>
 * <p>
 * The LoanAccount Validation  handles state validation of a LoanAccount include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>07/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateLoanAccountCommand</li>
 *      <li>UpdateLoanAccountCommand</li>
 *      <li>DeleteLoanAccountCommand</li>
 *set( false = false )
  *       <li>AssignBankToLoanAccountCommand</li>
 *       <li>UnAssignBankFromLoanAccountCommand</li>
  *       <li>AssignBranchToLoanAccountCommand</li>
 *       <li>UnAssignBranchFromLoanAccountCommand</li>
  *       <li>AssignProductToLoanAccountCommand</li>
 *       <li>UnAssignProductFromLoanAccountCommand</li>
   *       <li>AssignBorrowersToLoanAccountCommand</li>
 *       <li>RemoveBorrowersFromLoanAccountCommand</li>
 *   </ul>
 *
  *       <li>AssignRepaymentScheduleToLoanAccountCommand</li>
 *       <li>RemoveRepaymentScheduleFromLoanAccountCommand</li>
 *   </ul>
 *
  *       <li>AssignPaymentsToLoanAccountCommand</li>
 *       <li>RemovePaymentsFromLoanAccountCommand</li>
 *   </ul>
 *
  *       <li>AssignCollateralToLoanAccountCommand</li>
 *       <li>RemoveCollateralFromLoanAccountCommand</li>
 *   </ul>
 *
  *       <li>AssignFeeChargesToLoanAccountCommand</li>
 *       <li>RemoveFeeChargesFromLoanAccountCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class LoanAccountValidator {
		
	/**
	 * default constructor
	 */
	protected LoanAccountValidator() {	
	}
	
	/**
	 * factory method
	 */
	static public LoanAccountValidator getInstance() {
		return new LoanAccountValidator();
	}
		
	/**
	 * handles creation validation for a LoanAccount
	 */
	public void validate( CreateLoanAccountCommand loanAccount )throws Exception {
		Assert.notNull( loanAccount, "CreateLoanAccountCommand should not be null" );
//		Assert.isNull( loanAccount.getLoanAccountId(), "CreateLoanAccountCommand identifier should be null" );
		Assert.notNull( loanAccount.getLoanNumber(), "Field CreateLoanAccountCommand.loanNumber should not be null" );
		Assert.notNull( loanAccount.getPrincipalAmount(), "Field CreateLoanAccountCommand.principalAmount should not be null" );
		Assert.notNull( loanAccount.getOutstandingPrincipal(), "Field CreateLoanAccountCommand.outstandingPrincipal should not be null" );
		Assert.notNull( loanAccount.getInterestRate(), "Field CreateLoanAccountCommand.interestRate should not be null" );
		Assert.notNull( loanAccount.getOriginationDate(), "Field CreateLoanAccountCommand.originationDate should not be null" );
		Assert.notNull( loanAccount.getMaturityDate(), "Field CreateLoanAccountCommand.maturityDate should not be null" );
		Assert.notNull( loanAccount.getPaymentDayOfMonth(), "Field CreateLoanAccountCommand.paymentDayOfMonth should not be null" );
		Assert.notNull( loanAccount.getCurrency(), "Field CreateLoanAccountCommand.currency should not be null" );
	}

	/**
	 * handles update validation for a LoanAccount
	 */
	public void validate( UpdateLoanAccountCommand loanAccount ) throws Exception {
		Assert.notNull( loanAccount, "UpdateLoanAccountCommand should not be null" );
		Assert.notNull( loanAccount.getLoanAccountId(), "UpdateLoanAccountCommand identifier should not be null" );
		Assert.notNull( loanAccount.getLoanNumber(), "Field UpdateLoanAccountCommand.loanNumber should not be null" );
		Assert.notNull( loanAccount.getPrincipalAmount(), "Field UpdateLoanAccountCommand.principalAmount should not be null" );
		Assert.notNull( loanAccount.getOutstandingPrincipal(), "Field UpdateLoanAccountCommand.outstandingPrincipal should not be null" );
		Assert.notNull( loanAccount.getInterestRate(), "Field UpdateLoanAccountCommand.interestRate should not be null" );
		Assert.notNull( loanAccount.getOriginationDate(), "Field UpdateLoanAccountCommand.originationDate should not be null" );
		Assert.notNull( loanAccount.getMaturityDate(), "Field UpdateLoanAccountCommand.maturityDate should not be null" );
		Assert.notNull( loanAccount.getPaymentDayOfMonth(), "Field UpdateLoanAccountCommand.paymentDayOfMonth should not be null" );
		Assert.notNull( loanAccount.getCurrency(), "Field UpdateLoanAccountCommand.currency should not be null" );
    }

	/**
	 * handles delete validation for a LoanAccount
	 */
    public void validate( DeleteLoanAccountCommand loanAccount ) throws Exception {
		Assert.notNull( loanAccount, "{commandAlias} should not be null" );
		Assert.notNull( loanAccount.getLoanAccountId(), "DeleteLoanAccountCommand identifier should not be null" );
	}
	
	/**
	 * handles fetchOne validation for a LoanAccount
	 */
	public void validate( LoanAccountFetchOneSummary summary ) throws Exception {
		Assert.notNull( summary, "LoanAccountFetchOneSummary should not be null" );
		Assert.notNull( summary.getLoanAccountId(), "LoanAccountFetchOneSummary identifier should not be null" );
	}

	/**
	 * handles assign Bank validation for a LoanAccount
	 * 
	 * @param	command AssignBankToLoanAccountCommand
	 */	
	public void validate( AssignBankToLoanAccountCommand command ) throws Exception {
		Assert.notNull( command, "AssignBankToLoanAccountCommand should not be null" );
		Assert.notNull( command.getLoanAccountId(), "AssignBankToLoanAccountCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignBankToLoanAccountCommand assignment should not be null" );
	}

	/**
	 * handles unassign Bank validation for a LoanAccount
	 * 
	 * @param	command UnAssignBankFromLoanAccountCommand
	 */	
	public void validate( UnAssignBankFromLoanAccountCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignBankFromLoanAccountCommand should not be null" );
		Assert.notNull( command.getLoanAccountId(), "UnAssignBankFromLoanAccountCommand identifier should not be null" );
	}
	/**
	 * handles assign Branch validation for a LoanAccount
	 * 
	 * @param	command AssignBranchToLoanAccountCommand
	 */	
	public void validate( AssignBranchToLoanAccountCommand command ) throws Exception {
		Assert.notNull( command, "AssignBranchToLoanAccountCommand should not be null" );
		Assert.notNull( command.getLoanAccountId(), "AssignBranchToLoanAccountCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignBranchToLoanAccountCommand assignment should not be null" );
	}

	/**
	 * handles unassign Branch validation for a LoanAccount
	 * 
	 * @param	command UnAssignBranchFromLoanAccountCommand
	 */	
	public void validate( UnAssignBranchFromLoanAccountCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignBranchFromLoanAccountCommand should not be null" );
		Assert.notNull( command.getLoanAccountId(), "UnAssignBranchFromLoanAccountCommand identifier should not be null" );
	}
	/**
	 * handles assign Product validation for a LoanAccount
	 * 
	 * @param	command AssignProductToLoanAccountCommand
	 */	
	public void validate( AssignProductToLoanAccountCommand command ) throws Exception {
		Assert.notNull( command, "AssignProductToLoanAccountCommand should not be null" );
		Assert.notNull( command.getLoanAccountId(), "AssignProductToLoanAccountCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignProductToLoanAccountCommand assignment should not be null" );
	}

	/**
	 * handles unassign Product validation for a LoanAccount
	 * 
	 * @param	command UnAssignProductFromLoanAccountCommand
	 */	
	public void validate( UnAssignProductFromLoanAccountCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignProductFromLoanAccountCommand should not be null" );
		Assert.notNull( command.getLoanAccountId(), "UnAssignProductFromLoanAccountCommand identifier should not be null" );
	}

	/**
	 * handles add to Borrowers validation for a LoanAccount
	 * 
	 * @param	command AssignBorrowersToLoanAccountCommand
	 */	
	public void validate( AssignBorrowersToLoanAccountCommand command ) throws Exception {
		Assert.notNull( command, "AssignBorrowersToLoanAccountCommand should not be null" );
		Assert.notNull( command.getLoanAccountId(), "AssignBorrowersToLoanAccountCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignBorrowersToLoanAccountCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from Borrowers validation for a LoanAccount
	 * 
	 * @param	command RemoveBorrowersFromLoanAccountCommand
	 */	
	public void validate( RemoveBorrowersFromLoanAccountCommand command ) throws Exception {
		Assert.notNull( command, "RemoveBorrowersFromLoanAccountCommand should not be null" );
		Assert.notNull( command.getLoanAccountId(), "RemoveBorrowersFromLoanAccountCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveBorrowersFromLoanAccountCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getCustomerId(), "RemoveBorrowersFromLoanAccountCommand removeFrom attribubte identifier should not be null" );
	}
	
	/**
	 * handles add to RepaymentSchedule validation for a LoanAccount
	 * 
	 * @param	command AssignRepaymentScheduleToLoanAccountCommand
	 */	
	public void validate( AssignRepaymentScheduleToLoanAccountCommand command ) throws Exception {
		Assert.notNull( command, "AssignRepaymentScheduleToLoanAccountCommand should not be null" );
		Assert.notNull( command.getLoanAccountId(), "AssignRepaymentScheduleToLoanAccountCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignRepaymentScheduleToLoanAccountCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from RepaymentSchedule validation for a LoanAccount
	 * 
	 * @param	command RemoveRepaymentScheduleFromLoanAccountCommand
	 */	
	public void validate( RemoveRepaymentScheduleFromLoanAccountCommand command ) throws Exception {
		Assert.notNull( command, "RemoveRepaymentScheduleFromLoanAccountCommand should not be null" );
		Assert.notNull( command.getLoanAccountId(), "RemoveRepaymentScheduleFromLoanAccountCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveRepaymentScheduleFromLoanAccountCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getRepaymentScheduleId(), "RemoveRepaymentScheduleFromLoanAccountCommand removeFrom attribubte identifier should not be null" );
	}
	
	/**
	 * handles add to Payments validation for a LoanAccount
	 * 
	 * @param	command AssignPaymentsToLoanAccountCommand
	 */	
	public void validate( AssignPaymentsToLoanAccountCommand command ) throws Exception {
		Assert.notNull( command, "AssignPaymentsToLoanAccountCommand should not be null" );
		Assert.notNull( command.getLoanAccountId(), "AssignPaymentsToLoanAccountCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignPaymentsToLoanAccountCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from Payments validation for a LoanAccount
	 * 
	 * @param	command RemovePaymentsFromLoanAccountCommand
	 */	
	public void validate( RemovePaymentsFromLoanAccountCommand command ) throws Exception {
		Assert.notNull( command, "RemovePaymentsFromLoanAccountCommand should not be null" );
		Assert.notNull( command.getLoanAccountId(), "RemovePaymentsFromLoanAccountCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemovePaymentsFromLoanAccountCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getLoanPaymentId(), "RemovePaymentsFromLoanAccountCommand removeFrom attribubte identifier should not be null" );
	}
	
	/**
	 * handles add to Collateral validation for a LoanAccount
	 * 
	 * @param	command AssignCollateralToLoanAccountCommand
	 */	
	public void validate( AssignCollateralToLoanAccountCommand command ) throws Exception {
		Assert.notNull( command, "AssignCollateralToLoanAccountCommand should not be null" );
		Assert.notNull( command.getLoanAccountId(), "AssignCollateralToLoanAccountCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignCollateralToLoanAccountCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from Collateral validation for a LoanAccount
	 * 
	 * @param	command RemoveCollateralFromLoanAccountCommand
	 */	
	public void validate( RemoveCollateralFromLoanAccountCommand command ) throws Exception {
		Assert.notNull( command, "RemoveCollateralFromLoanAccountCommand should not be null" );
		Assert.notNull( command.getLoanAccountId(), "RemoveCollateralFromLoanAccountCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveCollateralFromLoanAccountCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getCollateralId(), "RemoveCollateralFromLoanAccountCommand removeFrom attribubte identifier should not be null" );
	}
	
	/**
	 * handles add to FeeCharges validation for a LoanAccount
	 * 
	 * @param	command AssignFeeChargesToLoanAccountCommand
	 */	
	public void validate( AssignFeeChargesToLoanAccountCommand command ) throws Exception {
		Assert.notNull( command, "AssignFeeChargesToLoanAccountCommand should not be null" );
		Assert.notNull( command.getLoanAccountId(), "AssignFeeChargesToLoanAccountCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignFeeChargesToLoanAccountCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from FeeCharges validation for a LoanAccount
	 * 
	 * @param	command RemoveFeeChargesFromLoanAccountCommand
	 */	
	public void validate( RemoveFeeChargesFromLoanAccountCommand command ) throws Exception {
		Assert.notNull( command, "RemoveFeeChargesFromLoanAccountCommand should not be null" );
		Assert.notNull( command.getLoanAccountId(), "RemoveFeeChargesFromLoanAccountCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveFeeChargesFromLoanAccountCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getFeeChargeId(), "RemoveFeeChargesFromLoanAccountCommand removeFrom attribubte identifier should not be null" );
	}
	

}
