/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.company.validator;

import org.springframework.util.Assert;

import com.company.api.*;

/**
 * <h2>PaymentCardValidation</h2>
 * <p>
 * The PaymentCard Validation  handles state validation of a PaymentCard include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>07/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreatePaymentCardCommand</li>
 *      <li>UpdatePaymentCardCommand</li>
 *      <li>DeletePaymentCardCommand</li>
 *set( false = false )
  *       <li>AssignBankToPaymentCardCommand</li>
 *       <li>UnAssignBankFromPaymentCardCommand</li>
  *       <li>AssignAccountToPaymentCardCommand</li>
 *       <li>UnAssignAccountFromPaymentCardCommand</li>
  *       <li>AssignCustomerToPaymentCardCommand</li>
 *       <li>UnAssignCustomerFromPaymentCardCommand</li>
   *       <li>AssignTransactionsToPaymentCardCommand</li>
 *       <li>RemoveTransactionsFromPaymentCardCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class PaymentCardValidator {
		
	/**
	 * default constructor
	 */
	protected PaymentCardValidator() {	
	}
	
	/**
	 * factory method
	 */
	static public PaymentCardValidator getInstance() {
		return new PaymentCardValidator();
	}
		
	/**
	 * handles creation validation for a PaymentCard
	 */
	public void validate( CreatePaymentCardCommand paymentCard )throws Exception {
		Assert.notNull( paymentCard, "CreatePaymentCardCommand should not be null" );
//		Assert.isNull( paymentCard.getPaymentCardId(), "CreatePaymentCardCommand identifier should be null" );
		Assert.notNull( paymentCard.getCardNumber(), "Field CreatePaymentCardCommand.cardNumber should not be null" );
		Assert.notNull( paymentCard.getEmbossedName(), "Field CreatePaymentCardCommand.embossedName should not be null" );
		Assert.notNull( paymentCard.getExpiryMonth(), "Field CreatePaymentCardCommand.expiryMonth should not be null" );
		Assert.notNull( paymentCard.getExpiryYear(), "Field CreatePaymentCardCommand.expiryYear should not be null" );
	}

	/**
	 * handles update validation for a PaymentCard
	 */
	public void validate( UpdatePaymentCardCommand paymentCard ) throws Exception {
		Assert.notNull( paymentCard, "UpdatePaymentCardCommand should not be null" );
		Assert.notNull( paymentCard.getPaymentCardId(), "UpdatePaymentCardCommand identifier should not be null" );
		Assert.notNull( paymentCard.getCardNumber(), "Field UpdatePaymentCardCommand.cardNumber should not be null" );
		Assert.notNull( paymentCard.getEmbossedName(), "Field UpdatePaymentCardCommand.embossedName should not be null" );
		Assert.notNull( paymentCard.getExpiryMonth(), "Field UpdatePaymentCardCommand.expiryMonth should not be null" );
		Assert.notNull( paymentCard.getExpiryYear(), "Field UpdatePaymentCardCommand.expiryYear should not be null" );
    }

	/**
	 * handles delete validation for a PaymentCard
	 */
    public void validate( DeletePaymentCardCommand paymentCard ) throws Exception {
		Assert.notNull( paymentCard, "{commandAlias} should not be null" );
		Assert.notNull( paymentCard.getPaymentCardId(), "DeletePaymentCardCommand identifier should not be null" );
	}
	
	/**
	 * handles fetchOne validation for a PaymentCard
	 */
	public void validate( PaymentCardFetchOneSummary summary ) throws Exception {
		Assert.notNull( summary, "PaymentCardFetchOneSummary should not be null" );
		Assert.notNull( summary.getPaymentCardId(), "PaymentCardFetchOneSummary identifier should not be null" );
	}

	/**
	 * handles assign Bank validation for a PaymentCard
	 * 
	 * @param	command AssignBankToPaymentCardCommand
	 */	
	public void validate( AssignBankToPaymentCardCommand command ) throws Exception {
		Assert.notNull( command, "AssignBankToPaymentCardCommand should not be null" );
		Assert.notNull( command.getPaymentCardId(), "AssignBankToPaymentCardCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignBankToPaymentCardCommand assignment should not be null" );
	}

	/**
	 * handles unassign Bank validation for a PaymentCard
	 * 
	 * @param	command UnAssignBankFromPaymentCardCommand
	 */	
	public void validate( UnAssignBankFromPaymentCardCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignBankFromPaymentCardCommand should not be null" );
		Assert.notNull( command.getPaymentCardId(), "UnAssignBankFromPaymentCardCommand identifier should not be null" );
	}
	/**
	 * handles assign Account validation for a PaymentCard
	 * 
	 * @param	command AssignAccountToPaymentCardCommand
	 */	
	public void validate( AssignAccountToPaymentCardCommand command ) throws Exception {
		Assert.notNull( command, "AssignAccountToPaymentCardCommand should not be null" );
		Assert.notNull( command.getPaymentCardId(), "AssignAccountToPaymentCardCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignAccountToPaymentCardCommand assignment should not be null" );
	}

	/**
	 * handles unassign Account validation for a PaymentCard
	 * 
	 * @param	command UnAssignAccountFromPaymentCardCommand
	 */	
	public void validate( UnAssignAccountFromPaymentCardCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignAccountFromPaymentCardCommand should not be null" );
		Assert.notNull( command.getPaymentCardId(), "UnAssignAccountFromPaymentCardCommand identifier should not be null" );
	}
	/**
	 * handles assign Customer validation for a PaymentCard
	 * 
	 * @param	command AssignCustomerToPaymentCardCommand
	 */	
	public void validate( AssignCustomerToPaymentCardCommand command ) throws Exception {
		Assert.notNull( command, "AssignCustomerToPaymentCardCommand should not be null" );
		Assert.notNull( command.getPaymentCardId(), "AssignCustomerToPaymentCardCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignCustomerToPaymentCardCommand assignment should not be null" );
	}

	/**
	 * handles unassign Customer validation for a PaymentCard
	 * 
	 * @param	command UnAssignCustomerFromPaymentCardCommand
	 */	
	public void validate( UnAssignCustomerFromPaymentCardCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignCustomerFromPaymentCardCommand should not be null" );
		Assert.notNull( command.getPaymentCardId(), "UnAssignCustomerFromPaymentCardCommand identifier should not be null" );
	}

	/**
	 * handles add to Transactions validation for a PaymentCard
	 * 
	 * @param	command AssignTransactionsToPaymentCardCommand
	 */	
	public void validate( AssignTransactionsToPaymentCardCommand command ) throws Exception {
		Assert.notNull( command, "AssignTransactionsToPaymentCardCommand should not be null" );
		Assert.notNull( command.getPaymentCardId(), "AssignTransactionsToPaymentCardCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignTransactionsToPaymentCardCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from Transactions validation for a PaymentCard
	 * 
	 * @param	command RemoveTransactionsFromPaymentCardCommand
	 */	
	public void validate( RemoveTransactionsFromPaymentCardCommand command ) throws Exception {
		Assert.notNull( command, "RemoveTransactionsFromPaymentCardCommand should not be null" );
		Assert.notNull( command.getPaymentCardId(), "RemoveTransactionsFromPaymentCardCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveTransactionsFromPaymentCardCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getTransactionId(), "RemoveTransactionsFromPaymentCardCommand removeFrom attribubte identifier should not be null" );
	}
	

}
