/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.company.validator;

import org.springframework.util.Assert;

import com.company.api.*;

/**
 * <h2>RepaymentScheduleValidation</h2>
 * <p>
 * The RepaymentSchedule Validation  handles state validation of a RepaymentSchedule include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>07/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateRepaymentScheduleCommand</li>
 *      <li>UpdateRepaymentScheduleCommand</li>
 *      <li>DeleteRepaymentScheduleCommand</li>
 *set( false = false )
  *       <li>AssignLoanAccountToRepaymentScheduleCommand</li>
 *       <li>UnAssignLoanAccountFromRepaymentScheduleCommand</li>
  *       <li>AssignPaymentToRepaymentScheduleCommand</li>
 *       <li>UnAssignPaymentFromRepaymentScheduleCommand</li>
   * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class RepaymentScheduleValidator {
		
	/**
	 * default constructor
	 */
	protected RepaymentScheduleValidator() {	
	}
	
	/**
	 * factory method
	 */
	static public RepaymentScheduleValidator getInstance() {
		return new RepaymentScheduleValidator();
	}
		
	/**
	 * handles creation validation for a RepaymentSchedule
	 */
	public void validate( CreateRepaymentScheduleCommand repaymentSchedule )throws Exception {
		Assert.notNull( repaymentSchedule, "CreateRepaymentScheduleCommand should not be null" );
//		Assert.isNull( repaymentSchedule.getRepaymentScheduleId(), "CreateRepaymentScheduleCommand identifier should be null" );
		Assert.notNull( repaymentSchedule.getInstallmentNumber(), "Field CreateRepaymentScheduleCommand.installmentNumber should not be null" );
		Assert.notNull( repaymentSchedule.getDueDate(), "Field CreateRepaymentScheduleCommand.dueDate should not be null" );
		Assert.notNull( repaymentSchedule.getPrincipalDue(), "Field CreateRepaymentScheduleCommand.principalDue should not be null" );
		Assert.notNull( repaymentSchedule.getInterestDue(), "Field CreateRepaymentScheduleCommand.interestDue should not be null" );
		Assert.notNull( repaymentSchedule.getTotalDue(), "Field CreateRepaymentScheduleCommand.totalDue should not be null" );
	}

	/**
	 * handles update validation for a RepaymentSchedule
	 */
	public void validate( UpdateRepaymentScheduleCommand repaymentSchedule ) throws Exception {
		Assert.notNull( repaymentSchedule, "UpdateRepaymentScheduleCommand should not be null" );
		Assert.notNull( repaymentSchedule.getRepaymentScheduleId(), "UpdateRepaymentScheduleCommand identifier should not be null" );
		Assert.notNull( repaymentSchedule.getInstallmentNumber(), "Field UpdateRepaymentScheduleCommand.installmentNumber should not be null" );
		Assert.notNull( repaymentSchedule.getDueDate(), "Field UpdateRepaymentScheduleCommand.dueDate should not be null" );
		Assert.notNull( repaymentSchedule.getPrincipalDue(), "Field UpdateRepaymentScheduleCommand.principalDue should not be null" );
		Assert.notNull( repaymentSchedule.getInterestDue(), "Field UpdateRepaymentScheduleCommand.interestDue should not be null" );
		Assert.notNull( repaymentSchedule.getTotalDue(), "Field UpdateRepaymentScheduleCommand.totalDue should not be null" );
    }

	/**
	 * handles delete validation for a RepaymentSchedule
	 */
    public void validate( DeleteRepaymentScheduleCommand repaymentSchedule ) throws Exception {
		Assert.notNull( repaymentSchedule, "{commandAlias} should not be null" );
		Assert.notNull( repaymentSchedule.getRepaymentScheduleId(), "DeleteRepaymentScheduleCommand identifier should not be null" );
	}
	
	/**
	 * handles fetchOne validation for a RepaymentSchedule
	 */
	public void validate( RepaymentScheduleFetchOneSummary summary ) throws Exception {
		Assert.notNull( summary, "RepaymentScheduleFetchOneSummary should not be null" );
		Assert.notNull( summary.getRepaymentScheduleId(), "RepaymentScheduleFetchOneSummary identifier should not be null" );
	}

	/**
	 * handles assign LoanAccount validation for a RepaymentSchedule
	 * 
	 * @param	command AssignLoanAccountToRepaymentScheduleCommand
	 */	
	public void validate( AssignLoanAccountToRepaymentScheduleCommand command ) throws Exception {
		Assert.notNull( command, "AssignLoanAccountToRepaymentScheduleCommand should not be null" );
		Assert.notNull( command.getRepaymentScheduleId(), "AssignLoanAccountToRepaymentScheduleCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignLoanAccountToRepaymentScheduleCommand assignment should not be null" );
	}

	/**
	 * handles unassign LoanAccount validation for a RepaymentSchedule
	 * 
	 * @param	command UnAssignLoanAccountFromRepaymentScheduleCommand
	 */	
	public void validate( UnAssignLoanAccountFromRepaymentScheduleCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignLoanAccountFromRepaymentScheduleCommand should not be null" );
		Assert.notNull( command.getRepaymentScheduleId(), "UnAssignLoanAccountFromRepaymentScheduleCommand identifier should not be null" );
	}
	/**
	 * handles assign Payment validation for a RepaymentSchedule
	 * 
	 * @param	command AssignPaymentToRepaymentScheduleCommand
	 */	
	public void validate( AssignPaymentToRepaymentScheduleCommand command ) throws Exception {
		Assert.notNull( command, "AssignPaymentToRepaymentScheduleCommand should not be null" );
		Assert.notNull( command.getRepaymentScheduleId(), "AssignPaymentToRepaymentScheduleCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignPaymentToRepaymentScheduleCommand assignment should not be null" );
	}

	/**
	 * handles unassign Payment validation for a RepaymentSchedule
	 * 
	 * @param	command UnAssignPaymentFromRepaymentScheduleCommand
	 */	
	public void validate( UnAssignPaymentFromRepaymentScheduleCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignPaymentFromRepaymentScheduleCommand should not be null" );
		Assert.notNull( command.getRepaymentScheduleId(), "UnAssignPaymentFromRepaymentScheduleCommand identifier should not be null" );
	}


}
