/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.company.validator;

import org.springframework.util.Assert;

import com.company.api.*;

/**
 * <h2>RiskAssessmentValidation</h2>
 * <p>
 * The RiskAssessment Validation  handles state validation of a RiskAssessment include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateRiskAssessmentCommand</li>
 *      <li>UpdateRiskAssessmentCommand</li>
 *      <li>DeleteRiskAssessmentCommand</li>
 *set( false = false )
  *       <li>AssignKycProfileToRiskAssessmentCommand</li>
 *       <li>UnAssignKycProfileFromRiskAssessmentCommand</li>
   * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class RiskAssessmentValidator {
		
	/**
	 * default constructor
	 */
	protected RiskAssessmentValidator() {	
	}
	
	/**
	 * factory method
	 */
	static public RiskAssessmentValidator getInstance() {
		return new RiskAssessmentValidator();
	}
		
	/**
	 * handles creation validation for a RiskAssessment
	 */
	public void validate( CreateRiskAssessmentCommand riskAssessment )throws Exception {
		Assert.notNull( riskAssessment, "CreateRiskAssessmentCommand should not be null" );
//		Assert.isNull( riskAssessment.getRiskAssessmentId(), "CreateRiskAssessmentCommand identifier should be null" );
		Assert.notNull( riskAssessment.getScore(), "Field CreateRiskAssessmentCommand.score should not be null" );
		Assert.notNull( riskAssessment.getAssessedOn(), "Field CreateRiskAssessmentCommand.assessedOn should not be null" );
	}

	/**
	 * handles update validation for a RiskAssessment
	 */
	public void validate( UpdateRiskAssessmentCommand riskAssessment ) throws Exception {
		Assert.notNull( riskAssessment, "UpdateRiskAssessmentCommand should not be null" );
		Assert.notNull( riskAssessment.getRiskAssessmentId(), "UpdateRiskAssessmentCommand identifier should not be null" );
		Assert.notNull( riskAssessment.getScore(), "Field UpdateRiskAssessmentCommand.score should not be null" );
		Assert.notNull( riskAssessment.getAssessedOn(), "Field UpdateRiskAssessmentCommand.assessedOn should not be null" );
    }

	/**
	 * handles delete validation for a RiskAssessment
	 */
    public void validate( DeleteRiskAssessmentCommand riskAssessment ) throws Exception {
		Assert.notNull( riskAssessment, "{commandAlias} should not be null" );
		Assert.notNull( riskAssessment.getRiskAssessmentId(), "DeleteRiskAssessmentCommand identifier should not be null" );
	}
	
	/**
	 * handles fetchOne validation for a RiskAssessment
	 */
	public void validate( RiskAssessmentFetchOneSummary summary ) throws Exception {
		Assert.notNull( summary, "RiskAssessmentFetchOneSummary should not be null" );
		Assert.notNull( summary.getRiskAssessmentId(), "RiskAssessmentFetchOneSummary identifier should not be null" );
	}

	/**
	 * handles assign KycProfile validation for a RiskAssessment
	 * 
	 * @param	command AssignKycProfileToRiskAssessmentCommand
	 */	
	public void validate( AssignKycProfileToRiskAssessmentCommand command ) throws Exception {
		Assert.notNull( command, "AssignKycProfileToRiskAssessmentCommand should not be null" );
		Assert.notNull( command.getRiskAssessmentId(), "AssignKycProfileToRiskAssessmentCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignKycProfileToRiskAssessmentCommand assignment should not be null" );
	}

	/**
	 * handles unassign KycProfile validation for a RiskAssessment
	 * 
	 * @param	command UnAssignKycProfileFromRiskAssessmentCommand
	 */	
	public void validate( UnAssignKycProfileFromRiskAssessmentCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignKycProfileFromRiskAssessmentCommand should not be null" );
		Assert.notNull( command.getRiskAssessmentId(), "UnAssignKycProfileFromRiskAssessmentCommand identifier should not be null" );
	}


}
