/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.company.validator;

import org.springframework.util.Assert;

import com.company.api.*;

/**
 * <h2>ScreeningResultValidation</h2>
 * <p>
 * The ScreeningResult Validation  handles state validation of a ScreeningResult include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>07/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateScreeningResultCommand</li>
 *      <li>UpdateScreeningResultCommand</li>
 *      <li>DeleteScreeningResultCommand</li>
 *set( false = false )
  *       <li>AssignKycProfileToScreeningResultCommand</li>
 *       <li>UnAssignKycProfileFromScreeningResultCommand</li>
   * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class ScreeningResultValidator {
		
	/**
	 * default constructor
	 */
	protected ScreeningResultValidator() {	
	}
	
	/**
	 * factory method
	 */
	static public ScreeningResultValidator getInstance() {
		return new ScreeningResultValidator();
	}
		
	/**
	 * handles creation validation for a ScreeningResult
	 */
	public void validate( CreateScreeningResultCommand screeningResult )throws Exception {
		Assert.notNull( screeningResult, "CreateScreeningResultCommand should not be null" );
//		Assert.isNull( screeningResult.getScreeningResultId(), "CreateScreeningResultCommand identifier should be null" );
		Assert.notNull( screeningResult.getScreeningDate(), "Field CreateScreeningResultCommand.screeningDate should not be null" );
		Assert.notNull( screeningResult.getProvider(), "Field CreateScreeningResultCommand.provider should not be null" );
	}

	/**
	 * handles update validation for a ScreeningResult
	 */
	public void validate( UpdateScreeningResultCommand screeningResult ) throws Exception {
		Assert.notNull( screeningResult, "UpdateScreeningResultCommand should not be null" );
		Assert.notNull( screeningResult.getScreeningResultId(), "UpdateScreeningResultCommand identifier should not be null" );
		Assert.notNull( screeningResult.getScreeningDate(), "Field UpdateScreeningResultCommand.screeningDate should not be null" );
		Assert.notNull( screeningResult.getProvider(), "Field UpdateScreeningResultCommand.provider should not be null" );
    }

	/**
	 * handles delete validation for a ScreeningResult
	 */
    public void validate( DeleteScreeningResultCommand screeningResult ) throws Exception {
		Assert.notNull( screeningResult, "{commandAlias} should not be null" );
		Assert.notNull( screeningResult.getScreeningResultId(), "DeleteScreeningResultCommand identifier should not be null" );
	}
	
	/**
	 * handles fetchOne validation for a ScreeningResult
	 */
	public void validate( ScreeningResultFetchOneSummary summary ) throws Exception {
		Assert.notNull( summary, "ScreeningResultFetchOneSummary should not be null" );
		Assert.notNull( summary.getScreeningResultId(), "ScreeningResultFetchOneSummary identifier should not be null" );
	}

	/**
	 * handles assign KycProfile validation for a ScreeningResult
	 * 
	 * @param	command AssignKycProfileToScreeningResultCommand
	 */	
	public void validate( AssignKycProfileToScreeningResultCommand command ) throws Exception {
		Assert.notNull( command, "AssignKycProfileToScreeningResultCommand should not be null" );
		Assert.notNull( command.getScreeningResultId(), "AssignKycProfileToScreeningResultCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignKycProfileToScreeningResultCommand assignment should not be null" );
	}

	/**
	 * handles unassign KycProfile validation for a ScreeningResult
	 * 
	 * @param	command UnAssignKycProfileFromScreeningResultCommand
	 */	
	public void validate( UnAssignKycProfileFromScreeningResultCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignKycProfileFromScreeningResultCommand should not be null" );
		Assert.notNull( command.getScreeningResultId(), "UnAssignKycProfileFromScreeningResultCommand identifier should not be null" );
	}


}
