/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.company.validator;

import org.springframework.util.Assert;

import com.company.api.*;

/**
 * <h2>StandingInstructionValidation</h2>
 * <p>
 * The StandingInstruction Validation  handles state validation of a StandingInstruction include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateStandingInstructionCommand</li>
 *      <li>UpdateStandingInstructionCommand</li>
 *      <li>DeleteStandingInstructionCommand</li>
 *set( false = false )
  *       <li>AssignAccountToStandingInstructionCommand</li>
 *       <li>UnAssignAccountFromStandingInstructionCommand</li>
  *       <li>AssignBeneficiaryToStandingInstructionCommand</li>
 *       <li>UnAssignBeneficiaryFromStandingInstructionCommand</li>
   * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class StandingInstructionValidator {
		
	/**
	 * default constructor
	 */
	protected StandingInstructionValidator() {	
	}
	
	/**
	 * factory method
	 */
	static public StandingInstructionValidator getInstance() {
		return new StandingInstructionValidator();
	}
		
	/**
	 * handles creation validation for a StandingInstruction
	 */
	public void validate( CreateStandingInstructionCommand standingInstruction )throws Exception {
		Assert.notNull( standingInstruction, "CreateStandingInstructionCommand should not be null" );
//		Assert.isNull( standingInstruction.getStandingInstructionId(), "CreateStandingInstructionCommand identifier should be null" );
		Assert.notNull( standingInstruction.getInstructionId(), "Field CreateStandingInstructionCommand.instructionId should not be null" );
		Assert.notNull( standingInstruction.getAmount(), "Field CreateStandingInstructionCommand.amount should not be null" );
		Assert.notNull( standingInstruction.getNextExecutionDate(), "Field CreateStandingInstructionCommand.nextExecutionDate should not be null" );
	}

	/**
	 * handles update validation for a StandingInstruction
	 */
	public void validate( UpdateStandingInstructionCommand standingInstruction ) throws Exception {
		Assert.notNull( standingInstruction, "UpdateStandingInstructionCommand should not be null" );
		Assert.notNull( standingInstruction.getStandingInstructionId(), "UpdateStandingInstructionCommand identifier should not be null" );
		Assert.notNull( standingInstruction.getInstructionId(), "Field UpdateStandingInstructionCommand.instructionId should not be null" );
		Assert.notNull( standingInstruction.getAmount(), "Field UpdateStandingInstructionCommand.amount should not be null" );
		Assert.notNull( standingInstruction.getNextExecutionDate(), "Field UpdateStandingInstructionCommand.nextExecutionDate should not be null" );
    }

	/**
	 * handles delete validation for a StandingInstruction
	 */
    public void validate( DeleteStandingInstructionCommand standingInstruction ) throws Exception {
		Assert.notNull( standingInstruction, "{commandAlias} should not be null" );
		Assert.notNull( standingInstruction.getStandingInstructionId(), "DeleteStandingInstructionCommand identifier should not be null" );
	}
	
	/**
	 * handles fetchOne validation for a StandingInstruction
	 */
	public void validate( StandingInstructionFetchOneSummary summary ) throws Exception {
		Assert.notNull( summary, "StandingInstructionFetchOneSummary should not be null" );
		Assert.notNull( summary.getStandingInstructionId(), "StandingInstructionFetchOneSummary identifier should not be null" );
	}

	/**
	 * handles assign Account validation for a StandingInstruction
	 * 
	 * @param	command AssignAccountToStandingInstructionCommand
	 */	
	public void validate( AssignAccountToStandingInstructionCommand command ) throws Exception {
		Assert.notNull( command, "AssignAccountToStandingInstructionCommand should not be null" );
		Assert.notNull( command.getStandingInstructionId(), "AssignAccountToStandingInstructionCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignAccountToStandingInstructionCommand assignment should not be null" );
	}

	/**
	 * handles unassign Account validation for a StandingInstruction
	 * 
	 * @param	command UnAssignAccountFromStandingInstructionCommand
	 */	
	public void validate( UnAssignAccountFromStandingInstructionCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignAccountFromStandingInstructionCommand should not be null" );
		Assert.notNull( command.getStandingInstructionId(), "UnAssignAccountFromStandingInstructionCommand identifier should not be null" );
	}
	/**
	 * handles assign Beneficiary validation for a StandingInstruction
	 * 
	 * @param	command AssignBeneficiaryToStandingInstructionCommand
	 */	
	public void validate( AssignBeneficiaryToStandingInstructionCommand command ) throws Exception {
		Assert.notNull( command, "AssignBeneficiaryToStandingInstructionCommand should not be null" );
		Assert.notNull( command.getStandingInstructionId(), "AssignBeneficiaryToStandingInstructionCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignBeneficiaryToStandingInstructionCommand assignment should not be null" );
	}

	/**
	 * handles unassign Beneficiary validation for a StandingInstruction
	 * 
	 * @param	command UnAssignBeneficiaryFromStandingInstructionCommand
	 */	
	public void validate( UnAssignBeneficiaryFromStandingInstructionCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignBeneficiaryFromStandingInstructionCommand should not be null" );
		Assert.notNull( command.getStandingInstructionId(), "UnAssignBeneficiaryFromStandingInstructionCommand identifier should not be null" );
	}


}
