/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.company.validator;

import org.springframework.util.Assert;

import com.company.api.*;

/**
 * <h2>ThirdPartyProviderValidation</h2>
 * <p>
 * The ThirdPartyProvider Validation  handles state validation of a ThirdPartyProvider include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateThirdPartyProviderCommand</li>
 *      <li>UpdateThirdPartyProviderCommand</li>
 *      <li>DeleteThirdPartyProviderCommand</li>
 *set( false = false )
  *       <li>AssignBankToThirdPartyProviderCommand</li>
 *       <li>UnAssignBankFromThirdPartyProviderCommand</li>
   *       <li>AssignConsentsToThirdPartyProviderCommand</li>
 *       <li>RemoveConsentsFromThirdPartyProviderCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class ThirdPartyProviderValidator {
		
	/**
	 * default constructor
	 */
	protected ThirdPartyProviderValidator() {	
	}
	
	/**
	 * factory method
	 */
	static public ThirdPartyProviderValidator getInstance() {
		return new ThirdPartyProviderValidator();
	}
		
	/**
	 * handles creation validation for a ThirdPartyProvider
	 */
	public void validate( CreateThirdPartyProviderCommand thirdPartyProvider )throws Exception {
		Assert.notNull( thirdPartyProvider, "CreateThirdPartyProviderCommand should not be null" );
//		Assert.isNull( thirdPartyProvider.getThirdPartyProviderId(), "CreateThirdPartyProviderCommand identifier should be null" );
		Assert.notNull( thirdPartyProvider.getName(), "Field CreateThirdPartyProviderCommand.name should not be null" );
		Assert.notNull( thirdPartyProvider.getRegistrationId(), "Field CreateThirdPartyProviderCommand.registrationId should not be null" );
		Assert.notNull( thirdPartyProvider.getWebsite(), "Field CreateThirdPartyProviderCommand.website should not be null" );
	}

	/**
	 * handles update validation for a ThirdPartyProvider
	 */
	public void validate( UpdateThirdPartyProviderCommand thirdPartyProvider ) throws Exception {
		Assert.notNull( thirdPartyProvider, "UpdateThirdPartyProviderCommand should not be null" );
		Assert.notNull( thirdPartyProvider.getThirdPartyProviderId(), "UpdateThirdPartyProviderCommand identifier should not be null" );
		Assert.notNull( thirdPartyProvider.getName(), "Field UpdateThirdPartyProviderCommand.name should not be null" );
		Assert.notNull( thirdPartyProvider.getRegistrationId(), "Field UpdateThirdPartyProviderCommand.registrationId should not be null" );
		Assert.notNull( thirdPartyProvider.getWebsite(), "Field UpdateThirdPartyProviderCommand.website should not be null" );
    }

	/**
	 * handles delete validation for a ThirdPartyProvider
	 */
    public void validate( DeleteThirdPartyProviderCommand thirdPartyProvider ) throws Exception {
		Assert.notNull( thirdPartyProvider, "{commandAlias} should not be null" );
		Assert.notNull( thirdPartyProvider.getThirdPartyProviderId(), "DeleteThirdPartyProviderCommand identifier should not be null" );
	}
	
	/**
	 * handles fetchOne validation for a ThirdPartyProvider
	 */
	public void validate( ThirdPartyProviderFetchOneSummary summary ) throws Exception {
		Assert.notNull( summary, "ThirdPartyProviderFetchOneSummary should not be null" );
		Assert.notNull( summary.getThirdPartyProviderId(), "ThirdPartyProviderFetchOneSummary identifier should not be null" );
	}

	/**
	 * handles assign Bank validation for a ThirdPartyProvider
	 * 
	 * @param	command AssignBankToThirdPartyProviderCommand
	 */	
	public void validate( AssignBankToThirdPartyProviderCommand command ) throws Exception {
		Assert.notNull( command, "AssignBankToThirdPartyProviderCommand should not be null" );
		Assert.notNull( command.getThirdPartyProviderId(), "AssignBankToThirdPartyProviderCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignBankToThirdPartyProviderCommand assignment should not be null" );
	}

	/**
	 * handles unassign Bank validation for a ThirdPartyProvider
	 * 
	 * @param	command UnAssignBankFromThirdPartyProviderCommand
	 */	
	public void validate( UnAssignBankFromThirdPartyProviderCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignBankFromThirdPartyProviderCommand should not be null" );
		Assert.notNull( command.getThirdPartyProviderId(), "UnAssignBankFromThirdPartyProviderCommand identifier should not be null" );
	}

	/**
	 * handles add to Consents validation for a ThirdPartyProvider
	 * 
	 * @param	command AssignConsentsToThirdPartyProviderCommand
	 */	
	public void validate( AssignConsentsToThirdPartyProviderCommand command ) throws Exception {
		Assert.notNull( command, "AssignConsentsToThirdPartyProviderCommand should not be null" );
		Assert.notNull( command.getThirdPartyProviderId(), "AssignConsentsToThirdPartyProviderCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignConsentsToThirdPartyProviderCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from Consents validation for a ThirdPartyProvider
	 * 
	 * @param	command RemoveConsentsFromThirdPartyProviderCommand
	 */	
	public void validate( RemoveConsentsFromThirdPartyProviderCommand command ) throws Exception {
		Assert.notNull( command, "RemoveConsentsFromThirdPartyProviderCommand should not be null" );
		Assert.notNull( command.getThirdPartyProviderId(), "RemoveConsentsFromThirdPartyProviderCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveConsentsFromThirdPartyProviderCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getConsentId(), "RemoveConsentsFromThirdPartyProviderCommand removeFrom attribubte identifier should not be null" );
	}
	

}
