/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.company.validator;

import org.springframework.util.Assert;

import com.company.api.*;

/**
 * <h2>TransactionValidation</h2>
 * <p>
 * The Transaction Validation  handles state validation of a Transaction include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateTransactionCommand</li>
 *      <li>UpdateTransactionCommand</li>
 *      <li>DeleteTransactionCommand</li>
 *set( false = false )
  *       <li>AssignAccountToTransactionCommand</li>
 *       <li>UnAssignAccountFromTransactionCommand</li>
  *       <li>AssignExternalCounterpartyToTransactionCommand</li>
 *       <li>UnAssignExternalCounterpartyFromTransactionCommand</li>
  *       <li>AssignPaymentCardToTransactionCommand</li>
 *       <li>UnAssignPaymentCardFromTransactionCommand</li>
  *       <li>AssignFundsTransferToTransactionCommand</li>
 *       <li>UnAssignFundsTransferFromTransactionCommand</li>
  *       <li>AssignFxTradeToTransactionCommand</li>
 *       <li>UnAssignFxTradeFromTransactionCommand</li>
  *       <li>AssignDisputeToTransactionCommand</li>
 *       <li>UnAssignDisputeFromTransactionCommand</li>
   * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class TransactionValidator {
		
	/**
	 * default constructor
	 */
	protected TransactionValidator() {	
	}
	
	/**
	 * factory method
	 */
	static public TransactionValidator getInstance() {
		return new TransactionValidator();
	}
		
	/**
	 * handles creation validation for a Transaction
	 */
	public void validate( CreateTransactionCommand transaction )throws Exception {
		Assert.notNull( transaction, "CreateTransactionCommand should not be null" );
//		Assert.isNull( transaction.getTransactionId(), "CreateTransactionCommand identifier should be null" );
		Assert.notNull( transaction.getBookingDate(), "Field CreateTransactionCommand.bookingDate should not be null" );
		Assert.notNull( transaction.getValueDate(), "Field CreateTransactionCommand.valueDate should not be null" );
		Assert.notNull( transaction.getAmount(), "Field CreateTransactionCommand.amount should not be null" );
		Assert.notNull( transaction.getDescription(), "Field CreateTransactionCommand.description should not be null" );
	}

	/**
	 * handles update validation for a Transaction
	 */
	public void validate( UpdateTransactionCommand transaction ) throws Exception {
		Assert.notNull( transaction, "UpdateTransactionCommand should not be null" );
		Assert.notNull( transaction.getTransactionId(), "UpdateTransactionCommand identifier should not be null" );
		Assert.notNull( transaction.getBookingDate(), "Field UpdateTransactionCommand.bookingDate should not be null" );
		Assert.notNull( transaction.getValueDate(), "Field UpdateTransactionCommand.valueDate should not be null" );
		Assert.notNull( transaction.getAmount(), "Field UpdateTransactionCommand.amount should not be null" );
		Assert.notNull( transaction.getDescription(), "Field UpdateTransactionCommand.description should not be null" );
    }

	/**
	 * handles delete validation for a Transaction
	 */
    public void validate( DeleteTransactionCommand transaction ) throws Exception {
		Assert.notNull( transaction, "{commandAlias} should not be null" );
		Assert.notNull( transaction.getTransactionId(), "DeleteTransactionCommand identifier should not be null" );
	}
	
	/**
	 * handles fetchOne validation for a Transaction
	 */
	public void validate( TransactionFetchOneSummary summary ) throws Exception {
		Assert.notNull( summary, "TransactionFetchOneSummary should not be null" );
		Assert.notNull( summary.getTransactionId(), "TransactionFetchOneSummary identifier should not be null" );
	}

	/**
	 * handles assign Account validation for a Transaction
	 * 
	 * @param	command AssignAccountToTransactionCommand
	 */	
	public void validate( AssignAccountToTransactionCommand command ) throws Exception {
		Assert.notNull( command, "AssignAccountToTransactionCommand should not be null" );
		Assert.notNull( command.getTransactionId(), "AssignAccountToTransactionCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignAccountToTransactionCommand assignment should not be null" );
	}

	/**
	 * handles unassign Account validation for a Transaction
	 * 
	 * @param	command UnAssignAccountFromTransactionCommand
	 */	
	public void validate( UnAssignAccountFromTransactionCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignAccountFromTransactionCommand should not be null" );
		Assert.notNull( command.getTransactionId(), "UnAssignAccountFromTransactionCommand identifier should not be null" );
	}
	/**
	 * handles assign ExternalCounterparty validation for a Transaction
	 * 
	 * @param	command AssignExternalCounterpartyToTransactionCommand
	 */	
	public void validate( AssignExternalCounterpartyToTransactionCommand command ) throws Exception {
		Assert.notNull( command, "AssignExternalCounterpartyToTransactionCommand should not be null" );
		Assert.notNull( command.getTransactionId(), "AssignExternalCounterpartyToTransactionCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignExternalCounterpartyToTransactionCommand assignment should not be null" );
	}

	/**
	 * handles unassign ExternalCounterparty validation for a Transaction
	 * 
	 * @param	command UnAssignExternalCounterpartyFromTransactionCommand
	 */	
	public void validate( UnAssignExternalCounterpartyFromTransactionCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignExternalCounterpartyFromTransactionCommand should not be null" );
		Assert.notNull( command.getTransactionId(), "UnAssignExternalCounterpartyFromTransactionCommand identifier should not be null" );
	}
	/**
	 * handles assign PaymentCard validation for a Transaction
	 * 
	 * @param	command AssignPaymentCardToTransactionCommand
	 */	
	public void validate( AssignPaymentCardToTransactionCommand command ) throws Exception {
		Assert.notNull( command, "AssignPaymentCardToTransactionCommand should not be null" );
		Assert.notNull( command.getTransactionId(), "AssignPaymentCardToTransactionCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignPaymentCardToTransactionCommand assignment should not be null" );
	}

	/**
	 * handles unassign PaymentCard validation for a Transaction
	 * 
	 * @param	command UnAssignPaymentCardFromTransactionCommand
	 */	
	public void validate( UnAssignPaymentCardFromTransactionCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignPaymentCardFromTransactionCommand should not be null" );
		Assert.notNull( command.getTransactionId(), "UnAssignPaymentCardFromTransactionCommand identifier should not be null" );
	}
	/**
	 * handles assign FundsTransfer validation for a Transaction
	 * 
	 * @param	command AssignFundsTransferToTransactionCommand
	 */	
	public void validate( AssignFundsTransferToTransactionCommand command ) throws Exception {
		Assert.notNull( command, "AssignFundsTransferToTransactionCommand should not be null" );
		Assert.notNull( command.getTransactionId(), "AssignFundsTransferToTransactionCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignFundsTransferToTransactionCommand assignment should not be null" );
	}

	/**
	 * handles unassign FundsTransfer validation for a Transaction
	 * 
	 * @param	command UnAssignFundsTransferFromTransactionCommand
	 */	
	public void validate( UnAssignFundsTransferFromTransactionCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignFundsTransferFromTransactionCommand should not be null" );
		Assert.notNull( command.getTransactionId(), "UnAssignFundsTransferFromTransactionCommand identifier should not be null" );
	}
	/**
	 * handles assign FxTrade validation for a Transaction
	 * 
	 * @param	command AssignFxTradeToTransactionCommand
	 */	
	public void validate( AssignFxTradeToTransactionCommand command ) throws Exception {
		Assert.notNull( command, "AssignFxTradeToTransactionCommand should not be null" );
		Assert.notNull( command.getTransactionId(), "AssignFxTradeToTransactionCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignFxTradeToTransactionCommand assignment should not be null" );
	}

	/**
	 * handles unassign FxTrade validation for a Transaction
	 * 
	 * @param	command UnAssignFxTradeFromTransactionCommand
	 */	
	public void validate( UnAssignFxTradeFromTransactionCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignFxTradeFromTransactionCommand should not be null" );
		Assert.notNull( command.getTransactionId(), "UnAssignFxTradeFromTransactionCommand identifier should not be null" );
	}
	/**
	 * handles assign Dispute validation for a Transaction
	 * 
	 * @param	command AssignDisputeToTransactionCommand
	 */	
	public void validate( AssignDisputeToTransactionCommand command ) throws Exception {
		Assert.notNull( command, "AssignDisputeToTransactionCommand should not be null" );
		Assert.notNull( command.getTransactionId(), "AssignDisputeToTransactionCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignDisputeToTransactionCommand assignment should not be null" );
	}

	/**
	 * handles unassign Dispute validation for a Transaction
	 * 
	 * @param	command UnAssignDisputeFromTransactionCommand
	 */	
	public void validate( UnAssignDisputeFromTransactionCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignDisputeFromTransactionCommand should not be null" );
		Assert.notNull( command.getTransactionId(), "UnAssignDisputeFromTransactionCommand identifier should not be null" );
	}


}
