/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.company.controller.query;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.concurrent.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.company.api.*;
import com.company.delegate.*;
import com.company.entity.*;
import com.company.exception.*;
import com.company.projector.*;

import com.company.controller.*;

/**
 * <h2>DisputeQueryRestController as REST API</h2>
 * <p>
 * Implements Spring Controller query CQRS processing for entity Dispute.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>07/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	DisputeBusinessDelegate
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateDisputeCommand</li>
 *      <li></li>UpdateDisputeCommand</li>
 *      <liDeleteDisputeCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 */
@CrossOrigin
@RestController
@RequestMapping("/DisputeQuery")
public class DisputeQueryRestController extends BaseSpringRestController {
	
    /**
     * Handles loading a Dispute using a UUID
     * @param		UUID disputeId
     * @return		Dispute
     */    
    @GetMapping("/load")
    public Dispute load( @RequestParam(required=true) UUID disputeId ) {
    	Dispute entity = null;

    	try {  
    		entity = DisputeBusinessDelegate.getDisputeInstance().getDispute( new DisputeFetchOneSummary( disputeId ) );
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING, "failed to load Dispute using Id " + disputeId );
            return null;
        }

        return entity;
    }

    /**
     * Handles loading all Dispute business objects
     * @return		Set<Dispute>
     */
    @GetMapping("/")
    public List<Dispute> loadAll() {                
    	List<Dispute> disputeList = null;
        
    	try {
            // load the Dispute
            disputeList = DisputeBusinessDelegate.getDisputeInstance().getAllDispute();
            
            if ( disputeList != null )
                LOGGER.log( Level.INFO,  "successfully loaded all Disputes" );
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING,  "failed to load all Disputes ", exc );
        	return null;
        }

        return disputeList;
                            
    }



//************************************************************************    
// Attributes
//************************************************************************
    protected Dispute dispute = null;
    private static final Logger LOGGER = Logger.getLogger(DisputeQueryRestController.class.getName());
    
}
