/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.company.controller.query;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.concurrent.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.company.api.*;
import com.company.delegate.*;
import com.company.entity.*;
import com.company.exception.*;
import com.company.projector.*;

import com.company.controller.*;

/**
 * <h2>PaymentCardQueryRestController as REST API</h2>
 * <p>
 * Implements Spring Controller query CQRS processing for entity PaymentCard.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	PaymentCardBusinessDelegate
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreatePaymentCardCommand</li>
 *      <li></li>UpdatePaymentCardCommand</li>
 *      <liDeletePaymentCardCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 */
@CrossOrigin
@RestController
@RequestMapping("/PaymentCardQuery")
public class PaymentCardQueryRestController extends BaseSpringRestController {
	
    /**
     * Handles loading a PaymentCard using a UUID
     * @param		UUID paymentCardId
     * @return		PaymentCard
     */    
    @GetMapping("/load")
    public PaymentCard load( @RequestParam(required=true) UUID paymentCardId ) {
    	PaymentCard entity = null;

    	try {  
    		entity = PaymentCardBusinessDelegate.getPaymentCardInstance().getPaymentCard( new PaymentCardFetchOneSummary( paymentCardId ) );
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING, "failed to load PaymentCard using Id " + paymentCardId );
            return null;
        }

        return entity;
    }

    /**
     * Handles loading all PaymentCard business objects
     * @return		Set<PaymentCard>
     */
    @GetMapping("/")
    public List<PaymentCard> loadAll() {                
    	List<PaymentCard> paymentCardList = null;
        
    	try {
            // load the PaymentCard
            paymentCardList = PaymentCardBusinessDelegate.getPaymentCardInstance().getAllPaymentCard();
            
            if ( paymentCardList != null )
                LOGGER.log( Level.INFO,  "successfully loaded all PaymentCards" );
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING,  "failed to load all PaymentCards ", exc );
        	return null;
        }

        return paymentCardList;
                            
    }



//************************************************************************    
// Attributes
//************************************************************************
    protected PaymentCard paymentCard = null;
    private static final Logger LOGGER = Logger.getLogger(PaymentCardQueryRestController.class.getName());
    
}
